### ISSUE TITLE
ValueError: cannot convert float NaN to integer (migrated from Trac #956)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2509]
Original ticket http://projects.scipy.org/numpy/ticket/956
Reported 2008-11-20 by atmention:cournape, assigned to atmention:pierregm.

Python 2.6 specific error:

```
ERROR: Tests the min/max functions with explicit outputs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/bbc8/python2.6/lib/python2.6/site-packages/numpy/ma/tests/test_core.py", line 700, in test_minmax_funcs_with_output
    result = npfunc(xm,axis=0,out=nout)
  File "/export/bbc8/python2.6/stow/numpy.svn//lib/python2.6/site-packages/numpy/core/fromnumeric.py", line 1569, in amin
    return amin(axis, out)
  File "/export/bbc8/python2.6/stow/numpy.svn//lib/python2.6/site-packages/numpy/ma/core.py", line 3188, in min
    np.putmask(out, newmask, np.nan)
ValueError: cannot convert float NaN to integer
```

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-11-20

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-12-30

Has been fixed.
