### ISSUE TITLE
numpy failures on mac os X (python 2.6) (migrated from Trac #958)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2511]
Original ticket http://projects.scipy.org/numpy/ticket/958
Reported 2008-11-24 by atmention:cournape, assigned to atmention:cournape.

```
======================================================================
ERROR: Tests the min/max functions with explicit outputs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/ma/tests/test_core.py", line 704, in test_minmax_funcs_with_output
    result = npfunc(xm,axis=0,out=nout)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/fromnumeric.py", line 1569, in amin
    return amin(axis, out)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/ma/core.py", line 3192, in min
    np.putmask(out, newmask, np.nan)
ValueError: cannot convert float NaN to integer

======================================================================
FAIL: test_basic (test_multiarray.TestClip)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_multiarray.py", line 677, in test_basic
    self._clip_type('float',1024,-12.8,100.2, inplace=inplace)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_multiarray.py", line 671, in _clip_type
    assert_equal(x.dtype.byteorder,byteorder)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: '>'
 DESIRED: '='

======================================================================
FAIL: test_binary (test_multiarray.TestFromstring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_multiarray.py", line 120, in test_binary
    assert_array_equal(a, array([1,2,3,4]))
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 303, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 295, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([  4.60060299e-41,   8.96831017e-44,   2.30485571e-41,
         4.60074312e-41], dtype=float32)
 y: array([1, 2, 3, 4])

======================================================================
FAIL: test_version0_float32 (test_multiarray.TestPickling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_multiarray.py", line 543, in test_version0_float32
    assert_equal(a, p)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 180, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 303, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 295, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([ 1.,  2.,  3.,  4.], dtype=float32)
 y: array([  4.60060299e-41,   8.96831017e-44,   2.30485571e-41,
         4.60074312e-41], dtype=float32)

======================================================================
FAIL: test_version1_float32 (test_multiarray.TestPickling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_multiarray.py", line 562, in test_version1_float32
    assert_equal(a, p)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 180, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 303, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 295, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([ 1.,  2.,  3.,  4.], dtype=float32)
 y: array([  4.60060299e-41,   8.96831017e-44,   2.30485571e-41,
         4.60074312e-41], dtype=float32)

======================================================================
FAIL: test_basic (test_multiarray.TestView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_multiarray.py", line 894, in test_basic
    assert_array_equal(y, [67305985, 134678021])
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 303, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 295, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([16909060, 84281096])
 y: array([ 67305985, 134678021])

======================================================================
FAIL: test_keywords (test_multiarray.TestView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_multiarray.py", line 904, in test_keywords
    assert_array_equal(y,[[513]])
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 303, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 295, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([[258]], dtype=int16)
 y: array([[513]])

======================================================================
FAIL: Test non native double input with scalar min/max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numeric.py", line 437, in test_simple_nonnative
    a   = self._generate_non_native_data(self.nr, self.nc)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numeric.py", line 396, in _generate_non_native_data
    assert not data.dtype.isnative
AssertionError

======================================================================
FAIL: Test NON native with native array min/max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numeric.py", line 632, in test_type_cast_07
    assert not a_s.dtype.isnative
AssertionError

======================================================================
FAIL: Test NON native with native scalar min/max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numeric.py", line 643, in test_type_cast_08
    assert not a_s.dtype.isnative
AssertionError

======================================================================
FAIL: Test native with NON native array min/max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numeric.py", line 654, in test_type_cast_09
    assert not m_s.dtype.isnative
AssertionError

======================================================================
FAIL: Test non native with native scalar, min/max, out non native
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numeric.py", line 671, in test_type_cast_11
    a   = self._generate_non_native_data(self.nr, self.nc)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numeric.py", line 396, in _generate_non_native_data
    assert not data.dtype.isnative
AssertionError

======================================================================
FAIL: Check creation from list of list of tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 167, in test_list_of_list_of_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from list of tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 158, in test_list_of_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 149, in test_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from list of list of tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 167, in test_list_of_list_of_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from list of tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 158, in test_list_of_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 149, in test_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from list of list of tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 167, in test_list_of_list_of_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from list of tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 158, in test_list_of_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 149, in test_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from list of list of tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 167, in test_list_of_list_of_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from list of tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 158, in test_list_of_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation from tuples
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 149, in test_tuple
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation of 0-dimensional objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 106, in test_zeros0D
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation of multi-dimensional objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 126, in test_zerosMD
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation of single-dimensional objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 116, in test_zerosSD
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation of 0-dimensional objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 106, in test_zeros0D
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation of multi-dimensional objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 126, in test_zerosMD
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: Check creation of single-dimensional objects
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_numerictypes.py", line 116, in test_zerosSD
    self.assert_(normalize_descr(self._descr) == h.dtype.descr)
AssertionError

======================================================================
FAIL: test_method_array (test_records.TestFromrecords)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_records.py", line 13, in test_method_array
    assert_equal(r[1].item(), (25444, 'efg', 1633837924))
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 176, in assert_equal
    assert_equal(actual[k], desired[k], 'item=%r\n%s' % (k,err_msg), verbose)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/testing/utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
item=0

 ACTUAL: 25699
 DESIRED: 25444

======================================================================
FAIL: test_umath.TestComplexFunctions.test_against_cmath
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/david/pylocal//lib/python2.6/site-packages/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/Users/david/pylocal/lib/python2.6/site-packages/numpy/core/tests/test_umath.py", line 423, in test_against_cmath
    assert abs(a - b) < atol, "%s %s: %s; cmath: %s"%(fname,p,a,b)
AssertionError: arcsin 2: (1.57079632679-1.31695789692j); cmath: (1.57079632679+1.31695789692j)

----------------------------------------------------------------------
Ran 1769 tests in 10.913s
```

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-11-25

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-12-23

The branch dynamic_cpu_detection is supposed to fix this: the problem is that numpy relies on WORDS_BIGENDIAN from pyconfig.h, which is not defined correctly on some platforms.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-12-27

See python bug 4728:

http://bugs.python.org/issue4728

I added a runtime check to detect this atmention: r6198, and will clean up the branch to avoid depending on the buggy python macro.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-03-03

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-03-06

Fixed in r6552
