### ISSUE TITLE
FAIL: test_umath.TestComplexFunctions.test_against_cmath (migrated from Trac #974)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2527]
Original ticket http://projects.scipy.org/numpy/ticket/974
Reported 2008-12-20 by atmention:nilswagner01, assigned to unknown.

python2,6 

```
>>> numpy.__version__
'1.3.0.dev6173'

======================================================================                                                         
FAIL: test_umath.TestComplexFunctions.test_against_cmath                                                                       
----------------------------------------------------------------------                                                         
Traceback (most recent call last):                                                                                             
  File "/home/nwagner/local/lib64/python2.6/site-packages/nose-0.10.4-py2.6.egg/nose/case.py", line 182, in runTest            
    self.test(*self.arg)                                                                                                       
  File "/home/nwagner/local/lib64/python2.6/site-packages/numpy/core/tests/test_umath.py", line 423, in test_against_cmath     
    assert abs(a - b) < atol, "%s %s: %s; cmath: %s"%(fname,p,a,b)                                                             
AssertionError: arcsin 2: (1.57079632679-1.31695789692j); cmath: (1.57079632679+1.31695789692j)      

>>> numpy.show_config()
atlas_threads_info:
    libraries = ['lapack', 'ptf77blas', 'ptcblas', 'atlas']
    library_dirs = ['/home/nwagner/src/ATLAS3.8.2/mybuild/lib']
    language = f77
    include_dirs = ['/home/nwagner/src/ATLAS3.8.2/include']

blas_opt_info:
    libraries = ['ptf77blas', 'ptcblas', 'atlas']
    library_dirs = ['/home/nwagner/src/ATLAS3.8.2/mybuild/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.2\\""')]
    language = c
    include_dirs = ['/home/nwagner/src/ATLAS3.8.2/include']

atlas_blas_threads_info:
    libraries = ['ptf77blas', 'ptcblas', 'atlas']
    library_dirs = ['/home/nwagner/src/ATLAS3.8.2/mybuild/lib']
    language = c
    include_dirs = ['/home/nwagner/src/ATLAS3.8.2/include']

lapack_opt_info:
    libraries = ['lapack', 'ptf77blas', 'ptcblas', 'atlas']
    library_dirs = ['/home/nwagner/src/ATLAS3.8.2/mybuild/lib']
    define_macros = [('ATLAS_INFO', '"\\"3.8.2\\""')]
    language = f77
    include_dirs = ['/home/nwagner/src/ATLAS3.8.2/include']

lapack_mkl_info:
  NOT AVAILABLE

blas_mkl_info:
  NOT AVAILABLE

mkl_info:
  NOT AVAILABLE
```

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2008-12-20

It's a branch cut issue. The behavior of our complex functions is undefined on the branch cuts (varies across platforms), whereas cmath (as of Python 2.6) follows the C99 specification.

So, the tests are wrong. Comparison on points on branch cuts removed in r6175 -> fixed.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-03-09
