### ISSUE TITLE
Formatting unit tests failure on windows + 2.6 (migrated from Trac #975)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2528]
Original ticket http://projects.scipy.org/numpy/ticket/975
Reported 2008-12-23 by atmention:cournape, assigned to unknown.

Harmless, but still annoying:

```
======================================================================
FAIL: Check formatting.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\numpy\core\tests\test_print.py", line 28, in test_complex_types
    assert_equal(str(t(x)), str(complex(x)))
  File "C:\Python26\Lib\site-packages\numpy\testing\utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: '(1e+020+0j)'
 DESIRED: '(1e+20+0j)'

======================================================================
FAIL: Check formatting.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python26\Lib\site-packages\numpy\core\tests\test_print.py", line 16, in test_float_types
    assert_equal(str(t(x)), str(float(x)))
  File "C:\Python26\Lib\site-packages\numpy\testing\utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: '1e+020'
 DESIRED: '1e+20'
```

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-12-27

Should be fixed in r6210: I copied the float formating implementation from python code, so that we are more compatible with it. It fixes all issues on 2.6, as well as some issues on 2.5 (and I guess on 2.4, although I have not tested it).

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2008-12-28

The issue is more complex than first expected. We use PyOS_sprintf for our formatting needs, but the function is not consistent across platforms (the problem is being fixed in python: http://mail.python.org/pipermail/python-bugs-list/2007-December/043559.html).

Maybe the solution is to have our own formatting functions, which does not sound like fun...

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-03-09

Fixed in the float formatting branch
