### ISSUE TITLE
Numpy test failure with Python 2.5.3 (win32) (migrated from Trac #977)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2530]
Original ticket http://projects.scipy.org/numpy/ticket/977
Reported 2008-12-26 by trac user raybaut, assigned to unknown.

Running unit tests for numpy
NumPy version 1.2.1
NumPy is installed in C:\Program Files\pythonxy\python\lib\site-packages\numpy
Python version 2.5.3 (r253:67855, Dec 19 2008, 16:58:30) [MSC v.1310 32 bit (Intel)]
# nose version 0.10.4
## FAIL: test_umath.TestComplexFunctions.test_against_cmath

Traceback (most recent call last):
  File "nose\case.py", line 182, in runTest
    self.test(*self.arg)
  File "C:\Program Files\pythonxy\python\lib\site-packages\numpy\core\tests\test_umath.py", line 268
, in test_against_cmath
    assert abs(a - b) < atol, "%s %s: %s; cmath: %s"%(fname,p,a,b)
AssertionError: arcsinh -2j: (-1.31695789692-1.57079632679j); cmath: (1.31695789692-1.57079632679j)

---

Ran 1592 tests in 11.484s

FAILED (KNOWNFAIL=3, failures=1)
Out[1]: <nose.result.TextTestResult run=1592 errors=0 failures=1>

**Comment by thouis** [comment]
Comment in Trac by trac user raybaut, 2008-12-27

Same result with Python 2.5.4 (it was predictible though...)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-01-12

Duplicate of #974, was fixed in r6175.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-03-02
