### ISSUE TITLE
unit test failures for numpy 1.3.0.dev6294 (migrated from Trac #978)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2531]
Original ticket http://projects.scipy.org/numpy/ticket/978
Reported 2009-01-05 by atmention:chanley, assigned to unknown.

The following unit test failures are received with numpy 1.3.0.dev6294 with Python 2.5.1.  The test system is an Intel Mac running OS X 10.5.6.  However, the errors can be reproduced on RHE 4 and 4 systems as well.

```
[redcedar:~/dev/devCode] chanley% python
Python 2.5.1 (r251:54863, Mar 13 2008, 13:22:51) 
[GCC 4.0.1 (Apple Computer, Inc. build 5367)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy;numpy.test()
Running unit tests for lib.python.numpy
NumPy version 1.3.0.dev6294
NumPy is installed in /Users/chanley/dev/site-packages/lib/python/numpy
Python version 2.5.1 (r251:54863, Mar 13 2008, 13:22:51) [GCC 4.0.1 (Apple Computer, Inc. build 5367)]
nose version 0.10.3
.............................................................................................................................................................................................................................................................F..F..F..FFF..................................................................................................................................................................................................K.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S.......................................................................................................................................................................................................................................................................................................................................................................ctypes is not available on this python: skipping the test (import error was: ctypes is not available.)
.No distutils available, skipping test.
.....
======================================================================
FAIL: Check formatting.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chanley/dev/site-packages/lib/python/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 74, in check_complex_type
    err_msg='Failed str formatting for type %s' % tp)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: Failed str formatting for type <type 'numpy.complex64'>
 ACTUAL: '(1e+10+0j)'
 DESIRED: '1e+10'

======================================================================
FAIL: Check formatting when using print
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chanley/dev/site-packages/lib/python/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 108, in check_float_type_print
    _test_redirected_print(float(x), tp)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 104, in _test_redirected_print
    err_msg='print failed for type%s' % tp)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: print failed for type<type 'numpy.float32'>
 ACTUAL: '10000000000.0\n'
 DESIRED: '1e+10\n'

======================================================================
FAIL: Check formatting when using print
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chanley/dev/site-packages/lib/python/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 115, in check_complex_type_print
    _test_redirected_print(complex(x), tp)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 104, in _test_redirected_print
    err_msg='print failed for type%s' % tp)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: print failed for type<type 'numpy.complex64'>
 ACTUAL: '(10000000000+0j)\n'
 DESIRED: '(1e+10+0j)\n'

======================================================================
FAIL: test_print.test_locale_single
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chanley/dev/site-packages/lib/python/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/decorators.py", line 82, in skipper
    return f(*args, **kwargs)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 164, in test_locale_single
    return _test_locale_independance(np.float32)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 157, in _test_locale_independance
    err_msg='Failed locale test for type %s' % tp)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: Failed locale test for type <type 'numpy.float32'>
 ACTUAL: '1,2'
 DESIRED: '1.2'

======================================================================
FAIL: test_print.test_locale_double
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chanley/dev/site-packages/lib/python/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/decorators.py", line 82, in skipper
    return f(*args, **kwargs)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 169, in test_locale_double
    return _test_locale_independance(np.double)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 157, in _test_locale_independance
    err_msg='Failed locale test for type %s' % tp)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: Failed locale test for type <type 'numpy.float64'>
 ACTUAL: '1,2'
 DESIRED: '1.2'

======================================================================
FAIL: test_print.test_locale_longdouble
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/chanley/dev/site-packages/lib/python/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/decorators.py", line 82, in skipper
    return f(*args, **kwargs)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 174, in test_locale_longdouble
    return _test_locale_independance(np.longdouble)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/core/tests/test_print.py", line 157, in _test_locale_independance
    err_msg='Failed locale test for type %s' % tp)
  File "/Users/chanley/dev/site-packages/lib/python/numpy/testing/utils.py", line 183, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: Failed locale test for type <type 'numpy.float128'>
 ACTUAL: '1,2'
 DESIRED: '1.2'

----------------------------------------------------------------------
Ran 1799 tests in 8.869s

FAILED (KNOWNFAIL=1, SKIP=1, failures=6)
<nose.result.TextTestResult run=1799 errors=0 failures=6>
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:stsci-sienkiew, 2009-01-08: [01-07.21.30.log](http://projects.scipy.org/numpy/attachment/ticket/978/01-07.21.30.log)

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-01-08

Also failing in the same build, but on Solaris:

Items are not equal: Failed str formatting for type <type 'numpy.float32'>
 ACTUAL: 'Inf'
 DESIRED: 'inf'

Items are not equal: Failed str formatting for type <type 'numpy.float64'>
 ACTUAL: 'Infinity'
 DESIRED: 'inf'

Items are not equal: Failed str formatting for type <type 'numpy.float128'>
 ACTUAL: 'Infinity'
 DESIRED: 'inf'

details in attached file 01-07.21.30.log

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-01-09

They are known failures, and were tagged as such in r6304.
