### ISSUE TITLE
problem with locales (migrated from Trac #981)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2534]
Original ticket http://projects.scipy.org/numpy/ticket/981
Reported 2009-01-08 by atmention:chanley, assigned to unknown.

Seen in latest version of numpy svn on multiple platforms.

```
>>> import numpy as np
>>> import locale
>>> locale.format_string("%f",np.double(1.2))
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/stsci/pyssgdev/Python-2.5.1/lib/python2.5/locale.py", line 188, in format_string
   val[key] = format(perc.group(), val[key], grouping)
TypeError: 'numpy.float64' object does not support item assignment
>>>
```

**Comment by thouis** [comment]
Comment in Trac by atmention:rkern, 2009-01-08

The cause of the problem is that {{{locale.format_string()}}} uses {{{operator.isMappingType()}}} (in C: {{{PyMapping_Check}}}) to see if the value is dictlike in order to support the {{{'%(foo)s'}}} kind of format strings. numpy scalars pass this test because they support indexing with {{{scalar[()]}}}.

I don't think we can really fix this one.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-03-02
