### ISSUE TITLE
Problem accessing data attribute of ndarray object created with certain sizes (migrated from Trac #982)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2535]
Original ticket http://projects.scipy.org/numpy/ticket/982
Reported 2009-01-09 by trac user jtaylor2, assigned to unknown.

When creating a ndarray object on a 64 bit machine where the number of bytes of data in the array is described by the following rule:

(size & 0x80000000) != 0 AND (size & 0xFFFFFFFF) != 0xFFFFFFFF

Accessing the data attribute (the data buffer) of the ndarray object results in a ValueError exception.

Note the following examples:

```
thor> python
Python 2.5.1 (r251:54863, Jan 16 2008, 16:16:13)
[GCC 3.4.6 20060404 (Red Hat 3.4.6-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> numpy.__version__
'1.3.0.dev6306'
>>> a=numpy.zeros(0x7FFFFFFF,dtype='b1')
>>> a.data
<read-write buffer for 0xa054a0, size 2147483647, offset 0 at 0x2a99e13e70>
>>> a=numpy.zeros(0x80000000,dtype='b1')
>>> a.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: size must be zero or positive
>>> a=numpy.zeros(0xFFFFFFFE,dtype='b1')
>>> a.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: size must be zero or positive
>>> a=numpy.zeros(0xFFFFFFFF,dtype='b1')
>>> a.data
<read-write buffer for 0xa2e410, size -1, offset 0 at 0x2a99e13e30>
>>> a=numpy.zeros(0x180000000,dtype='b1')
>>> a.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: size must be zero or positive
>>> a=numpy.zeros(0x180000001,dtype='b1')
>>> a.data
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: size must be zero or positive
>>> a=numpy.zeros(0x1FFFFFFFF,dtype='b1')
>>> a.data
<read-write buffer for 0xa2e590, size -1, offset 0 at 0x2a99e13e70>
```

**Comment by thouis** [comment]
Comment in Trac by atmention:chanley, 2009-01-29

This issue has been reported by a number of users of pyfits when trying to create large recarrays on 64bit systems.

**Comment by thouis** [comment]
Comment in Trac by trac user jmiller, 2009-03-05

Fixed in revision 6545 with a change to arrayobject.c

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-24

Closing as it was reported fixed.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31
