### ISSUE TITLE
Cannot build numpy from svn (migrated from Trac #983)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2536]
Original ticket http://projects.scipy.org/numpy/ticket/983
Reported 2009-01-09 by atmention:nilswagner01, assigned to atmention:jarrodmillman.

```
python setup.py install --prefix=$HOME/local
Running from numpy source directory.                                        
Traceback (most recent call last):                                          
  File "setup.py", line 96, in <module>                                     
    setup_package()                                                         
  File "setup.py", line 68, in setup_package                                
    from numpy.distutils.core import setup                                  
  File "/home/nwagner/svn/numpy/numpy/distutils/core.py", line 25, in <module>
    from numpy.distutils.command import config, config_compiler, \            
  File "/home/nwagner/svn/numpy/numpy/distutils/command/build_ext.py", line 16, in <module>
    from numpy.distutils.system_info import combine_paths                                  
  File "/home/nwagner/svn/numpy/numpy/distutils/system_info.py", line 185, in <module>     
    '/opt/local/lib','/sw/lib'], platform_bits)                                            
  File "/home/nwagner/svn/numpy/numpy/distutils/system_info.py", line 170, in libpaths     
    out.extend([p+bits, p])                                                                
TypeError: cannot concatenate 'str' and 'int' objects
```

**Comment by thouis** [comment]
Comment in Trac by atmention:jarrodmillman, 2009-01-09

**Comment by thouis** [comment]
Comment in Trac by atmention:jarrodmillman, 2009-01-09

Fixed in r6314.
