### ISSUE TITLE
numpy.load can't handle gzip file handles (migrated from Trac #995)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2548]
Original ticket http://projects.scipy.org/numpy/ticket/995
Reported 2009-02-03 by trac user MatthewMiller, assigned to unknown.

I'd like to log the state of my program as it progresses. Using the
numpy.save / numpy.load functions on the same filehandle repeatedly works very well for this -- but ends up making a file which very quickly grows to gigabytes. The data compresses well, though, so I thought I'd use Python's built-in gzip module underneath. This works great for saving -- but when it comes time to play back, there's an issue:

```
  >>> import numpy
  >>> import gzip
  >>> f=open("test.gz")
  >>> g=gzip.GzipFile(None,"rb",9,f)
  >>> g
  <gzip open file 'test.gz', mode 'r' at 0xbaad50 0xc0ab90>
  >>> numpy.load(g)
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/lib64/python2.5/site-packages/numpy/lib/io.py", line 133, in load
      fid.seek(-N,1) # back-up
  TypeError: seek() takes exactly 2 arguments (3 given)
```

Turns out you can't rewind gzip file handles in Python. Oops. The offending code is that which distinguishes between npy and npz files. Could there maybe be something added to just trust me that it's an npy?

If I use numpy.lib.format.read_array() directly, there's no problem.

**Comment by thouis** [comment]
Attachment in Trac by atmention:stefanv, 2009-02-21: [995-gzip-seek.patch](http://projects.scipy.org/numpy/attachment/ticket/995/995-gzip-seek.patch)

**Comment by thouis** [comment]
Attachment in Trac by atmention:nilswagner01, 2009-02-22: [ticket_995.py](http://projects.scipy.org/numpy/attachment/ticket/995/ticket_995.py)

**Comment by thouis** [comment]
Comment in Trac by atmention:nilswagner01, 2009-02-22

I have applied your patch against 1.3.0.dev6450.

Before I have applied the patch I get

```
python -i ticket_995.py
Traceback (most recent call last):
  File "ticket_995.py", line 5, in ?
    numpy.load(g)
  File "/usr/lib/python2.4/site-packages/numpy/lib/io.py", line 150, in load
    fid.seek(-N,1) # back-up
TypeError: seek() takes exactly 2 arguments (3 given)
>>> g
<gzip open file 'test.gz', mode 'r' at 0x40fad218 0x40fa2f8c>
```

With the patch

```
python -i ticket_995.py
Traceback (most recent call last):
  File "ticket_995.py", line 5, in ?
    numpy.load(g)
  File "/usr/lib/python2.4/site-packages/numpy/lib/io.py", line 197, in load
    raise IOError, \
IOError: Failed to interpret file <gzip open file 'test.gz', mode 'r' at 0x40fac260 0x40fa214c> as a pickle
```

**Comment by thouis** [comment]
Comment in Trac by atmention:stefanv, 2009-02-22

Please try with the attached test.gz.

**Comment by thouis** [comment]
Comment in Trac by atmention:nilswagner01, 2009-02-22

Works for me. IMHO, the ticket can be closed.

**Comment by thouis** [comment]
Comment in Trac by atmention:stefanv, 2009-02-22

Patch applied in r6454.  Test added in r6456.
