### ISSUE TITLE
[proposal][patch] bool(array) should "do the right thing" in the unambiguous cases. (migrated from Trac #997)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2550]
Original ticket http://projects.scipy.org/numpy/ticket/997
Reported 2009-02-04 by trac user alsuren, assigned to unknown.

After stumbling across http://mail.python.org/pipermail/python-list/2008-December/519124.html

I thought I might as well make a concrete proposal. The test case proposed in the email is:

> > > > import numpy
> > > > y = numpy.zeros((3,))
> > > > y
> > > > array([ 0.,  0.,  0.])
> > > > bool(y==y)
> > > > Traceback (most recent call last):
> > > >   File "<stdin>", line 1, in <module>
> > > > ValueError: The truth value of an array with more than one element is
> > > > ambiguous. Use a.any() or a.all()
> > > > ll1 = [y,1]
> > > > y in ll1
> > > > True
> > > > ll2 = [1,y]
> > > > y in ll2
> > > > Traceback (most recent call last):
> > > >   File "<stdin>", line 1, in <module>
> > > > ValueError: The truth value of an array with more than one element is
> > > > ambiguous. Use a.any() or a.all()

May I suggest that:
 bool(y==y) -> True
 bool(zeros((5,))==ones((5,))) -> False
are not ambiguous: in each case, any(array)==all(array), and this value should simply be returned.

I'll attach a patch against 1.1.1 which shows the general idea, but which I've not tested.

**Comment by thouis** [comment]
Attachment in Trac by trac user alsuren, 2009-02-04: [unambiguous.diff](http://projects.scipy.org/numpy/attachment/ticket/997/unambiguous.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:rkern, 2009-02-04

I'm -1 on this. I think it will just add to the confusion. The comparison will still raise errors in the ambiguous cases, so code that is not explicit will still fail with some inputs. However, the few cases that do work will trick people into thinking that comparison always work.

People often just try out a quick example in the interpreter to see if it works. However, they try just _one_ example, and not all of the variations. We saw exactly this behavior with Numeric, and a number people had incorrect code that was not caught for a long time.

**Comment by thouis** [comment]
Comment in Trac by atmention:rkern, 2009-02-07

I'm going to close this as wontfix. If you want to discuss it further, please join us on numpy-discussion.

  http://www.scipy.org/Mailing_Lists
