### ISSUE TITLE
NumPy does not easy install as a dependency (migrated from Trac #999)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2552]
Original ticket http://projects.scipy.org/numpy/ticket/999
Reported 2009-02-05 by trac user mjwakefield, assigned to atmention:dmcooke.

When NumPy is listed as a dependency for another package automatic installation of NumPy fails.
easy_install numpy works successfully

Best match: numpy 1.2.1
Downloading http://downloads.sourceforge.net/numpy/numpy-1.2.1.tar.gz?modtime=1225265011&big_mirror=0
Processing numpy-1.2.1.tar.gz
Running numpy-1.2.1/setup.py -q bdist_egg --dist-dir /var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/egg-dist-tmp-H5FSHT
Running from numpy source directory.
Warning: distutils distribution has been initialized, it may be too late to add a subpackage command
Warning: distutils distribution has been initialized, it may be too late to add a subpackage fcompiler
non-existing path in '/private/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils': 'site.cfg'
Warning: distutils distribution has been initialized, it may be too late to add a subpackage distutils
Warning: distutils distribution has been initialized, it may be too late to add a subpackage testing
/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/misc_util.py:1343: DeprecationWarning: os.popen4 is deprecated.  Use the subprocess module.
  sin, sout = os.popen4('svnversion')
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/Current/bin/easy_install", line 8, in <module>
    load_entry_point('setuptools==0.6c9', 'console_scripts', 'easy_install')()
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 1671, in main
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 1659, in with_ei_usage
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 1675, in <lambda>
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 211, in run
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 427, in easy_install
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 478, in install_item
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 519, in process_distribution
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py", line 522, in resolve
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py", line 758, in best_match
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py", line 770, in obtain
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 446, in easy_install
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 476, in install_item
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 655, in install_eggs
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 930, in build_and_install
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/command/easy_install.py", line 919, in run_setup
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/sandbox.py", line 27, in run_setup
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/sandbox.py", line 63, in run
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/setuptools/sandbox.py", line 29, in <lambda>
  File "setup.py", line 96, in <module>

  File "setup.py", line 89, in setup_package

  File "/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/core.py", line 150, in setup
  File "setup.py", line 56, in configuration

  File "/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/misc_util.py", line 851, in add_subpackage
  File "/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/misc_util.py", line 834, in get_subpackage
  File "/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/misc_util.py", line 781, in _get_configuration_from_setup_py
  File "numpy/setup.py", line 8, in configuration
    import os
  File "/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/misc_util.py", line 851, in add_subpackage
  File "/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/misc_util.py", line 834, in get_subpackage
  File "/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/misc_util.py", line 781, in _get_configuration_from_setup_py
  File "/private/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/f2py/setup.py", line 81, in configuration

  File "/var/folders/Kg/KgodBp6HFYaMgVoWCkGln+++mNU/-Tmp-/easy_install-p3img4/numpy-1.2.1/numpy/distutils/misc_util.py", line 1239, in add_scripts
AttributeError: 'NoneType' object has no attribute 'extend'

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-06-02

Duplicate of #860.

**Comment by thouis** [comment]
Comment in Trac by unknown, 2010-09-04

Milestone 1.2.2 deleted
