### ISSUE TITLE
dype comparison with other types raise a TypeError (migrated from Trac #1001)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2554]
Original ticket http://projects.scipy.org/numpy/ticket/1001
Reported 2009-02-06 by trac user ashleywalsh, assigned to unknown.

If you compare a dtype with another object for equality a TypeError is raised if the second object cannot be converted to a dtype:
    >>> import numpy
    >>> numpy.dtype(float) == 'float'
    True
    >>> numpy.dtype(float) == 'i'
    False
    >>> numpy.dtype(float) == object()
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: data type not understood
    >>> numpy.dtype(float) == 'x'
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: data type not understood

In my case this caused epydoc to crash because it attempted to compare a dtype that was class attribute with (I think) an object was an attribute of the same name on a super-class.

**Comment by thouis** [comment]
Comment in Trac by trac user ashleywalsh, 2009-02-06

"was a class attribute" -- and I hassle people in our office who don't use the "preview" on our internal Tracs...

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-10-10

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-24

This is because dtype comparison coerces the other value to a dtype. This behavior actually violates the requirements of the hashing protocol, and should be changed at some point to allow dtypes to be used in dictionaries without the potential for bad behavior.
