### ISSUE TITLE
dtype attributes change after an arithmetic operation involving a scalar (migrated from Trac #1012)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2565]
Original ticket http://projects.scipy.org/numpy/ticket/1012
Reported 2009-02-19 by trac user hana, assigned to unknown.

If you add an integer scalar to an integer array, the resulting array changes the attributes 'num' and 'char' of dtype:

> > > from numpy import array
> > > a = array([1,2])
> > > b = 0+a
> > > a.dtype.num
> > > 7
> > > b.dtype.num
> > > 5
> > > a.dtype.char
> > > 'l'
> > > b.dtype.char
> > > 'i'

This has an effect on scipy.ndimage functions:

> > > from scipy import ndimage
> > > ndimage.sum(a)
> > > 3.0
> > > ndimage.sum(b)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Frameworks/Python.framework/Versions/2.5/lib/python2.5/site-packages/scipy/ndimage/measurements.py", line 126, in sum
> > >     return _nd_image.statistics(input, labels, index, 0)
> > > RuntimeError: data type not supported

Note that if you do b=a+0 (instead of b=0+a), it works. 

We are running python 2.5, numpy 1.2.1, scipy 0.7.0

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2009-02-19

I expect the actual data type remains the same, so you probably want to use some other way of tracking the type. The 'l' type seems to be redundant on most platforms as it is either 32 or 64 bits and matches up with either int or long long. Maybe we should just remove it ;)

The code that determines these things is a bit of a tangle and the easiest short term solution is not to use the num or char data type.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-03-09

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-05-25

I think ndimage should be fixed to handle both cases since I think the actual precision of the types in this case are identical. That said, I think the type promotion code should be made symmetric in the arguments so that the common type of a,b is the same as the common type of b,a. This needs a bit of work, however.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-24

This was fixed in the scipy 0.9.0 release.
