### ISSUE TITLE
test fails: Test find_duplicates (migrated from Trac #1039)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2592]
Original ticket http://projects.scipy.org/numpy/ticket/1039
Reported 2009-03-05 by atmention:stsci-sienkiew, assigned to unknown.

numpy 1.3.0.dev6545
python 2.5.1
nose 0.10.4

This test fails on

Solaris 8, sparc, 32 bit

No failure reported on:

Mac OSX 10.4 (tiger), x86 or PPC

Red Hat Enterprise Linux 3 or 4, x86 or x86_64
# 
## FAIL: Test find_duplicates

Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/decorators.py", line 169, in knownfailer
    return f(_args, *_kwargs)
  File "/usr/ra/pyssg/2.5.1/numpy/lib/tests/test_recfunctions.py", line 152, in test_find_duplicates
    assert_equal(test[-1], control)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 121, in assert_equal
    return assert_array_equal(actual, desired, err_msg)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 193, in assert_array_equal
    header='Arrays are not equal')
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 186, in assert_array_compare
    verbose=verbose, header=header)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 295, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([2, 0])
 y: array([0, 2])

---

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-03-30

```
1.3.0 rc 1 still has this problem on Solaris.


======================================================================
FAIL: Test find_duplicates
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ra/pyssg/2.5.1/numpy/lib/tests/test_recfunctions.py", line 163, in test_find_duplicates
    assert_equal(test[0], a[control])
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 121, in assert_equal
    return assert_array_equal(actual, desired, err_msg)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 193, in assert_array_equal
    header='Arrays are not equal')
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 186, in assert_array_compare
    verbose=verbose, header=header)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 395, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 50.0%)
 x: array([(1, (2.0, 'B')), (2, (2.0, 'B')), (2, (2.0, 'B')), (1, (2.0, 'B'))],
      dtype=[('A', '>i4'), ('B', [('BA', '>f8'), ('BB', '|S1')])])
 y: array([(2, (2.0, 'B')), (1, (2.0, 'B')), (2, (2.0, 'B')), (1, (2.0, 'B'))],
      dtype=[('A', '>i4'), ('B', [('BA', '>f8'), ('BB', '|S1')])])

----------------------------------------------------------------------



The software I am using:

NumPy version 1.3.0rc1
Python version 2.5.1 (r251:54863, Jun  4 2008, 15:48:19) [C]
nose version 0.10.4


I think this identifies the compilers it was built with:

customize SunFCompiler
Found executable /opt/SUNWspro-6u2/bin/f90
Could not locate executable echo ranlib
customize SunFCompiler
customize SunFCompiler using config
C compiler: cc -DNDEBUG -O -xcode=pic32



It passes in Python 2.5.1 on these machines:
x86 macintosh, 32 bit
Red Hat Enterprise 4 Linux, x86, 32 bit
RHE 3, x86, 32 bit
RHE 4, x86, 64 bit
PowerPC mac, 32 bit  (Yes, even the PPC mac.)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-03-30

Seems like a small bug in the tests. Should be fixed now in trunk, r6827; confirm?

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-03-31

The test passed in 1.4.0.dev6827, on all the same machines mentioned above.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2009-03-31

Reported fixed by r6827.
