### ISSUE TITLE
64-bit arrayobject bugs (migrated from Trac #1040)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2593]
Original ticket http://projects.scipy.org/numpy/ticket/1040
Reported 2009-03-05 by trac user jmiller, assigned to atmention:cournape.

This ticket and patch addresses a number of 64-bit bugs in arrayobject.c:
# PyArray_ToString

> > > a.tostring()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > SystemError: Negative size passed to PyString_FromStringAndSize
# PyArray_CopyObject ?

> > > a = numpy.ones(0x80000000, dtype='c')
> > > a[:] = "1"*0x80000000
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > SystemError: error return without exception set
> > > 
> > > a.astype('b1')
> > > Segmentation fault (core dumped)

The patch also fixes a number of error string formatting bugs caused
by use of %d for a Py_ssize_t sized value.

**Comment by thouis** [comment]
Attachment in Trac by trac user jmiller, 2009-03-05: [patch_arrayobject_64.txt](http://projects.scipy.org/numpy/attachment/ticket/1040/patch_arrayobject_64.txt)

**Comment by thouis** [comment]
Comment in Trac by trac user jmiller, 2009-03-05

Some of the setup code for the first example got lopped off:

> > > a = numpy.ones(0x80000000, dtype='i1')

Later on in the CopyObject example there should be a line break before the a[:]

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2009-03-06

The patch looks good to me at first look. Could you put together some simple tests?

David, if you don't get to this I'll apply it this weekend.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2009-03-08

Applied in r6572. Thanks.
