### ISSUE TITLE
AttributeError: keys (migrated from Trac #1052)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2605]
Original ticket http://projects.scipy.org/numpy/ticket/1052
Reported 2009-03-13 by trac user Jack, assigned to atmention:pierregm.

I have installed Gnuradio-3.1.3 on RedHat -4.The installation of gnuradio was successful.Even I have got USRP connected and have loaded the firmware.
     But when I try to run the given examples of "gr-utils" for example usrp_fft.py i get the following error:-
[rootatmention:localhost python]# ./usrp_fft.py
Traceback (most recent call last):
  File "./usrp_fft.py", line 23, in ?
    from gnuradio import gr, gru
  File "/usr/lib/python2.3/site-packages/gnuradio/gru/**init**.py", line 37, in ?
    exec "from gnuradio.gruimpl.%s import *" % (f,)
  File "<string>", line 1, in ?
  File "/usr/lib/python2.3/site-packages/gnuradio/gruimpl/gnuplot_freqz.py", line 28, in ?
    import numpy
  File "/usr/lib/python2.3/site-packages/numpy/**init**.py", line 107, in ?
    import ma
  File "/usr/lib/python2.3/site-packages/numpy/ma/**init**.py", line 14, in ?
    import core
  File "/usr/lib/python2.3/site-packages/numpy/ma/core.py", line 114, in ?
    max_filler.update([(k,-numpy.inf) for k in [numpy.float32, numpy.float64]])
AttributeError: keys

What is the reason for such type of error.Can someone guide me through this problem.

Thanks.

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2009-03-13

Hi,
Are you able to run the numpy test suite by itself ?
python -c "import numpy; numpy.test()"
Let us know the result of this test first.

FYI, max_filler is numpy.core.numerictypes._minvals, which is a dictionary. The fact that is doesn't have keys hints that something went wrong in the installation.

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2009-06-29

No news ? Set as 'invalid'...
