### ISSUE TITLE
loadtxt fails if the last column contains empty value (migrated from Trac #1071)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2624]
Original ticket http://projects.scipy.org/numpy/ticket/1071
Reported 2009-03-30 by trac user Electrion, assigned to unknown.

Hello,

I recently noticed that loadtxt() fails when I try to load a file that contains no value on the last column when it is TAB delimited.

For example :

```
s = StringIO('#X\tY\tC\n1.\t1.\t1.\n2.\t2.\t\n')
loadtxt(s)
```

will fail with Exception:

```
ValueError: setting an array element with a sequence.
```

The use of dtypes or converters (like {2: lambda s: float(s or 'Nan')} ) doesn't help.

After investigation, I noticed that the loadtxt function strip all lines before splitting and then remove the '\t\n'.

If think the 'split_line' subfunction in numpy.io.loadtxt

```
    def split_line(line):
        """Chop off comments, strip, and split at delimiter."""
        line = line.split(comments)[0].strip()
[...]
```

should be replaced by
        def split_line(line):
            """Chop off comments, strip, and split at delimiter."""
            line = line.split(comments)[0].strip('\r\n')
    [...]

to remove any new line character but not the delimiter.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-24

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-03-26

Note: as default delimiter tab is treated as 'any whitespace', which includes any number of blanks or tabs. 
These are therefore treated differently from delimiters like ',' or '&'. I'd reckon there are too many people 
actually relying on this behaviour to silently change it (e.g. I know plenty of tables with columns separated 
by either one or  several tabs depending on the length of the previous entry). 

But tab is apparently also treated differently if explicitly specified with "delimiter='\t'" -  
and in that case using a converter à la {{{ {2: lambda s: float(s or 'Nan')} }}} is working for  
fields in the middle of the line, but not at the end - this is the case that should be fixed. 
Patch for 1.6.0beta1:

```
diff --git a/numpy/lib/npyio.py b/numpy/lib/npyio.py
index 9fbacaa..a1b58aa 100644
--- a/numpy/lib/npyio.py
+++ b/numpy/lib/npyio.py
atmention:atmention: -724,7 +728,7 atmention:atmention: def loadtxt(fname, dtype=float, comments='#', delimiter=None,

     def split_line(line):
         """Chop off comments, strip, and split at delimiter."""
-        line = asbytes(line).split(comments)[0].strip()
+        line = asbytes(line).split(comments)[0].strip(asbytes(' \r\n'))
         if line:
             return line.split(delimiter)
         else:
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:dhomeier, 2011-03-26: [1071.patch](http://projects.scipy.org/numpy/attachment/ticket/1071/1071.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:bsouthey, 2011-03-30

This ticket is invalid because the loadtxt docstring clearly states:
    Each row in the text file must have the same number of values.
Here ''values'' means having the same type throughout the input. That is you can not mix integers, floats and strings:

{{

> > > c = StringIO("0 1\n2 3")
> > > np.loadtxt(c)
> > > array([[ 0.,  1.],
> > >        [ 2.,  3.]])
> > > d = StringIO("0 '1'\n2 '3'")
> > > np.loadtxt(d)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/lib64/python2.7/site-packages/numpy/lib/npyio.py", line 783, in loadtxt
> > >     items = [conv(val) for (conv, val) in zip(converters, vals)]
> > > ValueError: could not convert string to float: '1'

}}

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-03-30

I am afraid I don't understand how this pertains to the ticket. The example above is not affected by the proposed patch; but the missing value/mixed data types issue can and could always be handled but structured arrays and or converters:

```
cnv = {1: lambda s: s.strip("\'\"")}
dt = np.dtype([('x', float), ('name', 'S4')])
>>>np.loadtxt(StringIO("0 '1'\n2 '3'"), converters=cnv)
array([[ 0.,  1.],
       [ 2.,  3.]])
>>> np.loadtxt(StringIO("0 '1'\n2 '3'"), dtype=dt)
array([(0.0, "'1'"), (2.0, "'3'")], 
      dtype=[('x', '<f8'), ('name', '|S4')])
>>> np.loadtxt(StringIO("0 '1'\n2 '3'"), converters=cnv, dtype=dt)
array([(0.0, '1'), (2.0, '3')], 
      dtype=[('x', '<f8'), ('name', '|S4')])
```

which is also following the documented use of converters.

The issue addressed here is rather that 
    cnv = {1: lambda s: np.float(s.strip() or 'Nan')}
    >>> np.loadtxt(StringIO("0 & 1\n2 & "), delimiter='&', converters=cnv)
    array([[  0.,   1.],
           [  2.,  nan]])
worked, 
and 
    >>>np.loadtxt(StringIO("0 \t1.5\t1\n2 \t \t 4 "), delimiter='\t', converters=cnv)
     Out[1102]: 
    array([[  0.,   1.,   1.5],
           [  2.,  nan,   4. ]])
also worked, but 
    >>>np.loadtxt(StringIO("0 \t1\n2 \t "), delimiter='\t', converters=cnv)

```
ValueError                                Traceback (most recent call last)

/sw/lib/python2.7/site-packages/numpy/lib/npyio.pyc in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack)
    731             X = np.array(X, dtype=dtype)
    732     else:
--> 733         X = np.array(X, dtype)
    734 
    735     X = np.squeeze(X)

ValueError: setting an array element with a sequence.
```

did not. And I don't see a valid reason why it shouldn't, either (but I've discussed this above).

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-03-31

There is another instance where the present code raises an error, not directly related to missing values/converters. 
Consider this
    >>> dt = np.dtype([('x', float), ('label', 'S4')])
    >>> np.loadtxt(StringIO("0\tany\n2\tname"), delimiter='\t', dtype=dt)
    array([(0.0, 'any'), (2.0, 'name')], 
          dtype=[('x', '<f8'), ('label', '|S4')])
works, and this as well
    >>> np.loadtxt(StringIO("0,any\n2,  "), delimiter=',', dtype=dt)
    array([(0.0, 'any'), (2.0, '')], 
          dtype=[('x', '<f8'), ('label', '|S4')])
(almost, though the whitespace is stripped), while 
    np.loadtxt(StringIO("0\tany\n2\t "), delimiter='\t', dtype=dt)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    /sw/lib/python2.7/site-packages/numpy/lib/npyio.pyc in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack)
        729         except TypeError:
        730             # In the case we have an object dtype

```
--> 731             X = np.array(X, dtype=dtype)
    732     else:
    733         X = np.array(X, dtype)

TypeError: expected a readable buffer object
```

does not...
If one wants to also preserve whitespace in string-type records, the patch should use {{{.strip(asbytes('\r\n'))}}} rather than {{{.strip(asbytes(' \r\n'))}}} again, but this causes test_io: test_dtype_with_object(self) to fail, which seems to rely on stripping the whitespace.

**Comment by thouis** [comment]
Comment in Trac by atmention:bsouthey, 2011-03-31

Replying to [comment:4 derek]:

> I am afraid I don't understand how this pertains to the ticket.
> I want to keep a distinction between loadtxt and genfromtxt. Specifically genfromtxt was added in 2009 especially to address many of the limitations of loadtxt (added in 2007). So we need to avoid adding new features/abilities to loadtxt that duplicate features already present in genfromtxt. 

The ticket says 'empty value' which means 'missing data'. My response is that loadtxt must fail in such cases because the loadtxt docstring clearly states that in 3 different, yet critical places, that missing values are not handled:
Each row in the text file must have the same number of values.
genfromtxt : Load data with missing values handled as specified.
This function aims to be a fast reader for simply formatted files.  The genfromtxt function provides more sophisticated handling of, e.g., lines with missing values.

Really the ticket and your last example arise from the ''misused'' of loadtxt features (i.e. converters) to handle missing data. But since loadtxt is not meant to handle missing values, the ticket and your example is invalid. If missing values were allowed then sure there is a problem.

The attached patch would still be incorrect because it should not include the space in the strip. However I am not sure if similar cases will be uncovered (like more than one delimiter in certain lines) or that really the split_line function should be changed so it first splits valid lines on the delimiter.

**Comment by thouis** [comment]
Comment in Trac by atmention:bsouthey, 2011-03-31

Replying to [comment:5 derek]:
If I just use 'line = line.split(comments)[0].strip('\r\n')' in version 2.0.0.dev-7134a93 then this example now works for me.
    >>> np.loadtxt(StringIO("0 \t1\n2 \t "), delimiter='\t', converters=cnv)
    array([[  0.,   1.],
           [  2.,  nan]])

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-03-31

Replying to [comment:7 bsouthey]:

> Replying to [comment:5 derek]:
> If I just use 'line = line.split(comments)[0].strip('\r\n')' in version 2.0.0.dev-7134a93 then this example now works for me.
> Not converting the string with {{{asbytes('\r\n')}}}  raises an error for me with Python3, and without the blank it fails this test:
>     ERROR: Test using an explicit dtype with an object
>     ----------------------------------------------------------------------
>     Traceback (most recent call last):
>       File "/sw/lib/python2.6/site-packages/numpy/lib/tests/test_io.py", line 422, in test_dtype_with_object
>         converters=converters)
>       File "/sw/lib/python2.6/site-packages/numpy/lib/npyio.py", line 784, in loadtxt
>         items = [conv(val) for (conv, val) in zip(converters, vals)]
>       File "/sw/lib/python2.6/site-packages/numpy/lib/npyio.py", line 569, in <lambda>
>         return lambda x: int(float(x))
>     ValueError: empty string for float()
> because the test passes two blank lines as input. It is not explicitly documented that loadtxt silently skips blank lines, and it could raise other issues because empty lines have been proposed to delimit different data blocks in #1107. 
> But if we want to preserve this functionality, the better fix I now realise is 
>     atmention:atmention: -724,8 +728,8 atmention:atmention: def loadtxt(fname, dtype=float, comments='#', delimiter=None,

```
     def split_line(line):
         """Chop off comments, strip, and split at delimiter."""
-        line = asbytes(line).split(comments)[0].strip()
+        line = asbytes(line).split(comments)[0].strip(asbytes('\r\n'))
+        if line.strip():
             return line.split(delimiter)
         else:
             return []
```

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-03-31

Replying to [comment:8 derek]:

> But if we want to preserve this functionality, the better fix I now realise is 
> Umm, using {{{line.strip()}}} would remove tab-delimited lines with all blanks again, producing 
>     >>> dt = np.dtype([('label', 'S4'), ('comment', 'S4')])
>     >>> np.loadtxt(StringIO("aa\tbb\n \t \ncc\t"), delimiter='\t', dtype=dt)
>     array([('aa', 'bb'), ('cc', '')], 
>           dtype=[('label', '|S4'), ('comment', '|S4')])
> as compared to 
>     >>> np.loadtxt(StringIO("aa,bb\n , \ncc,"), delimiter=',', dtype=dt)
>     array([('aa', 'bb'), (' ', ' '), ('cc', '')], 
>           dtype=[('label', '|S4'), ('comment', '|S4')])
> so I would really rather propose for the patch
>     +        if line.strip(' '):

**Comment by thouis** [comment]
Comment in Trac by atmention:bsouthey, 2011-04-01

I forgot about Python3! So asbytes('\r\n') works for me.

This is a '''great''' example that does not involve missing values because whitespace can be a valid entry in a string. Specifically that any non-delimiter character has to be treated as a valid value.

Also, as you previously indicated, the numpy io test 'test_dtype_with_object' is incorrect. The test relies on the ''unseen'' end of line characters in triple-quotes of the data variable as can be seen by printing repr(data):

```
'\n        1; 2001-01-01\n        2; 2002-01-31\n        '
```

That means data variable really should be defined as (keeping the indents):
            data = """1; 2001-01-01
            2; 2002-01-31 """
            #data = """1;2001-01-01\n2;2002-01-31""" # more explicitly

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-04-03

So where are we now? Is there a consensus? Should the test with blank lines be fixed.

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-04-03

I think there is (at least on my part ;-) - so I'd leave the {{{line.strip()}}} part out and fix the test; this means 
**blank** lines (as opposed to empty lines) are no longer silently skipped.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-04-03

Could you update the patch in that case so it's complete, with tests, and has a comment with what is covered and for what one should use genfromtxt?

I would like to get this in today.

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-04-04

I've put the changes to 'test_dtype_with_object' in and added a test for blank fields in a structured array. Do you think an extra test using converters for empty fields is required, if we want to discourage from using this? I've just added a reference to {{{genfromtxt}}} to the {{{converters}}} documentation - not sure what more there is to be discussed.

**Comment by thouis** [comment]
Attachment in Trac by atmention:dhomeier, 2011-04-04: [1071+doc.patch](http://projects.scipy.org/numpy/attachment/ticket/1071/1071+doc.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-04-04

Applied in ce0019c3c0ce3f5afe6eaf6326cd13093d0644e2, thanks to all.
