### ISSUE TITLE
can't import numpy on Vista x64 system (migrated from Trac #1084)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2637]
Original ticket http://projects.scipy.org/numpy/ticket/1084
Reported 2009-04-14 by trac user ntv1534, assigned to unknown.

I recently upgraded my Python to version 2.6, and installed numpy via the sourceforge installer on my Windows Vista x64 laptop. I got the following results:

SyntaxError: invalid syntax

> > > import numpy
> > > D:\Python\lib\site-packages\numpy\core__init__.py:5: Warning: Windows 64 bits s
> > > upport is experimental, and only available for
> > > testing. You are advised not to use it for production.

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
  import multiarray
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\lib\site-packages\numpy__init__.py", line 130, in <module>
    import add_newdocs
  File "D:\Python\lib\site-packages\numpy\add_newdocs.py", line 9, in <module>
    from lib import add_newdoc
  File "D:\Python\lib\site-packages\numpy\lib__init__.py", line 13, in <module>

```
from polynomial import *
```

  File "D:\Python\lib\site-packages\numpy\lib\polynomial.py", line 18, in <modul
e>
    from numpy.linalg import eigvals, lstsq
  File "D:\Python\lib\site-packages\numpy\linalg__init__.py", line 47, in <modu
le>
    from linalg import *
  File "D:\Python\lib\site-packages\numpy\linalg\linalg.py", line 22, in <module

> ```
> from numpy.linalg import lapack_lite
> ```
> 
> ImportError: DLL load failed: The specified module could not be found.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-06-01

Most likely linked to #1068

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-06-27
