### ISSUE TITLE
polydiv should be duck-typing safe (migrated from Trac #1097)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2650]
Original ticket http://projects.scipy.org/numpy/ticket/1097
Reported 2009-04-28 by atmention:pv, assigned to unknown.

polydiv incorrectly casts objects to polynomials:
    >>> import numpy as np
    >>> from sympy.mpmath import mpf
    >>> p = np.poly1d([mpf('1')])
    >>> p
    poly1d([1.0], dtype=object)
    >>> p / mpf('2.0')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File ".../numpy/lib/polynomial.py", line 1007, in **div**
        return polydiv(self, other)
      File ".../numpy/lib/polynomial.py", line 747, in polydiv
        while NX.allclose(r[0], 0, rtol=1e-14) and (r.shape[-1] > 1):
      File ".../numpy/core/numeric.py", line 1588, in allclose
        xinf = isinf(x)
    TypeError: function not supported for these types, and can't coerce safely to supported types
I think it should first cast both its arguments first to ndarrays and treat 0-d arrays as scalars.

Similar things should be checked also in the other polynomial arithmetic operations.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2009-11-15

Is this better?

```
In [6]: from numpy.polynomial import Polynomial

In [7]: from sympy.mpmath import mpf

In [8]: p = Polynomial([mpf('1')])

In [9]: p/mpf('2.0')
Out[9]: Polynomial([0.5], dtype=object, [-1, 1], dtype=object)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-03-24

These problems aren't easy to fix for poly1d. New applications should use the polynomial.Polynomial class.
