### ISSUE TITLE
FAIL: Test bug in reduceat with structured arrays copied for speed. (migrated from Trac #1108)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2661]
Original ticket http://projects.scipy.org/numpy/ticket/1108
Reported 2009-05-13 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
FAIL: Test bug in reduceat with structured arrays copied for speed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/Python-2.5.1/lib/python2.5/site-packages/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/core/tests/test_umath.py", line 664, in test_reduceat
    assert np.all(h1 == h2)
AssertionError

----------------------------------------------------------------------
```

Affects rev 6976 through 6983 (latest I tried), on 64 bit Red Hat Enterprise Linux 4 and 32 bit PowerPC Macintosh.  Does not affect 32 bit Solaris, 32 bit x86 Mac, 32 bit RHEL 3 or 4.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-05-17

Strangely enough, in the SPARC buildbots, this error appears only starting from r6994. I wonder what's going on...

**Comment by thouis** [comment]
Comment in Trac by atmention:teoliphant, 2009-05-19

I changed the test to stop testing for equality on floating point arrays.  I'm not sure if this is the problem being seen, but it's the wrong approach anyway.   It's worth checking to see if this fixes the reported problems.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-05-19

Doesn't fix it:

http://buildbot.scipy.org/builders/Linux_SPARC_64_Debian_gcc4/builds/507/steps/shell_2/logs/stdio

```
FAIL: Test bug in reduceat with structured arrays copied for speed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".../numpy/core/tests/test_umath.py", line 664, in test_reduceat
    assert_array_almost_equal(h1, h2)
AssertionError: 
Arrays are not almost equal

(mismatch 100.0%)
 x: array([  700.93884277,   800.93884277,  1000.93884277,  7500.93896484], dtype=float32)
 y: array([  700.,   800.,  1000.,  7500.], dtype=float32)
```

Rounding error is quite large -- I wonder if it's even consistent with single precision.

The other SPARC buildslave does pass the test, however. I think the only difference between the two is that the failing one uses gcc 4...

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-05-19

In case it helps, here is some stuff about my compilers:

In numpy 1.4.0.dev7001:

This test passes with the Sun compiler building 32 bit binaries:

grail> cc -V
cc: Sun WorkShop 6 update 2 C 5.3 Patch 111679-14 2004/02/20

On the macintosh:

fail: powerpc-apple-darwin8-gcc-4.0.1 (GCC) 4.0.1 (Apple Computer, Inc. build 5250)
pass: i686-apple-darwin8-gcc-4.0.1 (GCC) 4.0.1 (Apple Computer, Inc. build 5367)

On red hat enterprise 4 x86_64 it also fails:
gcc (GCC) 3.4.6 20060404 (Red Hat 3.4.6-10)

but it passes on 32 bit red hat enterprise 4:
gcc (GCC) 3.4.6 20060404 (Red Hat 3.4.6-10)

(i.e. exactly the same gcc version string on both RHE4 machines.)

None of my machines report the same detail that you have.  It just shows "AssertionError" as in the original report.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-05-19

Replying to [comment:4 sienkiew]:

> None of my machines report the same detail that you have.  It just shows "AssertionError" as in the original report.

Just for clarification: Do you mean it shows `assert np.all(h1 == h2)   AssertionError` instead of the `assert_array_almost_equal` line? If so, then this might mean that for some reason you are not running the tests for a not up-to-date version of Numpy?

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-05-19

I have rev 7001,  but the latest rev in the repository is 7002.  I'll run 7002 and report what happens.

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-05-19

This is certainly a clue:

Linux, 64 bit:

```
NUMPY VERSION:
1.4.0.dev7002
...
======================================================================
FAIL: Test bug in reduceat with structured arrays copied for speed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/Python-2.5.1/lib/python2.5/site-packages/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/core/tests/test_umath.py", line 664, in test_reduceat
    assert_array_almost_equal(h1, h2)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 537, in assert_array_almost_equal
    header='Arrays are not almost equal')
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 395, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal

(mismatch 100.0%)
 x: array([  4.61621844e+24,   4.61621844e+24,   4.61621844e+24,
         4.61621844e+24], dtype=float32)
 y: array([  700.,   800.,  1000.,  7500.], dtype=float32)

----------------------------------------------------------------------
```

ppc mac:

```
======================================================================
FAIL: Test bug in reduceat with structured arrays copied for speed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.1/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/core/tests/test_umath.py", line 664, in test_reduceat
    assert_array_almost_equal(h1, h2)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 537, in assert_array_almost_equal
    header='Arrays are not almost equal')
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 395, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal

(mismatch 100.0%)
 x: array([  2.82687706e+23,   2.82687706e+23,   2.82687706e+23,
         2.82687706e+23], dtype=float32)
 y: array([  700.,   800.,  1000.,  7500.], dtype=float32)

----------------------------------------------------------------------
```

Notice that the values in the x array are all the same, but are apparently unrelated to the values in the y array.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2009-05-23

Got this again on Fedora 9 32 bit linux:

```
Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/lib/python2.5/site-packages/numpy/core/tests/test_umath.py", line 664, in test_reduceat
    assert_array_almost_equal(h1, h2)
  File "/usr/lib/python2.5/site-packages/numpy/testing/utils.py", line 537, in assert_array_almost_equal
    header='Arrays are not almost equal')
  File "/usr/lib/python2.5/site-packages/numpy/testing/utils.py", line 395, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal

(mismatch 100.0%)
 x: array([  1.37766126e+11,   1.37766126e+11,   1.37766126e+11,
         1.37766126e+11], dtype=float32)
 y: array([  700.,   800.,  1000.,  7500.], dtype=float32)
```

It went away on a second try.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-05-23

That it's not deterministic may signal a reference counting or some similar failure: freeing some memory first, and then addressing its data.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-06-02

Valgrind shows that something is wrong when running test_umath.py:test_reduceat:
    ==20907== Conditional jump or move depends on uninitialised value(s)
    ==20907==    by 0x5D57476: array_any (methods.c:1727)
    ==20907== 
    ==20907== Conditional jump or move depends on uninitialised value(s)
    ==20907==    by 0x5D57476: array_any (methods.c:1727)
    ==20907== 
    ==20907== Conditional jump or move depends on uninitialised value(s)
    ==20907==    by 0x5D35974: array_absolute (number.c:214)
    ==20907== 
    ==20907== Conditional jump or move depends on uninitialised value(s)
    ==20907==    by 0x5D456F9: PyArray_ToList (convert.c:46)
None of the above originates from ReduceAt, but instead they come from the `assert_array_almost_equal(h1, h2)` following the reduceat.

This was not introduced in r6977, similar warnings appear after reverting it (but then the test always fails). Apparently, there's something amiss in ReduceAt that's still not fixed.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-11-25

**Comment by thouis** [comment]
Comment in Trac by atmention:teoliphant, 2009-12-02

The identity pointer was not initialized correctly for the ReduceAt when using the BUFFER part of the loop).  

This is fixed in r7823 for numpy1.4 and in r7824 for trunk.
