### ISSUE TITLE
Fix endianness-detection on ppc64 builds (migrated from Trac #1111)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2664]
Original ticket http://projects.scipy.org/numpy/ticket/1111
Reported 2009-05-20 by atmention:dwf, assigned to unknown.

Trying to build either a fat64 or a 4-way binary of NumPy on Mac OS X is failing in svn r7002 an endianness detection error. This came up on the mailing list ([http://mail.scipy.org/pipermail/scipy-user/2009-May/021066.html thread]) and I encountered it myself. Some #warnings show PPC64 builds are the problem:

```
$ gcc -arch ppc64 -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -O3 -Wall -DNDEBUG -g -fwrapv -Wstrict-prototypes -arch x86_64 -arch ppc64 -Inumpy/core/include -Ibuild/src.macosx-10.5-fat64-2.6/numpy/core/include/numpy -Inumpy/core/src -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/include -I/Library/Frameworks/Python64.framework/Versions/2.6/include/python2.6 -Ibuild/src.macosx-10.5-fat64-2.6/numpy/core/src/multiarray -Ibuild/src.macosx-10.5-fat64-2.6/numpy/core/src/umath -c  build/src.macosx-10.5-fat64-2.6/numpy/core/src/_sortmodule.c
In file included from numpy/core/include/numpy/npy_endian.h:22,
                 from numpy/core/include/numpy/ndarrayobject.h:33,
                 from numpy/core/include/numpy/noprefix.h:7,
                 from numpy/core/src/_sortmodule.c.src:29:
numpy/core/include/numpy/npy_cpu.h:39:6: warning: #warning "PPC64! Hooray!"
In file included from numpy/core/include/numpy/ndarrayobject.h:33,
                 from numpy/core/include/numpy/noprefix.h:7,
                 from numpy/core/src/_sortmodule.c.src:29:
numpy/core/include/numpy/npy_endian.h:33:10: error: #error Unknown CPU: can not set endianness
In file included from numpy/core/include/numpy/npy_endian.h:22,
                 from numpy/core/include/numpy/ndarrayobject.h:33,
                 from numpy/core/include/numpy/noprefix.h:7,
                 from numpy/core/src/_sortmodule.c.src:29:
numpy/core/include/numpy/npy_cpu.h:30:6: warning: #warning "AMD64! Hooray!"
lipo: can't figure out the architecture type of: /var/folders/jz/jzMQLnV-GOWCP55tPgPBl++++Tc/-Tmp-//ccjBE91A.out
```

I've attached a tiny patch that fixes this, adds PPC64 as one of the architectures detected as big-endian.

**Comment by thouis** [comment]
Attachment in Trac by atmention:dwf, 2009-05-20: [endian_ppc64.patch](http://projects.scipy.org/numpy/attachment/ticket/1111/endian_ppc64.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-05-20

Thanks for the fix, applied in r7003. Can you confirm it works ? If so, I will backport it to 1.3.1.

**Comment by thouis** [comment]
Comment in Trac by atmention:dwf, 2009-05-20

No problem. I can confirm that PPC64 builds work now as of r7007. 4-way universal binary builds seem a bit wonky, something goes wrong with 32-bit mode but 64-bit works fine.

I do observe one test failure on PPC64:

```
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex64'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python64.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/Library/Frameworks/Python64.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/tests/test_umath.py", line 524, in check_loss_of_precision
    assert np.all(d < 1e-15)
AssertionError
```

but everything else seems fine.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-06-01
