### ISSUE TITLE
ppc (32 and 64 bits) test failure: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex64'>,) (migrated from Trac #1113)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2666]
Original ticket http://projects.scipy.org/numpy/ticket/1113
Reported 2009-05-20 by atmention:dwf, assigned to unknown.

I'm seeing this test fail with a PPC64 build on with a 4-way universal binary Python 2.6.2, r7007. Looks similar to #1038, but it's a complex64 rather than a complex256.

```
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex64'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python64.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/Library/Frameworks/Python64.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/tests/test_umath.py", line 524, in check_loss_of_precision
    assert np.all(d < 1e-15)
AssertionError
```

**Comment by thouis** [comment]
Comment in Trac by atmention:dwf, 2009-05-23

This actually affects PPC64 _and_ PPC, I've discovered.

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-05-23

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-03-24
