### ISSUE TITLE
distutils barfs when building a library from a .c.src file if add_library does not have depends argument (migrated from Trac #1134)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2687]
Original ticket http://projects.scipy.org/numpy/ticket/1134
Reported 2009-06-09 by atmention:cournape, assigned to atmention:dmcooke.

Example:

```
#!python
...
config.add_library('yo', sources=['yo.c.src'])
...
```

Will return:

```
Traceback (most recent call last):
  File "setup.py", line 185, in <module>
    setup_package()
  File "setup.py", line 178, in setup_package
    configuration=configuration )
  File "/usr/media/src/dsp/numpy/numpy-git/numpy/distutils/core.py", line 184, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python2.5/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.5/distutils/dist.py", line 974, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.5/distutils/dist.py", line 994, in run_command
    cmd_obj.run()
  File "/usr/media/src/dsp/numpy/numpy-git/numpy/distutils/command/install.py", line 49, in run
    r = old_install.run(self)
  File "/usr/lib/python2.5/distutils/command/install.py", line 506, in run
    self.run_command('build')
  File "/usr/lib/python2.5/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.5/distutils/dist.py", line 994, in run_command
    cmd_obj.run()
  File "/usr/media/src/dsp/numpy/numpy-git/numpy/distutils/command/build.py", line 37, in run
    old_build.run(self)
  File "/usr/lib/python2.5/distutils/command/build.py", line 113, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.5/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.5/distutils/dist.py", line 994, in run_command
    cmd_obj.run()
  File "/usr/media/src/dsp/numpy/numpy-git/numpy/distutils/command/build_src.py", line 130, in run
    self.build_sources()
  File "/usr/media/src/dsp/numpy/numpy-git/numpy/distutils/command/build_src.py", line 141, in build_sources
    self.build_library_sources(*libname_info)
  File "/usr/media/src/dsp/numpy/numpy-git/numpy/distutils/command/build_src.py", line 222, in build_library_sources
    sources = self.template_sources(sources, (lib_name, build_info))
  File "/usr/media/src/dsp/numpy/numpy-git/numpy/distutils/command/build_src.py", line 353, in template_sources
    if (self.force or newer_group([source] + depends, target_file)):
TypeError: can only concatenate list (not "NoneType") to list
```

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-06-09

Fixed in r7046 in trunk, r7047 in 1.3.x
