### ISSUE TITLE
Multiplying Python float to numpy.array of objects works but fails with a numpy.float64 (migrated from Trac #1136)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2689]
Original ticket http://projects.scipy.org/numpy/ticket/1136
Reported 2009-06-10 by atmention:b45ch1, assigned to unknown.

This is best explained by the following example:

```
class adouble:
      def __init__(self,x):
              self.x = x
      def __mul__(self,rhs):
              if isinstance(rhs,adouble):
                      return adouble(self.x * rhs.x)
              else:
                      return adouble(self.x * rhs)
      def __str__(self):
              return str(self.x)

x = adouble(3.)
y = adouble(2.)
u = array([adouble(3.), adouble(5.)])
v = array([adouble(2.), adouble(7.)])
z = array([2.,3.])

print 'numpy.__version__=',numpy.__version__
print x * y              # ok
print u * v              # ok
print u * z              # ok
print u * 3.             # ok
print u * z[0]           # _NOT_ OK!
print u * float64(3.)    # _NOT_ OK!
```

Output:
    bastiatmention:shlp:~/tmp$ python numpy_float64_issue.py
    numpy.**version**= 1.4.0.dev7039
    6.0
    [6.0 35.0]
    [6.0 15.0]
    [9.0 15.0]
    Traceback (most recent call last):
     File "numpy_float64_issue.py", line 26, in <module>
       print u \* z[0]           # _NOT_ OK!
    TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and
    'numpy.float64'

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-11-25

**Comment by thouis** [comment]
Comment in Trac by atmention:b45ch1, 2010-02-13

bug still persistent in version 1.5.0.dev

```
b45ch1atmention:shlp:~/workspace/numpy_bugs$ python bug_float64_op_object.py
numpy.__version__= 1.5.0.dev
6.0
[6.0 35.0]
[6.0 15.0]
[9.0 15.0]
Traceback (most recent call last):
  File "bug_float64_op_object.py", line 26, in <module>
    print u * z[0]           # _NOT_ OK!
TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'numpy.float64'
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:b45ch1, 2010-02-13: [test_bugs.py](http://projects.scipy.org/numpy/attachment/ticket/1136/test_bugs.py)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-03-04

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-24

It's not necessary to introduce the "adouble" type, just making u an object array is enough:

```
In [19]: v = np.array([2,3], dtype=object)

In [20]: v * z[0]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/mwiebe/<ipython-input-20-384f41272ec5> in <module>()
----> 1 v * z[0]

TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'numpy.float64'
```

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-24

Marking as a duplicate of #1150, since it has a clearer explanation.
