### ISSUE TITLE
lookfor is broken on Python2.6 (migrated from Trac #1141)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2694]
Original ticket http://projects.scipy.org/numpy/ticket/1141
Reported 2009-06-19 by atmention:pv, assigned to unknown.

Lookfor on Python2.6 is broken:
    >>> import numpy as np
    >>> np.lookfor('binary representation')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/pauli/koodi/proj/scipy/numpy/dist/linux/lib/python2.6/site-packages/numpy-1.4.0.dev7066.420e060cb4a1975bf5ccb6e0b56bc3750159c4a6-py2.6-linux-i686.egg/numpy/lib/utils.py", line 574, in lookfor
        cache = _lookfor_generate_cache(module, import_modules, regenerate)
      File "/home/pauli/koodi/proj/scipy/numpy/dist/linux/lib/python2.6/site-packages/numpy-1.4.0.dev7066.420e060cb4a1975bf5ccb6e0b56bc3750159c4a6-py2.6-linux-i686.egg/numpy/lib/utils.py", line 724, in _lookfor_generate_cache
        for n, v in inspect.getmembers(item):
      File "/usr/lib/python2.6/inspect.py", line 256, in getmembers
        value = getattr(object, key)
    AttributeError: __abstractmethods__

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-07-26

Works for me. Still broken for you?
    In [33]: np.lookfor('binary representation')
    Search results for 'binary representation'
    ------------------------------------------
    numpy.ma.bitwise_and
        Compute the bit-wise AND of two arrays element-wise.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-07-26

Was fixed in r7584
