### ISSUE TITLE
unit test suite test fails after installing scipy and numpy (migrated from Trac #1144)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2697]
Original ticket http://projects.scipy.org/numpy/ticket/1144
Reported 2009-06-20 by trac user iftikhar.khan, assigned to unknown.

Hi, Just installed python 2.6 and the 2.6 versions of scipy & numpy onto my Windows machine. Get the following error when running scipy.test() and numpy.test():

> > > numpy.test()
> > > Running unit tests for numpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python26\lib\site-packages\numpy\testing\nosetester.py", line 242, in
> > >  test
> > >     self._show_system_info()
> > >   File "C:\Python26\lib\site-packages\numpy\testing\nosetester.py", line 149, in
> > >  _show_system_info
> > >     nose = import_nose()
> > >   File "C:\Python26\lib\site-packages\numpy\testing\nosetester.py", line 49, in
> > > import_nose
> > >     raise ImportError(msg)
> > > ImportError: Need nose >= 0.10.0 for tests - see http://somethingaboutorange.com
> > > /mrl/projects/nose

---

> > > scipy.test()
> > > Running unit tests for scipy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python26\lib\site-packages\numpy\testing\nosetester.py", line 242, in
> > >  test
> > >     self._show_system_info()
> > >   File "C:\Python26\lib\site-packages\numpy\testing\nosetester.py", line 149, in
> > >  _show_system_info
> > >     nose = import_nose()
> > >   File "C:\Python26\lib\site-packages\numpy\testing\nosetester.py", line 49, in
> > > import_nose
> > >     raise ImportError(msg)
> > > ImportError: Need nose >= 0.10.0 for tests - see http://somethingaboutorange.com
> > > /mrl/projects/nose

I went to the nosetest website but it is dedicated to just the UNIX OS.

Thanks

Iftikhar

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-07-13

Not really, it only ships the source code. You can install it just like any other Python package. For help, you can eg. ask on the mailing lists.
