### ISSUE TITLE
argmin doesn't work with datetime objects (migrated from Trac #1149)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2702]
Original ticket http://projects.scipy.org/numpy/ticket/1149
Reported 2009-06-25 by trac user doylejg, assigned to unknown.

With a numpy array of ''datetime'' or ''datetime.timedelta'' objects, it appears that ''min'' will work, but ''argmin'' will not. 
I have attached the traceback.
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.5/site-packages/numpy/core/fromnumeric.py", line 632, in argmin
        return argmin(axis)
    TypeError: unsupported operand type(s) for -: 'int' and 'datetime.timedelta'

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-11-25

**Comment by thouis** [comment]
Comment in Trac by trac user doylejg, 2011-05-27

**Comment by thouis** [comment]
Comment in Trac by trac user bshanks, 2012-02-01

still an issue in 1.6.1.

interestingly, argmax seems to work fine.

**Comment by thouis** [comment]
Comment in Trac by trac user bshanks, 2012-02-01

workaround (for the convenience of people who need to argmin dates):

from numpy import isnan
def argmin(listable):
    xs = list(listable)
    current_min = xs[0]
    current_min_loc = 0
    for i in range(len(xs)):
        item = xs[i]
        if item < current_min:
            current_min = item
            current_min_loc = i
        try:
            if isnan(item):
                current_min = item
                current_min_loc = i
        except TypeError:
            pass
    return current_min_loc

**Comment by thouis** [comment]
Comment in Trac by trac user bshanks, 2012-02-01

```
from numpy import isnan
def argmin(listable):
    xs = list(listable)
    current_min = xs[0]
    current_min_loc = 0
    for i in range(len(xs)):
        item = xs[i]
        if item < current_min:
            current_min = item
            current_min_loc = i
        try:
            if isnan(item):
                current_min = item
                current_min_loc = i
        except TypeError:
            pass
    return current_min_loc
```

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-02-01

Fixed in master branch.
