### ISSUE TITLE
FAIL: Tests new ufuncs on MaskedArrays. (Solaris) (migrated from Trac #1173)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2726]
Original ticket http://projects.scipy.org/numpy/ticket/1173
Reported 2009-07-15 by atmention:stsci-sienkiew, assigned to atmention:pierregm.

```
======================================================================
FAIL: Tests new ufuncs on MaskedArrays.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ra/pyssg/2.5.1/numpy/ma/tests/test_core.py", line 1403, in test_testUfuncRegression
    assert_mask_equal(ur.mask, mr.mask)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 237, in assert_mask_equal
    assert_array_equal(m1, m2)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 193, in assert_array_equal
    header='Arrays are not equal')
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 186, in assert_array_compare
    verbose=verbose, header=header)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 395, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 25.0%)
 x: array([False,  True, False,  True, False, False, False,  True], dtype=bool)
 y: array([False,  True, False, False, False, False, False, False], dtype=bool)
```

numpy 1.4.0.dev7132

solaris 8

python 2.5.1

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2009-07-18

I do not have access to a Solaris machine, so more details are needed: could you provide more information about which function ('sqrt', 'log', 'log10', 'exp',...) actually stalls the test ?

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-07-20

Ok, let me add to this report:  "This test does not adequately report information about the test failure."

Please make these changes to the source:

In numpy/ma/tests/test_core.py near line 3177, change
                assert_mask_equal(ur.mask, mr.mask)
to
                assert_mask_equal(ur.mask, mr.mask, err_msg=f)

In numpy/ma/testutils.py at the end of the file, change assert_mask_equal:  add parameter err_msg='' and pass err_msg on to assert_array_equal()

```
======================================================================
FAIL: Tests new ufuncs on MaskedArrays.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ra/pyssg/2.5.1/numpy/ma/tests/test_core.py", line 1409, in test_testUfuncRegression
    assert_mask_equal(ur.mask, mr.mask, err_msg=f)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 237, in assert_mask_equal
    assert_array_equal(m1, m2, err_msg)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 193, in assert_array_equal
    header='Arrays are not equal')
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 186, in assert_array_compare
    verbose=verbose, header=header)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 395, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal
arcsin
(mismatch 25.0%)
 x: array([False,  True, False,  True, False, False, False,  True], dtype=bool)
 y: array([False,  True, False, False, False, False, False, False], dtype=bool)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-07-20

That last bit said 
{{{ add parameter err_msg='' and pass err_msg ... }}}

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-11-25

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2009-12-07

This is still happening in 1.4.0rc1.  This time, I tested on:

Solaris 10
Python 2.5.4, 64 bit executable

b.t.w.  Ticket #1204 is a duplicate of this one, filed about a month later.

**Comment by thouis** [comment]
Attachment in Trac by atmention:mdboom, 2009-12-07: [domain.patch](http://projects.scipy.org/numpy/attachment/ticket/1173/domain.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-12-07

The problem seems to be based on a difference in how the Sun stdlib and the GNU stdlib handle out-of-domain values to asin (and others).

The Sun asin manpage says:

```
If the value of x is
not in the range [-1,1] and is not +Inf or NaN, either  0.0
or NaN is returned and errno is set to EDOM.
```

The GNU asin manpage says:

```
If x falls outside the range -1 to 1, asin() fails and errno is set.
```

On Sun C 5.3 (SPARC), asin(pi/2) gives 0.0.  On gcc 3.4.6 (Linux/x86), asin(pi/2) gives NaN.  When calling asin inside the context of numpy.ma.core.arcsin (which is wrapped by the _MaskedUnaryOperation class), the errno handling is turned off.  On Sun, this means you get a "valid-seeming" 0.0 back.  On gcc, you get a NaN which is masked out, which (completely by accident) happens to match the correct behavior when calling asin with errno handling turned on.

The fix appears to be to apply a mask based on the domain of the input values (see patch).  This isn't strictly necessary on platforms where EDOM errors are accompanied by NaN results.  If we want to wrap this domain checking in a platform check, that may be preferable for performance reasons.

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2009-12-07

I applied the patch on the trunk. Mind applying it to the 1.4.x branch as well ?

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-12-07

Patch applied to 1.4.x branch.  I believe there was an error in r7978 -- the assert_mask_equal method does not have an err_msg kwarg.  I added that in r7979 to the branch.  I'd add this to the trunk as well, but the trunk is currently segfaulting unpredictably for me (probably for other reasons).

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-12-07

I got my trunk build working again, and have fixed the "err_msg" keyword bug there, too.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-16

All fixed then it seems.
