### ISSUE TITLE
chararray.expandtabs broken (migrated from Trac #1199)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2752]
Original ticket http://projects.scipy.org/numpy/ticket/1199
Reported 2009-08-18 by trac user dgoldsmith, assigned to unknown.

> > > c = np.array(['aAaAaA', '\taA\t', 'abBABba']).view(np.chararray); c
> > > chararray(['aAaAaA', '\taA', 'abBABba'],
> > >       dtype='|S7')
> > > c.expandtabs()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "C:\Python25\lib\site-packages\numpy\core\defchararray.py", line 223, in expandtabs
> > >     return self._generalmethod('endswith', broadcast(self, tabsize))
> > >   File "C:\Python25\lib\site-packages\numpy\core\defchararray.py", line 158, in _generalmethod
> > >     newitem = getattr(val[0],name)(*newval)
> > > TypeError: endswith() takes at least 1 argument (0 given)

And yet:

> > > help(c.expandtabs)
> > > Help on method expandtabs in module numpy.core.defchararray:

expandtabs(self, tabsize=None) method of numpy.core.defchararray.chararray instance

So expandtabs isn't supposed to require an argument, and thus must itself generate the argument endswith is looking for, but isn't doing so.

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-10-12

This bug is fixed as part of the chararray refactoring in SVN r7514, which also adds a unit test.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-04-24

Fixed in svn.
