### ISSUE TITLE
FAIL: test_umath.test_arctan2_special_values(0.0, 3.1415926535897931) [ SOLARIS ] (migrated from Trac #1201)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2754]
Original ticket http://projects.scipy.org/numpy/ticket/1201
Reported 2009-08-20 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
FAIL: test_umath.test_arctan2_special_values(0.0, 3.1415926535897931)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.1/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 421, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal
 ACTUAL: 0.0
 DESIRED: 3.1415926535897931
```

1.4.0.dev7284 (august 6)

1.4.0.dev7303 (august 19)

Python 2.5.1, Solaris 8, cc: Sun WorkShop 6 update 2 C 5.3 Patch 111679-14 2004/02/20

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-11-13

Fixed in r7732 by using the Numpy-included implementation of atan2.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-11-14
