### ISSUE TITLE
test_umath.test_arctan2_special_values(-0.0, 0.0) (migrated from Trac #1203)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2756]
Original ticket http://projects.scipy.org/numpy/ticket/1203
Reported 2009-08-20 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
FAIL: test_umath.test_arctan2_special_values(-0.0, 0.0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.1/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/usr/ra/pyssg/2.5.1/numpy/core/tests/test_umath.py", line 235, in assert_arctan2_isnzero
    assert ncu.arctan2(x, y) == 0 and np.signbit(ncu.arctan2(x, y))
AssertionError
```

1.4.0.dev7284 (august 6)

1.4.0.dev7303 (august 19)

Python 2.5.1, Solaris 8, cc: Sun WorkShop 6 update 2 C 5.3 Patch 111679-14 2004/02/20

I put in three tickets for this one (the other two are #1201 and #1202) before I noticed that the problem is probably that arctan2 doesn't work.

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-11-13

Fixed in r7732 by using the Numpy-included implementation of atan2.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-11-14
