### ISSUE TITLE
Test failure: new ufuncs on MaskedArrays. [ SOLARIS ] (migrated from Trac #1204)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2757]
Original ticket http://projects.scipy.org/numpy/ticket/1204
Reported 2009-08-20 by atmention:stsci-sienkiew, assigned to atmention:pierregm.

```
======================================================================
FAIL: Tests new ufuncs on MaskedArrays.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/ra/pyssg/2.5.1/numpy/ma/tests/test_core.py", line 1419, in test_testUfuncRegression
    assert_mask_equal(ur.mask, mr.mask)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 237, in assert_mask_equal
    assert_array_equal(m1, m2)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 193, in assert_array_equal
    header='Arrays are not equal')
  File "/usr/stsci/pyssgdev/2.5.1/numpy/ma/testutils.py", line 186, in assert_array_compare
    verbose=verbose, header=header)
  File "/usr/stsci/pyssgdev/2.5.1/numpy/testing/utils.py", line 571, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 25.0%)
 x: array([False,  True, False,  True, False, False, False,  True], dtype=bool)
 y: array([False,  True, False, False, False, False, False, False], dtype=bool)
```

1.4.0.dev7284 (august 6)

1.4.0.dev7303 (august 19)

Python 2.5.1, Solaris 8, cc: Sun WorkShop 6 update 2 C 5.3 Patch 111679-14 2004/02/20

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-06-02

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-06-02

Mmh... W/o more details about what actual function(s) fail(s), I'm in the dark. Solaris users, please contact me directly.

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2010-06-02

This ticket was filed 10 months ago; it appears somebody fixed this problem since then, so no further fix is necessary.

(b.t.w.  How would I contact you directly?  Does trac have a registry of email addresses somewhere? sienkiew at stsci dot edu )

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-06-02

Does this mean we can close the ticker ? Ralf, you confirm ?
For direct contact, use the numpy mailing list (you can find one email that should work for me...)

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2010-06-02

All I really know is that the test is not failing any more.  I am only indirectly involved with numpy, so I don't know if your work flow considers that sufficient.  In the absence of other formal criteria, I think it would make sense to close this ticket.

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-06-02

If the test doesn't fail, everything's fine on my side.
