### ISSUE TITLE
Docstring for numpy.numarray.random_array.multinomial is out of date. (migrated from Trac #1209)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2762]
Original ticket http://projects.scipy.org/numpy/ticket/1209
Reported 2009-08-27 by trac user throwaway, assigned to unknown.

It appears that the semantics of the multinomial function have changed,
and the docstring has not kept pace with it.  Here is what the docstring
says:

```
There are len(prob)+1 events.
prob[i] is the probability of the i-th event, 0<=i<len(prob).
The probability of event len(prob) is 1.-Numeric.sum(prob).
```

Contrast that with this behavior:

```
>>> from numpy.numarray.random_array import multinomial

>>> multinomial(10000, [0.5, 0.5])

array([5010, 4990])
```

It used to be that you'd have to leave off the last probability entry.
It's much more convenient that you don't have to do that anymore, but
since it continues to silently accept input in the old form, it's caused
me a great deal of confusion.

Here is the old behavior, for sake of contrast

```
>>> from RandomArray import multinomial

>>> multinomial(10000, [0.5,])

array([4982, 5018])

>>> multinomial(10000, [0.5,0.5])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.5/site-packages/Numeric/RandomArray.py", line 221, in multinomial
    x = ranlib.multinomial(trials, probs.astype(Numeric.Float32), Numeric.multiply.reduce(shape))
RuntimeError: Sum of P(i) > 1 in GENMUL
```

The new form still accepts this input:

```
>>> from numpy.numarray.random_array import multinomial

>>> multinomial(10000, [0.5,])

array([10000])
```

These examples come from numpy version 1.0.4 (Ubuntu Hardy), but the
same problems seem to apply to version 1.2.1 (Ubuntu Jaunty).  I don't
have access to the latest numpy version to check there.  Apologies for
the redundant report, if this problem has already been corrected.

Incidentally, the reason I moved to the numarray multinomial function is that the one in oldnumeric has a memory leak.  If this is worth attention, I will be happy to submit a bug report about that, too.

**Comment by thouis** [comment]
Comment in Trac by atmention:josef-pkt, 2009-11-26

The current behavior seems to be:

> > > numpy.version.version
> > > '1.4.0.dev7758'

It takes the length of the probs list/array as the number of support points but ignores the content of the last entry:
    >>> np.random.multinomial(1000, [0.5,0.4]) 
    array([495, 505])
    >>> np.random.multinomial(1000, [0.5,0.2]) 
    array([519, 481])
    >>> np.random.multinomial(1000, [0.5]) 
    array([1000])
    >>> np.random.multinomial(1000, [0.5, 0.9]) 
    array([518, 482])

```
>>> np.random.multinomial(10000, [0.3, 0.3, 0.9]) 
array([2942, 3068, 3990])
>>> np.random.multinomial(100000, [0.3, 0.3, 0.9]) 
array([30028, 29967, 40005])
>>> 
>>> np.random.multinomial(100000, [0.3, 0.3, 0.1]) 
array([30118, 29956, 39926])

>>> np.random.multinomial(100000, [0.3, 0.3]) 
array([29795, 70205])
```

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-24
