### ISSUE TITLE
numpy.linalg.eig crashes on Mandriva/OpenSuse for some matrices (migrated from Trac #1211)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2764]
Original ticket http://projects.scipy.org/numpy/ticket/1211
Reported 2009-08-30 by atmention:pv, assigned to unknown.

See this discussion: http://article.gmane.org/gmane.comp.python.scientific.user/21936

---

The attached script crashes with SIGSEGV on on Mandriva 2009.1, 64-bit and OpenSUSE.

**Comment by thouis** [comment]
Attachment in Trac by atmention:pv, 2009-08-30: [cheby.py](http://projects.scipy.org/numpy/attachment/ticket/1211/cheby.py)

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-08-30

Regarding Mandriva, the test fails on both 32 bit and 64 bit versions. I'm currently using 32 bit version. 

Before trying the steps you laid out on scipy mailing list, just a quick note. When running your modified cheby.py script, the program does not crash:

[Thread debugging using libthread_db enabled]
[New Thread 0xb7c216c0 (LWP 5075)]
PRE
POST
[ 0.99144486  0.92387953  0.79335334  0.60876143  0.38268343 -0.99144486
  0.13052619 -0.92387953 -0.13052619 -0.79335334 -0.38268343 -0.60876143]
det(A)=0.000488281

Program exited normally.

But, as soon as I comment out the following lines: 

#sys.stderr.write('POST\n')
#sys.stderr.flush()

this is what happens: 
[New Thread 0xb7c406c0 (LWP 5111)]
PRE
[ 0.99144486  0.92387953  0.79335334  0.60876143  0.38268343 -0.99144486
  0.13052619 -0.92387953 -0.13052619 -0.79335334 -0.38268343 -0.60876143]
det(A)=0.000488281

Program received signal SIGSEGV, Segmentation fault.
0xb7ec4ed8 in ?? () from /usr/lib/libpython2.6.so.1.0

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-08-30

I cherry picked the tests you proposed. This time I replaced libatlas3-sse with libatlas3-sse3, and there are no more crashes with that particular test. However, when I reversed the change in scipy.special to use numpy.dual, the following test fails: 

> > > from scipy.special import chebyt
> > > chebyt(12)(-0.5)
> > > 0.999999999999998
> > > quit()

Program received signal SIGSEGV, Segmentation fault.
0xb7fb44d0 in ?? () from /usr/lib/libpython2.6.so.1.0

This just means that the test script cheby.py does not completely test the problem.

**Comment by thouis** [comment]
Attachment in Trac by trac user ivom, 2009-08-30: [numpy_scipy_test_log.txt](http://projects.scipy.org/numpy/attachment/ticket/1211/numpy_scipy_test_log.txt)

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-08-30

I installed all the missing debug packages under Mandriva, and hopefully this should give 
a better idea as to where the problem is: 

(gdb) run ch.py
Starting program: /usr/bin/python ch.py
[Thread debugging using libthread_db enabled]
[New Thread 0xb7d606c0 (LWP 6368)]
1.0

Program received signal SIGSEGV, Segmentation fault.
dict_dealloc (mp=0xb69c88ac) at Objects/dictobject.c:910
910                             Py_DECREF(ep->me_key);
(gdb)

**Comment by thouis** [comment]
Attachment in Trac by trac user ivom, 2009-08-30: [ch.py](http://projects.scipy.org/numpy/attachment/ticket/1211/ch.py)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-08-30

Some comments:
- install the Nose package to run the numpy and scipy tests
- what about atlas without SSE at all?
- please type 'bt' on the '(gdb)' prompt after the crash to see the backtrace.
  (Note that you can include lines in Trac between {{{  }}} and it'll be typeset nicely.)

Note that it's likely that the backtrace from gdb may not be very useful, since the crash seems to occur due to memory corruption -> it doesn't crash where the corruption happens, but later on when something depends on the corrupted memory and bombs. This makes it all quite a bit more difficult to debug. Valgrind might reveal at which point the corruption occurs.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-08-30

Also: what about non-ATLAS blas?

**Comment by thouis** [comment]
Attachment in Trac by trac user ivom, 2009-08-30: [backtrace.log](http://projects.scipy.org/numpy/attachment/ticket/1211/backtrace.log)

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-08-31

I cannot locate any 'other' blas and atlas libraries, but I will look it up agian tomorrow. The same applies to openSUSE, where there is only one set of each.

**Comment by thouis** [comment]
Attachment in Trac by trac user ivom, 2009-08-31: [numpy_scipy_test_openSUSE.log](http://projects.scipy.org/numpy/attachment/ticket/1211/numpy_scipy_test_openSUSE.log)

**Comment by thouis** [comment]
Attachment in Trac by trac user ivom, 2009-08-31: [numpy_scipy_test_mandriva.log](http://projects.scipy.org/numpy/attachment/ticket/1211/numpy_scipy_test_mandriva.log)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-08-31

It seems the problem is already triggered by Numpy's tests (you can try 'numpy.test(verbose=2)' to see which one), so we probably don't need new tests. Mandriva/Opensuse people have apparently not tested that their packages work.

Atlas is one BLAS library. Other BLAS libraries on mandriva/suse are probably named libblas*.

Regarding bug reports to the distributions:
- http://wiki.mandriva.com/en/Bug_policy
- http://en.opensuse.org/Submitting_Bug_Reports

It's probably useful to add a link to here in the distribution bug reports.

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-08-31

Will try later (to run with verbosity level set to 2), but I'm not sure that the problem triggered by ch.py is triggered on Mandriva. It is triggered on openSUSE though. 

As for the libraries, it is not that I don't know how to search for libraries, but simply I cannot find any among the existing packages. Not even under ubuntu, which I currently have access to: 

```
 aptitude search libblas*
v   libblas-3gf.so                                    -                                                             
p   libblas-dev                                       - Basic Linear Algebra Subroutines 3, static library          
p   libblas-doc                                       - Basic Linear Algebra Subroutines 3, documentation           
p   libblas-test                                      - Basic Linear Algebra Subroutines 3, testing programs        
v   libblas.so.3gf                                    -                                                             
i A libblas3gf                                        - Basic Linear Algebra Subroutines 3, shared library 
```

**Comment by thouis** [comment]
Attachment in Trac by trac user ivom, 2009-08-31: [numpy_test_ubuntu904.log](http://projects.scipy.org/numpy/attachment/ticket/1211/numpy_test_ubuntu904.log)

**Comment by thouis** [comment]
Comment in Trac by atmention:lebedov, 2009-08-31

**Comment by thouis** [comment]
Comment in Trac by atmention:lebedov, 2009-09-01

Upgrading to lapack 3.2.1 (which will be the default in Mandriva 2010.*) appears to solve the numpy problem. I built experimental lapack 3.2.1 packages for Ivo to try out on Mandriva 2009.1; if they do solve the problem, I'll see to porting them back to Mandriva 2009.1 as an official update.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-09-01

Question: does rebuilding Lapack 3.1.1, but with different compiler options help?

What I'm slightly puzzled about is that according to Ivo's report, replacing `numpy.linalg.eig` with `scipy.linalg.eig` made the crashes go away (both call DGEEV in the end). But I guess it's possible that since this seems to be a heisenbug, the memory corruption, or whatever causes this, is hidden in the other case.

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-09-02

Lev, 

In: 
/usr/lib64/python/site-packages/scipy/special

or in (depending on the architecture):
/usr/lib/python/site-packages/scipy/special

modify orthogonal.py as shown below (the eigenvalue call): 

# Scipy imports.

import numpy as np
from numpy import all, any, exp, inf, pi, sqrt
#from numpy.dual import eig    # <-- comment out this line
from scipy.linalg import eig   # <-- Add this. Call eig from scipy.linalg 

and see what happens with the old library. It worked for me.

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-09-02

Lev,

In: 

```
/usr/lib64/python/site-packages/scipy/special
```

or in (depending on the architecture): 
    /usr/lib/python/site-packages/scipy/special

modify orthogonal.py as shown below (the eigenvalue call):

```
# Scipy imports. 
import numpy as np from numpy import all, any, exp, inf, pi, sqrt 
#from numpy.dual import eig  # <-- comment out this line 
from scipy.linalg import eig # <-- Add this. Call eig from scipy.linalg
```

and see what happens with the old library. It worked for me.

**Comment by thouis** [comment]
Comment in Trac by atmention:lebedov, 2009-09-02

Replying to [comment:11 pv]:

> Question: does rebuilding Lapack 3.1.1, but with different 
> compiler options help?

I haven't tried that yet.

Currently, it appears that most of blas/lapack on Mandriva is compiled with the options 

-O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -fomit-frame-pointer -march=i586 -mtune=generic -fasynchronous-unwind-tables -Os -fPIC 

(Some of these are stock flags used to compile many Mandriva packages.)

**Comment by thouis** [comment]
Comment in Trac by atmention:lebedov, 2009-09-02

Replying to [comment:13 ivom]:

> Lev,
> 
> In: 
> 
> {{{
> /usr/lib64/python/site-packages/scipy/special
> }}}
> 
> or in (depending on the architecture): 
> {{{
> /usr/lib/python/site-packages/scipy/special
> }}}
> 
> modify orthogonal.py as shown below (the eigenvalue call):
> 
> {{{
> 
> # Scipy imports.
> 
> import numpy as np from numpy import all, any, exp, inf, pi, sqrt 
> #from numpy.dual import eig  # <-- comment out this line 
> from scipy.linalg import eig # <-- Add this. Call eig from scipy.linalg
> }}}
> 
> and see what happens with the old library. It worked for me.

Making the above change appears to prevent the segfault I mentioned earlier.

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-09-03

I've updated the liblapack3 library, and unfortunately it fails again: 

```
>>> from scipy.special import chebyt
>>> chebyt(12)(-0.5)
0.999999999999998
>>> quit()
Segmentation fault
```

or if I put the code listed above it into a file: 

```
[ivomatmention:localhost ~]$ python ch.py
1.0
Segmentation fault
[ivomatmention:localhost ~]$
```

The version of liblapack I've installed is: 

```
[rootatmention:localhost ~]# rpm -qi liblapack3                               
Name        : liblapack3                   Relocations: (not relocatable)
Version     : 3.2.1                             Vendor: Mandriva
Release     : 1mdv2009.1                    Build Date: Tue 01 Sep 2009 04:49:58 PM EDT
Install Date: Wed 02 Sep 2009 11:21:43 PM EDT      Build Host: n2.mandriva.com
```

**Comment by thouis** [comment]
Comment in Trac by atmention:lebedov, 2009-09-04

Replying to [comment:16 ivom]:

> I've updated the liblapack3 library, and unfortunately it fails 
> again: 

Strange..I tested another Mandriva 2009.1 (32 bit) installation I have access to that is running on a Pentium D CPU, and updating blas/lapack to 3.2.1 also solved the segfault on quit after running the chebyt() function (the cheby.py test program did not exhibit any problems with either lapack 3.2 or 3.2.1). I'll continue investigating..

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-09-04

OK, I just removed libatlas, and the problem went away: 

```
[ivomatmention:localhost ~]$ python ch.py
1.0
[ivomatmention:localhost ~]$ python
Python 2.6.1 (r261:67515, Aug 22 2009, 12:28:58)
[GCC 4.3.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.special import chebyt
>>> chebyt(12)(-0.5)
0.99999999999986799
>>> quit()
[ivomatmention:localhost ~]$
```

Now, the interesting thing is that I can no longer even locate libatlas when I do a search on it. 

Also, could you tell me what component is missing in python or numpy so that I can verify numpy.test()? You said that it works well for you, but I'm getting the following error message: 

```
======================================================================                       
ERROR: Failure: DistutilsPlatformError (invalid Python installation: unable to open /usr/lib/python2.6/config/Makefile (No such file or directory))                                       
----------------------------------------------------------------------                       
Traceback (most recent call last):                                                           
  File "/usr/lib/python2.6/site-packages/nose/loader.py", line 364, in loadTestsFromName     
    addr.filename, addr.module)                                                              
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 39, in importFromPath       
    return self.importFromDir(dir_path, fqname)                                              
  File "/usr/lib/python2.6/site-packages/nose/importer.py", line 84, in importFromDir        
    mod = load_module(part_fqname, fh, filename, desc)      
[snip]
```

**Comment by thouis** [comment]
Comment in Trac by atmention:lebedov, 2009-09-04

Replying to [comment:18 ivom]:

> OK, I just removed libatlas, and the problem went away: 

(snip)

> Now, the interesting thing is that I can no longer even locate
> libatlas when I do a search on it. 

What do you mean? Where are you searching? What do you see when you run the following on your system?

rpm -qa | grep atlas

> Also, could you tell me what component is missing in python or numpy so that I can verify numpy.test()? You said that it works well for you, but I'm getting the following error message: 
> 
> # 
> 
> ERROR: Failure: DistutilsPlatformError (invalid Python
> installation: unable to open /usr/lib/python2.6/config/Makefile
> (No such file or directory))

(snip)

That file is provided by libpython2.6-devel (you can determine what package provides a particular file using urpmf, i.e., 
urpmf /usr/lib/python2.6/config/Makefile).

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-09-04

> > Now, the interesting thing is that I can no longer even locate
> > libatlas when I do a search on it. 
> 
> What do you mean? Where are you searching? What do you see when you run the following on your system?
> 
> rpm -qa | grep atlas

Oh, that is not that important, I should not have mentioned it. I cleaned up my urpmi.cfg file, and I might have removed a bit too much :) I'll add some mirrors and that should be solved. But to answer your question, I did a search via a software installer GUI, which should give the same result as your command. This GUI based search seemed to work for any package I was looking for anyway. 

I think that the real issue here is that this points to a broken atlas library. On the other hand, if you didn't remove it, and you solved the problem just by installing a new version of liblapack library, than I am not sure if my assumption about atlas is correct. 

> > Also, could you tell me what component is missing in python or numpy so that I can verify numpy.test()? You said that it works well for you, but I'm getting the following error message: 
> > 
> > # 
> > 
> > ERROR: Failure: DistutilsPlatformError (invalid Python
> > installation: unable to open /usr/lib/python2.6/config/Makefile
> > (No such file or directory))
> 
> (snip)
> 
> That file is provided by libpython2.6-devel (you can determine what package provides a particular file using urpmf, i.e., 
> urpmf /usr/lib/python2.6/config/Makefile).

Thanks. I will install it and see what happens with numpy.test(). Maybe you want to add libpythonx.y-devel as an optional dependency (along with python-nose) to scimath package, so that this test can be executed.

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-09-05

I verified again, and it is quite consistent on my computer. With libaltas3-sse\* two tests, namely, ch.py and numpy.test() are crashing, and without the atlas library there is no problem. 

Note: It was tirival to bring the atlas library back once I figured out how this works.

**Comment by thouis** [comment]
Comment in Trac by trac user ivom, 2009-09-05

For what it's worth, I just updated liblapack and libblas to 3.2.1 under openSUSE, and the problem went away. I will have to see what happens if I update libblas to 3.2.1 under mandriva.

**Comment by thouis** [comment]
Comment in Trac by atmention:lebedov, 2009-09-07

Replying to [comment:21 ivom]:

> I verified again, and it is quite consistent on my computer. With
> libaltas3-sse\* two tests, namely, ch.py and numpy.test() are 
> crashing, and without the atlas library there is no problem. 
> 
> Note: It was trivial to bring the atlas library back once I 
> figured out how this works. 

The above happens intermittently on my system when the blas/lapack 3.2 are installed along with the libatlas3-sse\* packages. It does not occur when blas/lapack 3.2.1 are installed.

Interestingly, I did not observe any crash on another 32-bit 2009.1 system with a Pentium M CPU with blas/lapack 3.2.

**Comment by thouis** [comment]
Comment in Trac by atmention:lebedov, 2009-09-24

Given that lapack 3.2.1 does seem to solve some of the issues, I've asked the Mandriva QA folks to consider releasing it as an official update for 2009.1.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-03-24

Everything seems to point to a broken ATLAS build, so closing.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31
