### ISSUE TITLE
PyArray_INCREF numpy/core/src/multiarray/refcount.c (migrated from Trac #1216)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2769]
Original ticket http://projects.scipy.org/numpy/ticket/1216
Reported 2009-09-02 by atmention:nilswagner01, assigned to unknown.

```
>>> numpy.__version__
'1.4.0.dev7353'
>>> scipy.__version__
'0.8.0.dev5838'

Getting factors of real matrix ... ok
Prefactorize (with UMFPACK) matrix for solving with multiple rhs ...
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 47346072863120 (LWP 4228)]
PyArray_INCREF (mp=0xc) at numpy/core/src/multiarray/refcount.c:103
103         if (!PyDataType_REFCHK(mp->descr)) {
(gdb) bt
#0  PyArray_INCREF (mp=0xc) at numpy/core/src/multiarray/refcount.c:103
#1  0x00002b0fab9a34df in helper_getCArrayObject (input=0x1b2c1f0, type=12,
    minDim=1, maxDim=1)
    at build/src.linux-x86_64-2.5/scikits/umfpack/_umfpack_wrap.c:2535
#2  0x00002b0fab9a4eab in _wrap_umfpack_di_defaults (
    self=<value optimized out>, args=<value optimized out>)
    at build/src.linux-x86_64-2.5/scikits/umfpack/_umfpack_wrap.c:3054
```

**Comment by thouis** [comment]
Comment in Trac by atmention:nilswagner01, 2009-09-07

segfault vanished after an update to most recent svn. Ticket can be closed.

```
>>> numpy.__version__
'1.4.0.dev7361'
>>> scipy.__version__
'0.8.0.dev5838'

======================================================================
FAIL: test_io.test_imread
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/nose-0.10.4-py2.5.egg/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/local/lib64/python2.5/site-packages/scipy/ndimage/tests/test_io.py", line 9, in test_imread
    assert_array_equal(img.shape, (300, 420, 3))
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 639, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 532, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(shapes (0,), (3,) mismatch)
 x: array([], dtype=float64)
 y: array([300, 420,   3])

======================================================================
FAIL: test_asfptype (test_base.TestBSR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 242, in test_asfptype
    assert_equal( A.dtype , 'int32' )
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: Test manipulating empty matrices. Fails in SciPy SVN <= r1768
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 78, in test_empty_arithmetic
    assert_equal(m.dtype,mytype)
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: test_asfptype (test_base.TestCOO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 242, in test_asfptype
    assert_equal( A.dtype , 'int32' )
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: Test manipulating empty matrices. Fails in SciPy SVN <= r1768
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 78, in test_empty_arithmetic
    assert_equal(m.dtype,mytype)
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: test_asfptype (test_base.TestCSC)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 242, in test_asfptype
    assert_equal( A.dtype , 'int32' )
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: Test manipulating empty matrices. Fails in SciPy SVN <= r1768
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 78, in test_empty_arithmetic
    assert_equal(m.dtype,mytype)
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: test_asfptype (test_base.TestCSR)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 242, in test_asfptype
    assert_equal( A.dtype , 'int32' )
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: Test manipulating empty matrices. Fails in SciPy SVN <= r1768
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 78, in test_empty_arithmetic
    assert_equal(m.dtype,mytype)
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: test_asfptype (test_base.TestDIA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 242, in test_asfptype
    assert_equal( A.dtype , 'int32' )
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: Test manipulating empty matrices. Fails in SciPy SVN <= r1768
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 78, in test_empty_arithmetic
    assert_equal(m.dtype,mytype)
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: test_asfptype (test_base.TestDOK)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 242, in test_asfptype
    assert_equal( A.dtype , 'int32' )
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: Test manipulating empty matrices. Fails in SciPy SVN <= r1768
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 78, in test_empty_arithmetic
    assert_equal(m.dtype,mytype)
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: test_asfptype (test_base.TestLIL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 242, in test_asfptype
    assert_equal( A.dtype , 'int32' )
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: Test manipulating empty matrices. Fails in SciPy SVN <= r1768
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_base.py", line 78, in test_empty_arithmetic
    assert_equal(m.dtype,mytype)
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int32')
 DESIRED: 'int32'

======================================================================
FAIL: test_eye (test_construct.TestConstructUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_construct.py", line 84, in test_eye
    assert_equal(eye(3,3,dtype='int16').dtype, 'int16')
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int16')
 DESIRED: 'int16'

======================================================================
FAIL: test_identity (test_construct.TestConstructUtils)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/scipy/sparse/tests/test_construct.py", line 70, in test_identity
    assert_equal( I.dtype, 'int8' )
  File "/usr/local/lib64/python2.5/site-packages/numpy/testing/utils.py", line 274, in assert_equal
    raise AssertionError(msg)
AssertionError:
Items are not equal:
 ACTUAL: dtype('int8')
 DESIRED: 'int8'

======================================================================
FAIL: test_boost_data.test_all(<Boost test for psi: digamma_root_data_ipp-digamma_root_data>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/nose-0.10.4-py2.5.egg/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 196, in _test_factory
    test.check(dtype=dtype)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 332, in check
    assert False, "\n".join(msg)
AssertionError:
Max |adiff|: 9.29812e-16
Max |rdiff|: 3.15103e-12
Bad results for the following points (in output 0):
            1.4609999656677246 =>        -0.00061191937930571427 !=        -0.00061191937930632739  (rdiff         1.0019560570799086e-12)
            1.4615000486373901 =>        -0.00012783367977320381 !=          -0.000127833679772801  (rdiff          3.151033537081845e-12)

======================================================================
FAIL: test_boost_data.test_all(<Boost test for psi (complex): digamma_root_data_ipp-digamma_root_data>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/nose-0.10.4-py2.5.egg/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 196, in _test_factory
    test.check(dtype=dtype)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 332, in check
    assert False, "\n".join(msg)
AssertionError:
Max |adiff|: 9.29812e-16
Max |rdiff|: 3.15103e-12
Bad results for the following points (in output 0):
       (1.4609999656677246+0j) =>   (-0.00061191937930571427+0j) !=        -0.00061191937930632739  (rdiff         1.0019560570799086e-12)
       (1.4615000486373901+0j) =>   (-0.00012783367977320381+0j) !=          -0.000127833679772801  (rdiff          3.151033537081845e-12)

======================================================================
FAIL: test_boost_data.test_all(<Boost test for ellipeinc_: ellint_e2_data_ipp-ellint_e2_data>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/nose-0.10.4-py2.5.egg/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 196, in _test_factory
    test.check(dtype=dtype)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 332, in check
    assert False, "\n".join(msg)
AssertionError:
Max |adiff|: 2.27374e-13
Max |rdiff|: 1.97027e-15
Bad results for the following points (in output 0):
         0.0017721911426633596            -0.38366591930389404 =>           0.001772191006114956 !=          0.0017721910061149527  (rdiff         1.8353588897773323e-15)
         0.0022177286446094513            -0.38366591930389404 =>          0.0022177283770131993 !=          0.0022177283770131949  (rdiff         1.9555184191595052e-15)
         0.0074444999918341637            -0.38366591930389404 =>          0.0074444898700397055 !=          0.0074444898700396925  (rdiff         1.7476585094415186e-15)
          0.014336004853248596            -0.38366591930389404 =>           0.014335932572318438 !=           0.014335932572318417  (rdiff         1.4520633106155296e-15)
          0.017609169706702232            -0.38366591930389404 =>           0.017609035755112572 !=           0.017609035755112537  (rdiff         1.9702651526199038e-15)

======================================================================
FAIL: test_boost_data.test_all(<Boost test for exp1 (complex): expint_1_data_ipp-expint_1_data>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/nose-0.10.4-py2.5.egg/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 196, in _test_factory
    test.check(dtype=dtype)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 332, in check
    assert False, "\n".join(msg)
AssertionError:
Max |adiff|: 1.76256e-14
Max |rdiff|: 2.24484e-09
Bad results for the following points (in output 0):
       (9.4190988540649414+0j) =>    (7.8515817802937704e-06+0j) !=         7.8515817979193266e-06  (rdiff         2.2448414456281229e-09)

======================================================================
FAIL: test_boost_data.test_all(<Boost test for expn: expint_data_ipp-expint_data>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/nose-0.10.4-py2.5.egg/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 196, in _test_factory
    test.check(dtype=dtype)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 332, in check
    assert False, "\n".join(msg)
AssertionError:
Max |adiff|: 8.67362e-19
Max |rdiff|: 1.11795e-15
Bad results for the following points (in output 0):
                          18.0              9.4190988540649414 =>         3.0306769539617701e-06 !=         3.0306769539617735e-06  (rdiff          1.117945541700891e-15)

======================================================================
FAIL: test_boost_data.test_all(<Boost test for gammaln: test_gamma_data_ipp-near_2>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib64/python2.5/site-packages/nose-0.10.4-py2.5.egg/nose/case.py", line 182, in runTest
    self.test(*self.arg)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 196, in _test_factory
    test.check(dtype=dtype)
  File "/usr/local/lib64/python2.5/site-packages/scipy/special/tests/test_boost_data.py", line 332, in check
    assert False, "\n".join(msg)
AssertionError:
Max |adiff|: 1.91079e-16
Max |rdiff|: 1.1286e-10
Bad results for the following points (in output 0):
            1.9999923706054688 =>         -3.225569724207844e-06 !=        -3.2255697240167648e-06  (rdiff         5.9238898645735525e-11)
            1.9999961853027344 =>        -1.6127895543505133e-06 !=        -1.6127895545325333e-06  (rdiff         1.1286033463889784e-10)

----------------------------------------------------------------------
Ran 3891 tests in 67.485s

FAILED (KNOWNFAIL=6, SKIP=17, failures=27)
<nose.result.TextTestResult run=3891 errors=0 failures=27>
```

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-09-12
