### ISSUE TITLE
saving large matrices through filters fails (migrated from Trac #1245)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2798]
Original ticket http://projects.scipy.org/numpy/ticket/1245
Reported 2009-10-02 by trac user jap, assigned to unknown.

While trying to save a large matrix through gzip, I got the following error:

```
>>> import numpy
>>> Large_Matrix = numpy.zeros((30000, 30000), dtype=numpy.float32)
>>> import gzip
>>> numpy.save(gzip.open("/tmp/matrix.npy.gz", "w"), Large_Matrix)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/dist-packages/numpy/lib/io.py", line 178, in save
    format.write_array(fid, arr)
  File "/usr/lib/python2.6/dist-packages/numpy/lib/format.py", line 326, in write_array
    fp.write(array.tostring('C'))
SystemError: Negative size passed to PyString_FromStringAndSize
```

Even though this is a python-bug, I'd like to see a workaround in numpy by writing chunks smaller than 2GB. This might also be good for performance of filtered writes.. As I'm going to need this, I'll code this up (shouldn't change the on-disk format), is there any demand for this to be integrated into numpy?

**Comment by thouis** [comment]
Attachment in Trac by trac user jap, 2009-10-02: [numpy-large-matrix-save.diff](http://projects.scipy.org/numpy/attachment/ticket/1245/numpy-large-matrix-save.diff)

**Comment by thouis** [comment]
Comment in Trac by unknown, 2010-09-04

Milestone 1.1.2 deleted
