### ISSUE TITLE
64 Bit Numpy - DLL Load failure (migrated from Trac #1251)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2804]
Original ticket http://projects.scipy.org/numpy/ticket/1251
Reported 2009-10-07 by trac user altiod, assigned to unknown.

Hi, I'm running windows xp with python 64 2.6 bit and 64 bit numpy version 1.3.0 for python 2.6

Program I am using runs correctly in 32 bit python/numpy, but when I use the 64 bit versions I get the following error:

e:\Environ\Python26_64bit\lib\site-packages\numpy\core__init__.py:5: Warning: Windows 64 bits suppo
rt is experimental, and only available for
testing. You are advised not to use it for production.

CRASHES ARE TO BE EXPECTED - PLEASE REPORT THEM TO NUMPY DEVELOPERS
  import multiarray
Traceback (most recent call last):
  File "TestGridWorldChiArm.py", line 1, in <module>
    import numpy
  File "e:\Environ\Python26_64bit\lib\site-packages\numpy__init__.py", line 130, in <module>
    import add_newdocs
  File "e:\Environ\Python26_64bit\lib\site-packages\numpy\add_newdocs.py", line 9, in <module>
    from lib import add_newdoc
  File "e:\Environ\Python26_64bit\lib\site-packages\numpy\lib__init__.py", line 13, in <module>
    from polynomial import *
  File "e:\Environ\Python26_64bit\lib\site-packages\numpy\lib\polynomial.py", line 18, in <module>
    from numpy.linalg import eigvals, lstsq
  File "e:\Environ\Python26_64bit\lib\site-packages\numpy\linalg__init__.py", line 47, in <module>
    from linalg import *
  File "e:\Environ\Python26_64bit\lib\site-packages\numpy\linalg\linalg.py", line 22, in <module>
    from numpy.linalg import lapack_lite
ImportError: DLL load failed: The specified module could not be found.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-07-24

Did you compile it, or was it a specific binary you downloaded? Recent (unofficial) binaries with a lot of 64-bit bugfixes can be found at http://www.lfd.uci.edu/~gohlke/pythonlibs/. Does that work for you?

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-03

I'm guessing this was the experimental installer from David:
http://sourceforge.net/projects/numpy/files/NumPy/1.3.0/numpy-1.3.0.win-amd64-py2.6.msi 

This one was compiled with gcc IIRC, and this was not (yet) successful. Now we don't provide 64-bits Windows installers anymore, they can be obtained from Enthought or from Christoph Gohlke's unofficial package repo.

Not applicable anymore and no more info for >6 months, so closing.
