### ISSUE TITLE
newbyteorder fails on structured arrays with both names and titles (migrated from Trac #1254)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2807]
Original ticket http://projects.scipy.org/numpy/ticket/1254
Reported 2009-10-07 by atmention:mdboom, assigned to atmention:teoliphant.

Creating a newbyteorder of a dtype which contains both a name and title returns the "<err>" dtype.  Using this dtype to create a new array segfaults.

```
   >>> import numpy as np
   >>> x = np.array([(1, 1)], dtype=[(('a', 'a'), 'i'), ('b', 'i')])
   >>> x.dtype.newbyteorder('>')
   dtype(<err>)
   >>> y = np.array(x, dtype=x.dtype.newbyteorder('>'))
   Segmentation fault
```

And here's the backtrace from the segfault

```
[Switching to Thread -1208456544 (LWP 6456)]
0x080d5957 in vgetargs1 (args=0x0, format=0xb7db54 "",  p_va=0xbfe05bd4, flags=Variable "flags" is not available.
)
    at Python/getargs.c:286
286             if (!PyTuple_Check(args)) {
(gdb) bt
#0  0x080d5957 in vgetargs1 (args=0x0, format=0xb7db54 "", p_va=0xbfe05bd4,
    flags=Variable "flags" is not available.
) at Python/getargs.c:286
#1  0x080d5ec5 in _PyArg_ParseTuple_SizeT (args=0xb7db55, format=0xb7db54 "")
    at Python/getargs.c:96
#2  0x00b73092 in VOID_setitem (op=0xb7a9090c, ip=0x8fc8980 "", ap=0x8fa80e8)
    at numpy/core/src/multiarray/arraytypes.c.src:620
#3  0x00b748ce in VOID_to_VOID (ip=0x8fd4838 "\001", op=0x8fc8980 "", n=1,
    aip=0x8ebacd8, aop=0x8fa80e8)
    at numpy/core/src/multiarray/arraytypes.c.src:1392
#4  0x00b53958 in PyArray_CastTo (out=0x8fa80e8, mp=0x8ebacd8)
    at numpy/core/src/multiarray/convert_datatype.c:316
#5  0x00b4ae74 in _array_copy_into (dest=0x8fa80e8, src=0x8ebacd8, usecopy=1)
    at numpy/core/src/multiarray/ctors.c:855
#6  0x00b4be98 in PyArray_FromArray (arr=0x8ebacd8, newtype=0xb7a982f0,
    flags=112) at numpy/core/src/multiarray/ctors.c:2421
#7  0x00b4c3ef in PyArray_FromAny (op=0x8ebacd8, newtype=0xb7a982f0,
    min_depth=0, max_depth=0, flags=112, context=0x0)
    at numpy/core/src/multiarray/ctors.c:1598
#8  0x00b6a60a in PyArray_CheckFromAny (op=0x8ebacd8, descr=0xb7a982f0,
    min_depth=0, max_depth=0, requires=112, context=0x0)
    at numpy/core/src/multiarray/ctors.c:1769
#9  0x00b75fde in _array_fromobject (__NPY_UNUSED_TAGGEDignored=0x0,
    args=0xb7f0a2cc, kws=0xb7a91dfc)
    at numpy/core/src/multiarray/multiarraymodule.c:1478
#10 0x0805d984 in PyObject_Call (func=0xb7db50, arg=0xb7f0a2cc, kw=0xb7a91dfc)
    at Objects/abstract.c:1861
#11 0x080bf804 in PyEval_EvalFrameEx (f=0x8e85dc4, throwflag=0)
    at Python/ceval.c:3784
#12 0x080c43bb in PyEval_EvalCodeEx (co=0xb7eabec0, globals=0xb7f5eacc,
    locals=0xb7f5eacc, args=0x0, argcount=0, kws=0x0, kwcount=0, defs=0x0,
    defcount=0, closure=0x0) at Python/ceval.c:2836
#13 0x080c450a in PyEval_EvalCode (co=0xb7eabec0, globals=0xb7f5eacc,
    locals=0xb7f5eacc) at Python/ceval.c:494
#14 0x080e3e52 in PyRun_InteractiveOneFlags (fp=0xd16720,
    filename=0x811a058 "<stdin>", flags=0xbfe065dc) at Python/pythonrun.c:1273
#15 0x080e4005 in PyRun_InteractiveLoopFlags (fp=0xd16720,
    filename=0x811a058 "<stdin>", flags=0xbfe065dc) at Python/pythonrun.c:723
#16 0x080e4525 in PyRun_AnyFileExFlags (fp=0xd16720,
    filename=0x811a058 "<stdin>", closeit=0, flags=0xbfe065dc)
    at Python/pythonrun.c:692
#17 0x08056d85 in Py_Main (argc=0, argv=0xbfe06714) at Modules/main.c:523
#18 0x08056323 in main (argc=1, argv=0xbfe06714) at ./Modules/python.c:23
```

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-10-14

More info: the name and title of the field must be the same.

**Comment by thouis** [comment]
Comment in Trac by atmention:teoliphant, 2009-12-03

This is a problem with the creation of the dtype when the name and the title fields are the same.   Several places assume that there is an entry for both the name and the title.  When they are the same, two entries do not get created.  There is an implicit assumption that the name and the title are not the same thing. 

This should probably be enforced on dtype creation, by raising an error.

**Comment by thouis** [comment]
Comment in Trac by atmention:teoliphant, 2009-12-04

Fixed in r7870 by raising an error if a duplicate exists --- the pattern previously used (just not in this particular conversion routine).
