### ISSUE TITLE
Failure in genfromtxt tests (python 2.4 & 2.5 only) (migrated from Trac #1257)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2810]
Original ticket http://projects.scipy.org/numpy/ticket/1257
Reported 2009-10-08 by atmention:pv, assigned to atmention:pierregm.

Buildbots are showing this:
    ======================================================================
    FAIL: test_inconsistent_dtype (test_io.TestFromTxt)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/var/lib/buildslave/numpy-real/b15/numpy-install-2.4/lib/python2.4/site-packages/numpy/lib/tests/test_io.py", line 888, in test_inconsistent_dtype
        assert_raises(TypeError, np.genfromtxt, mdata, **kwargs)
      File "../numpy-install-2.4/lib/python2.4/site-packages/numpy/testing/utils.py", line 971, in assert_raises
    AssertionError: TypeError not raised

Does not occur on python2.6, only on 2.4 and 2.5.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-10-08

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2009-10-08

Duly noted. However, I don't have access to numpy on a 2.5/2.4 Python yet: I'm having the same problem as listed in ticket #1221  ("ValueError?: array is too big." on line line 600 of numpy/core/numerictypes.py when importing numpy w/ a 32b Python). Could we get #1221 fixed first ?

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2009-10-12

Should be fixed in r7511. Please confirm so that I can close the ticket. Thank you.
(FYI, it was related to `np.nan` that is convertible to an int in Python2.5 but not in Python2.6)

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2009-11-28

I've checked on 2.4 on Linux.
