### ISSUE TITLE
byteswapping a complex scalar fails (migrated from Trac #1259)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2812]
Original ticket http://projects.scipy.org/numpy/ticket/1259
Reported 2009-10-09 by atmention:mdboom, assigned to unknown.

```
 >>> x = np.array([-1j], '<c8')
 >>> x.tostring().encode('hex')
'00000000000080bf'
# This is a little-endian representation, in the order (real, imag)

# When I swap the whole array, it swaps each of the (real, imag) parts 
separately
 >>> y = x.byteswap()
 >>> y.tostring().encode('hex')
'00000000bf800000'
# and this round-trips fine
 >>> z = np.fromstring(y.tostring(), dtype='>c8')
 >>> assert z[0] == -1j
 >>>

# When I swap the scalar, it seems to swap the entire 8 bytes
 >>> y = x[0].byteswap()
 >>> y.tostring().encode('hex')
'bf80000000000000'
# ...and this doesn't round-trip
 >>> z = np.fromstring(y.tostring(), dtype='>c8')
 >>> assert z[0] == -1j
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
 >>>
```

Travis O. suggested a fix on the mailing list here:

http://www.nabble.com/byteswapping-a-complex-scalar-td25788857.html

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-10-15

Fixed by Travis in r7460, tests in r7537

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-10-19

Regression test fails on Solaris (Sparc):

```
======================================================================
FAIL: Ticket #1259
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mdroe/numpy/numpy/core/tests/test_regression.py", line 1189, in test_byteswap_complex_scalar
    assert_equal(x, np.fromstring(y.tostring(), dtype='>c8'))
  File "/home/mdroe/numpy/build/lib.solaris-2.8-sun4u-2.5/numpy/testing/utils.py", line 246, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/home/mdroe/numpy/build/lib.solaris-2.8-sun4u-2.5/numpy/testing/utils.py", line 675, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/home/mdroe/numpy/build/lib.solaris-2.8-sun4u-2.5/numpy/testing/utils.py", line 607, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 100.0%)
 x: array([ 0.-1.j], dtype=complex64)
 y: array([ 0. +4.61853961e-41j], dtype=complex64)
-------------------- >> begin captured stdout << ---------------------
00000000000080bf
00000000000080bf
```

Interestingly, x.tostring() == y.tostring(), if that offers any clue.  The same is not true on x86 or x86_64.

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-10-19

The reason for the failure is that the value is being swapped twice on big endian platforms.  Once in the explicit call to atmention:atmention:_copyswap from gentype_byteswap, and again inside of the PyArray_Scalar constructor because the dtype of the new scalar is non-native endian.  (byteswap doesn't change the underlying dtype, only the contents of the buffer).  I'm not sure of the best way to solve this problem.  An easy fix would be to only do the swap in gentype_byteswap if PyArray_Scalar isn't going to undo it for us:

```
            if (PyArray_ISNBO(descr->byteorder)) {
                descr->f->copyswap(newmem, data, 1, NULL);
            }
```

But that's not terribly elegant and creates a coupling between gentype_byteswap and PyArray_Scalar.

One can create an analogous failure for little endian platforms as follows (note the source value is now non-native).  So this isn't just a "big endian" bug:

```
        x = np.array([-1j], '>c8')
        y = x[0].byteswap()
        assert_equal(x, np.fromstring(y.tostring(), dtype='<c8'))
```

We should probably test both directions in the unit test.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-10-20

Yep, the problem with the test seems to be that `x[0]` is always native-endian:
    >>> x = np.array([1.234], '>f4')
    >>> x.dtype.byteorder
    '>'
    >>> x[0].dtype.byteorder
    '='
This is a bit surprising to me, but I guess changing those semantics would require more discussion. If we accept this, it is probably no bug, and in any case it's unrelated to this one.

I fixed the test according to status quo in r7574. Please reopen if I made a mess of it again :)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-10-20

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-10-20

The fact is that you still can't (directly) byteswap a scalar from little- to big-endian on a big-endian machine, or big- to little-endian on a little-endian machine, and that's a perfectly reasonable thing to want to do.  I can see that this is changing existing semantics -- but it's changing existing _untested_ semantics (applying my suggested patch doesn't break any existing unit tests), so it might be fair game.  But I agree it's probably a separate bug to the original one here.  I'll open a new one.

**Comment by thouis** [comment]
Comment in Trac by atmention:mdboom, 2009-10-20

Moved over to #1268.
