### ISSUE TITLE
Constructing real arrays with complex numbers leads to funny errors (migrated from Trac #1277)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2830]
Original ticket http://projects.scipy.org/numpy/ticket/1277
Reported 2009-10-28 by atmention:inducer, assigned to unknown.

> > > numpy.array([1j], dtype=numpy.float64)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ValueError: setting an array element with a sequence.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2009-10-29

The error message isn't very informative, but you can't have a complex type in a real array. Either a ValueError or a cast of the complex type should probably take place. My preference would be for a ValueError. OTOH, there is

```
In [1]: array([1.5], dtype=int)
Out[1]: array([1])
```

Which would argue for a cast just to be consistent. But I would prefer an error in this case also.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-25

This is the same issue in #1258. There are inconsistencies here, but they should be dealt with in a different bug.

**Comment by thouis** [comment]
Comment in Trac by atmention:inducer, 2011-03-25

Both issues would go away if there was an error message in this obviously ill-defined operation--which could be phased in by ways of a warning.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-03-25

In the current trunk:
    >>> np.array([1j], dtype=numpy.float64)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: can't convert complex to float
So it seems to be actually fixed, and the error message is more clear than the previous "setting an array element with a sequence".

If there's something more, please reopen again ;)
