### ISSUE TITLE
ERROR: test_simple2 (test_utils.TestArrayAlmostEqualNulp)  (bad format string) (migrated from Trac #1290)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2843]
Original ticket http://projects.scipy.org/numpy/ticket/1290
Reported 2009-11-09 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
ERROR: test_simple2 (test_utils.TestArrayAlmostEqualNulp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/tests/test_utils.py", line 317, in test_simple2
    self.failUnlessRaises(AssertionError, failure)
  File "/usr/stsci/pyssgdev/Python-2.5.4/lib/python2.5/unittest.py", line 320, in failUnlessRaises
    callableObj(*args, **kwargs)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/tests/test_utils.py", line 316, in failure
    nulp=1000)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/utils.py", line 1112, in assert_array_almost_equal_nulp
    "(max is %d)" % (nulp, max_nulp))
TypeError: int argument required
```

Format string does not match args to be printed.

numpy trunk rev 7699

Python 2.5.4

seen on:
- Red Hat Enterprise 4, 32 bit
- Mac OSX Leopard, 32 bit

not seen on:
- Red Hat Enterprise 4, 64 bit

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-11-13

Same as #1297
