### ISSUE TITLE
ERROR: test_nan (test_utils.TestULP) (migrated from Trac #1291)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2844]
Original ticket http://projects.scipy.org/numpy/ticket/1291
Reported 2009-11-09 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
ERROR: test_nan (test_utils.TestULP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/tests/test_utils.py", line 409, in test_nan
    lambda: assert_array_max_ulp(nan, inf,
  File "/usr/stsci/pyssgdev/Python-2.5.4/lib/python2.5/unittest.py", line 320, in failUnlessRaises
    callableObj(*args, **kwargs)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/tests/test_utils.py", line 410, in <lambda>
    maxulp=maxulp))
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/utils.py", line 1121, in assert_array_max_ulp
    maxulp)
TypeError: int argument required

----------------------------------------------------------------------
```

numpy trunk rev 7699

Python 2.5.4

seen on:
- Red Hat Enterprise 4, 32 bit
- Mac OSX Leopard, 32 bit

not seen on:
- Red Hat Enterprise 4, 64 bit

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-11-13

Same as #1297
