### ISSUE TITLE
Unit test failures: some nextafter tests fail on Python2.4/2.5 (migrated from Trac #1297)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2850]
Original ticket http://projects.scipy.org/numpy/ticket/1297
Reported 2009-11-12 by atmention:pv, assigned to atmention:cournape.

The following unit tests fail on Python2.4 and 2.5 (but not on 2.6):
    ======================================================================
    ERROR: test_simple2 (test_utils.TestArrayAlmostEqualNulp)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/var/lib/buildslave/numpy-real/b15/numpy-install-2.5/lib/python2.5/site-packages/numpy/testing/tests/test_utils.py", line 317, in test_simple2
        self.failUnlessRaises(AssertionError, failure)
      File "/usr/lib/python2.5/unittest.py", line 320, in failUnlessRaises
        callableObj(_args, *_kwargs)
      File "/var/lib/buildslave/numpy-real/b15/numpy-install-2.5/lib/python2.5/site-packages/numpy/testing/tests/test_utils.py", line 316, in failure
        nulp=1000)
      File "../numpy-install-2.5/lib/python2.5/site-packages/numpy/testing/utils.py", line 1112, in assert_array_almost_equal_nulp
    TypeError: int argument required

```
======================================================================
ERROR: test_nan (test_utils.TestULP)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/lib/buildslave/numpy-real/b15/numpy-install-2.5/lib/python2.5/site-packages/numpy/testing/tests/test_utils.py", line 370, in test_nan
    lambda: assert_array_max_ulp(nan, inf,
  File "/usr/lib/python2.5/unittest.py", line 320, in failUnlessRaises
    callableObj(*args, **kwargs)
  File "/var/lib/buildslave/numpy-real/b15/numpy-install-2.5/lib/python2.5/site-packages/numpy/testing/tests/test_utils.py", line 371, in <lambda>
    maxulp=maxulp))
  File "../numpy-install-2.5/lib/python2.5/site-packages/numpy/testing/utils.py", line 1121, in assert_array_max_ulp
TypeError: int argument required
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:drnlm, 2009-11-13: [numpy.diff](http://projects.scipy.org/numpy/attachment/ticket/1297/numpy.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:drnlm, 2009-11-13

Both assert_array_max_ulp and assert_array_almost_equal_nulp rely on the '%d' string interpolation truncating non integer values. This behaviour was only introduced in python 2.6.

For the assert_array_almost_equal_nulp failure, max_nulp is clearly never an int, as it's calculated from a float array

For the assert_array_max_ulp failure, it's because one of the tests uses 1e12 for maxulp, which is interpreted as a float.

The attached patch explicitly cast these to int, which is one way of dealing with the problem.

**Comment by thouis** [comment]
Comment in Trac by atmention:drnlm, 2009-11-13

The assert_array_max_ulp is also reported as #1291

The assert_array_almost_equal_nulp failure is also reported as #1290

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-11-13

Thanks, should be fixed in r7734 by changing it to %g.

(I think you meant that floats that can't be represented as integers are not converted to Python longs before %d formatting, and this causes an exception, before Python 2.6.)
