### ISSUE TITLE
Error in 1.4.0rc1 on Python 2.6.4 and Windows: numpy.dtype does not appear to be the correct type object (migrated from Trac #1320)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2873]
Original ticket http://projects.scipy.org/numpy/ticket/1320
Reported 2009-12-08 by atmention:jonovik, assigned to unknown.

Using Numpy 1.4.0rc1 under Windows (XP or 7):

> > > from scipy.stats import chi2
> > > Traceback (most recent call last):
> > > ValueError: numpy.dtype does not appear to be the correct type object

I has this problem on 32-bit Windows XP SP3, whereas this poster had it on 64-bit Windows 7:
http://thread.gmane.org/gmane.comp.python.scientific.user/23108

Another poster suggested to downgrade to Numpy 1.3.0, which fixed the problem in both cases.

I forgot to save the traceback before I downgraded, but the abovementioned Windows 7 user had this:
  File "<stdin>", line 1, in <module>
  File "D:\Python26\lib\site-packages\scipy\stats__init__.py", line
7, in <module>
    from stats import *
  File "D:\Python26\lib\site-packages\scipy\stats\stats.py", line 203,
in <module>
    from morestats import find_repeats #is only reference to scipy.stats
  File "D:\Python26\lib\site-packages\scipy\stats\morestats.py", line
7, in <module>
    import distributions
  File "D:\Python26\lib\site-packages\scipy\stats\distributions.py",
line 27, in <module>
    import vonmises_cython
  File "numpy.pxd", line 30, in scipy.stats.vonmises_cython
(scipy\stats\vonmises_cython.c:2939)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2009-12-08

This is because Numpy's ABI changed in 1.4.0 -- the change was backward compatible, though.

However, Cython makes some very strict checks, which causes these problems. They are resolved by recompiling -- in this case, recompiling Scipy.
