### ISSUE TITLE
Scipy build fails on Mac OS X 10.5.8, Numpy import fails on Mac OS X 10.5.8 (migrated from Trac #1322)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2875]
Original ticket http://projects.scipy.org/numpy/ticket/1322
Reported 2009-12-10 by trac user ndufour, assigned to atmention:cournape.

Mac OS X 10.5.8
32-bit machine
The problem appears to lie with the file "multiarray.so"
Attempting to import Numpy returns:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/**init**.py", line 132, in <module>
    import add_newdocs
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from lib import add_newdoc
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/lib/**init**.py", line 4, in <module>
    from type_check import *
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/lib/type_check.py", line 8, in <module>
    import numpy.core.numeric as _nx
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/__init__.py", line 5, in <module>
    import multiarray
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so, 2): no suitable image found.  Did find:
    /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so: unknown required load command 0x80000022

Attempting to build Scipy returns:

Traceback (most recent call last):
  File "setup.py", line 160, in <module>
    setup_package()
  File "setup.py", line 127, in setup_package
    from numpy.distutils.core import setup
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/**init**.py", line 132, in <module>
    import add_newdocs
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from lib import add_newdoc
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/lib/**init**.py", line 4, in <module>
    from type_check import *
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/lib/type_check.py", line 8, in <module>
    import numpy.core.numeric as _nx
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/__init__.py", line 5, in <module>
    import multiarray
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so, 2): no suitable image found.  Did find:
    /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so: unknown required load command 0x80000022

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2009-12-10

What version of Numpy? Architecture? There is a new release in the works that should come out in a week or two, it would be helpful if you tested the release candidates. Go to www.scipy.org to track these, look at the right side bar.

**Comment by thouis** [comment]
Comment in Trac by trac user nvawter, 2009-12-15

Hi, I can reproduce this bug.  

My numpy version is: numpy-1.4.0rc1-py2.6-python.org-1.dmg, downloaded from http://sourceforge.net/projects/numpy/files/

I first saw the failure when I tried to "import numpy".  Essentially identical message to the above atmention:dlopen.  At that point, I was running OSX 10.5.1 and python 2.6.2.  Then I upgraded to python 2.6.4, and OSX 10.5.8.  The error message was virtually identical.  

Here's my error message.  Thank you for looking into this :)

/Library/WebServer/CGI-Executables>python
Python 2.6.4 (r264:75821M, Oct 27 2009, 19:48:32) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

> > > import numpy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/**init**.py", line 132, in <module>
> > >     import add_newdocs
> > >   File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/add_newdocs.py", line 9, in <module>
> > >     from lib import add_newdoc
> > >   File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/lib/**init**.py", line 4, in <module>
> > >     from type_check import *
> > >   File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/lib/type_check.py", line 8, in <module>
> > >     import numpy.core.numeric as _nx
> > >   File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/__init__.py", line 5, in <module>
> > >     import multiarray
> > > ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so, 2): no suitable image found.  Did find:
> > >     /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so: unknown required load command 0x80000022

Library/WebServer/CGI-Executables>file /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so
/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so: Mach-O universal binary with 2 architectures
/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so (for architecture ppc7400):  Mach-O bundle ppc
/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so (for architecture i386): Mach-O bundle i386
/Library/WebServer/CGI-Executables>uname
Darwin
/Library/WebServer/CGI-Executables>uname -a
Darwin dhcp-18-111-92-239.dyn.mit.edu 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386
/Library/WebServer/CGI-Executables>

**Comment by thouis** [comment]
Comment in Trac by trac user ansobol, 2009-12-16

Replying to [comment:1 charris]:

> What version of Numpy? Architecture? There is a new release in the works that should come out in a week or two, it would be helpful if you tested the release candidates. Go to www.scipy.org to track these, look at the right side bar.

I'd like to confirm that on my system I see exactly the same error message as nvawter.

!NumPy version 1.4.0rc1, downloaded from !SourceForge

Python version 2.6.4

Architecture i386

Mac OS X version 10.5.8 build 9L30

**Comment by thouis** [comment]
Comment in Trac by trac user alxndr, 2009-12-22

Same error over here, on the same setup...

NumPy 1.4.0rc1[[BR]]
Python 2.6.4[[BR]]
OS X 10.5.8

$ uname -a[[BR]]
Darwin ... 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386

**Comment by thouis** [comment]
Comment in Trac by trac user ansobol, 2009-12-28

Hi,

I have just downloaded !NumPy version 1.4.0rc2.  It gives exactly the same error message as RC1, on the same system configuration.

Andrei

**Comment by thouis** [comment]
Comment in Trac by trac user ansobol, 2010-01-01

After an upgrade to Snow Leopard (version 10.6.2, build 10C540; Python 2.6.4) this error seems to be gone: for !NumPy 1.4.0rc2 I was able to import numpy successfully both before and after (re)installation of Xcode tools that come with Snow Leopard.

**Comment by thouis** [comment]
Comment in Trac by trac user resolve, 2010-01-19

Same issue here, and unfortunately upgrading to Snow Leopard is not an option at the moment. Adding a CC to track this.

**Comment by thouis** [comment]
Comment in Trac by trac user resolve, 2010-01-19

(reverting to 1.3 seems to have solved the problem for now)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-06-02

How about the 1.4.1 release, can you try if that is still failing for you?

**Comment by thouis** [comment]
Comment in Trac by trac user resolve, 2010-06-02

I'll look into it when I build the next release of my project - might take a while to get back to you.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-07-30

The first beta for 1.5.0 should be available by this Sunday night, please try it and let me know if this is still an issue - this would be an important issue to fix for the next release.

**Comment by thouis** [comment]
Comment in Trac by trac user resolve, 2010-07-30

I'm afraid I had to upgrade to 10.6 for other reasons, so I am no longer able to test this.

**Comment by thouis** [comment]
Comment in Trac by trac user collord, 2010-09-05

On 10.5.8, with python 2.7 from python.org, numpy-1.5.0-py2.7 gives the same error.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-09-07

Reformatting the first comment for readability:
    Library/WebServer/CGI-Executables>file /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so 

```
/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so: Mach-O universal binary with 2 architectures 
/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so (for architecture ppc7400): Mach-O bundle ppc 
/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so (for architecture i386): Mach-O bundle i386 

/Library/WebServer/CGI-Executables>uname
Darwin 
/Library/WebServer/CGI-Executables>uname -a
Darwin dhcp-18-111-92-239.dyn.mit.edu 9.8.0 Darwin Kernel Version 9.8.0: Wed Jul 15 16:55:01 PDT 2009; root:xnu-1228.15.4~1/RELEASE_I386 i386 
/Library/WebServer/CGI-Executables> 
```

I've looked into this some more and found a large amount of reports with the same problem - no solution. The issue seems to that binaries compiled on 10.6 simply fail to load on 10.5 despite the correct SDK being used (10.4 in this case, I checked all individual files in the build log). I think this problem first started occurring when David C. upgraded his machine to Snow Leopard before 1.4.0.

One of the most complete threads about this I found is http://web.archiveorange.com/archive/v/JT06FFoTBH5HKDgJ9T5X. At the end there is a report that including a compile flag {{{-mmacosx-version-min=10.4}}} helps. Will give that a try when I find the time.

The only safe way to go though, as far as I can tell, is what Sage does: provide separate binaries for each version of OS X, built on that same OS version.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-09-07

Please try numpy-2.0.0.dev-py2.6-osx10.5-python.org.dmg, the newest file on http://sourceforge.net/projects/numpy/files/. It's compiled with {{{-mmacosx-version-min=10.4}}}.

Also, I'd like to see the result of
    $ otool -l /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.s
both for the 1.5.0 binary and the one mentioned above.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-09-15

Anyone?

That installer doesn't really belong on SF, I just don't have a permanent home for it. So please give it a try within a few days or so.

**Comment by thouis** [comment]
Comment in Trac by trac user PeterR, 2010-09-29

I am using 10.5.7 and have this exact same issue. 
I tried numpy-2.0.0.dev-py2.6-osx10.5-python.org.dmg and there is no change.
The check for multiarray.s retruns a file not found, inspecting the directory shows it contains multiarray.so
and multiarray_tests.so but no multiarray.s

hope this helps...

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-09-29

Thanks for testing. For your comment on checking for multiarray.s (instead of .so), I see I made a copy-paste error above, in the {{{$ otool -l ...}}} line I meant {{{.so}}} of course. It's the output of the {{{otool -l}}} on multiarray.so that I was interested in.
    /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/multiarray.so: unknown required load command 0x80000022 

I think the conclusion is that 10.5 binaries should be compiled on 10.5, no way around it. I'll remove the binary from SF again.

**Comment by thouis** [comment]
Comment in Trac by trac user registrar, 2010-10-15

Did this ever get resolved?  I am currently to install NumPy on Mac OS 10.5.8, but having no luck at all.

I would love to try using numpy-2.0.0.dev-py2.6-osx10.5-python.org.dmg if that is still available.  

Any other thoughts?  Upgrading to Mac OS 10.6 is not an option unless I replace my chipset

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-16

It is about to be resolved - a MacBook running 10.5 to build the installers was just set up this week. The first release candidate for numpy 1.5.1 will be tagged tomorrow, and that should have working binaries for 10.5.

**Comment by thouis** [comment]
Comment in Trac by trac user registrar, 2010-10-16

That's fantastic.  Those of us on legacy hardware appreciate the diligence.  Will it be architecture-agnostic?  (I have only a PowerPC mac)

Thanks very much.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-16

Yep, should be the same as the python.org binaries, so i386/ppc bundles.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-20

A new build machine running 10.5 was just set up, thanks to Vincent Davis and Friedrich Romstedt.

I just uploaded a new dmg built on it to SF (python 2.6 only). Full name is {{{numpy-1.5.1rc1-py2.6-python.org-macosx10.3.dmg}}}, md5 bc7900771e58fbdc45e5918b0698f663. Please try it out.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-11-15

Anyone tried the 1.5.1rc2 binaries that are up now on SF? They were built on 10.5 and seem to install fine on both Intel and PPC 10.5 machines.

**Comment by thouis** [comment]
Comment in Trac by trac user sarahk, 2010-11-29

I get exactly the same bug on my iMac, running Mac OSX 10.6.5, python 2.7 and trying to import numpy 1.5.1. I used the dmg numpy-1.5.1-py2.7-python.org-macosx10.3.dmg. Any advice?

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-11-29

Are you sure you installed the matching version of Python itself from python.org? So the dmg ending in 10.3, not 10.5?

You can check with
    $ file /Library/Frameworks/Python.framework/Versions/2.7/Python
it should say 
    /Library/Frameworks/Python.framework/Versions/2.7/Python: Mach-O universal binary with 2 architectures
    /Library/Frameworks/Python.framework/Versions/2.7/Python (for architecture ppc):    Mach-O dynamically linked shared library ppc
    /Library/Frameworks/Python.framework/Versions/2.7/Python (for architecture i386):   Mach-O dynamically linked shared library i386

**Comment by thouis** [comment]
Comment in Trac by trac user sarahk, 2010-11-29

returns:

```
/Library/Frameworks/Python.framework/Versions/2.7/Python: Mach-O universal binary with 3 architectures
/Library/Frameworks/Python.framework/Versions/2.7/Python (for architecture i386):   Mach-O dynamically linked shared library i386
/Library/Frameworks/Python.framework/Versions/2.7/Python (for architecture ppc7400):    Mach-O dynamically linked shared library ppc
/Library/Frameworks/Python.framework/Versions/2.7/Python (for architecture x86_64): Mach-O 64-bit dynamically linked shared library x86_64
```

Yeah, the python dmg I used ends in 10.5, not 10.3. Will try again.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-11-30

The new installers for 1.5.1 were compiled on OS X 10.5. They were tested successfully on both PPC and Intel 10.5 systems, so I think this issue is fixed.
