### ISSUE TITLE
FAIL: Test generic loops. (migrated from Trac #1323)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2876]
Original ticket http://projects.scipy.org/numpy/ticket/1323
Reported 2009-12-11 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
FAIL: Test generic loops.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_ufunc.py", line 86, in test_generic_loops
    assert_almost_equal(fone(x), fone_val, err_msg=msg)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/utils.py", line 434, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal PyUFunc_F_F
 ACTUAL: array([ 0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j,  0.+0.j], dtype=complex64)
 DESIRED: 1
```

Python 2.5.4

Red Hat Enterprise Linux 4, 64 bit

Not on RHE 4, 32 bit.  Not on Mac OSX Leopard, 32 bit python.  Not on RHE 5, 64 bit.  Not on Solaris 8, 32 bit python.

NumPy version 1.5.0.dev7996

**Comment by thouis** [comment]
Comment in Trac by atmention:chanley, 2010-02-17

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-25

This is calling np.exp on x = np.zeros(10, dtype=np.csingle)[0::2], so for some reason np.exp is failing with a complex input.

**Comment by thouis** [comment]
Comment in Trac by atmention:bsouthey, 2011-05-12

I used a self-compiled Python 2.5.5 (GCC 4.5.1 20100924 (Red Hat 4.5.1-4)) but I could not verify this with either numpy 1.5.0 or 1.5.1 on Fedora 14 64-bit with nose 0.11.2. All the tests pass and example also works (below for both numpy versions).

Based on the very similar ticket 1325, this may be gcc version. Ticket 1324 also seems related.

```
$ python2.5
Python 2.5.5 (r255:77872, Nov  8 2010, 09:10:42) 
[GCC 4.5.1 20100924 (Red Hat 4.5.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.5.1'
>>> x = np.zeros(10, dtype=np.csingle)[0::2]
>>> np.exp(x)
array([ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j], dtype=complex64)


$ python2.5
Python 2.5.5 (r255:77872, Nov  8 2010, 09:10:42) 
[GCC 4.5.1 20100924 (Red Hat 4.5.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.5.0'
>>> x = np.zeros(10, dtype=np.csingle)[0::2]
>>> np.exp(x)
array([ 1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j,  1.+0.j], dtype=complex64)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2011-05-23

I can only make it happen on RHE 4 on 64 bits.  This machine says:

```
thor 1% gcc --version
gcc (GCC) 3.4.6 20060404 (Red Hat 3.4.6-11)
Copyright (C) 2006 Free Software Foundation, Inc.
```

I only have a few RHE 4 machines left, so if you're really confident that it is a compiler bug (rather than a numpy bug that just happens to get masked most of the time), then I wouldn't worry about it.  Otherwise, if you want to provide some test/debug code with instructions, I can run it for you.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-05-23

It may be a bug. Can you determine if the cexpf called is in the gcc library or is it the numpy version?

Hmm, looks like gcc now has a library for quad precision. Needs looking into since we will need to deal with that someday.
