### ISSUE TITLE
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex64'>,) (migrated from Trac #1324)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2877]
Original ticket http://projects.scipy.org/numpy/ticket/1324
Reported 2009-12-11 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
FAIL: test_umath.TestComplexFunctions.test_loss_of_precision(<type 'numpy.complex64'>,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_umath.py", line 721, in check_loss_of_precision
    check(x_basic, 2*eps/1e-3)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_umath.py", line 691, in check
    'arcsinh')
AssertionError: (0, 0.0010023052, 0.9987238, 'arcsinh')
```

Python 2.5.4

Red Hat Enterprise Linux 4, 64 bit 

Not on RHE 4, 32 bit.  Not on Mac OSX Leopard, 32 bit python.  Not on RHE 5, 64 bit. (!)

NumPy version 1.5.0.dev7996

This appears to be similar to #1113, but I'm first seeing it this week and that ticket is 7 months old.

**Comment by thouis** [comment]
Comment in Trac by atmention:chanley, 2010-02-17
