### ISSUE TITLE
FAIL: test_umath.TestComplexFunctions.test_precisions_consistent (migrated from Trac #1325)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2878]
Original ticket http://projects.scipy.org/numpy/ticket/1325
Reported 2009-12-11 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
FAIL: test_umath.TestComplexFunctions.test_precisions_consistent
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_umath.py", line 602, in test_precisions_consistent
    assert_almost_equal(fcf, fcd, decimal=6, err_msg='fch-fcd %s'%f)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/utils.py", line 434, in assert_almost_equal
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal fch-fcd <ufunc 'arcsin'>
 ACTUAL: 2.3561945j
 DESIRED: (0.66623943249251527+1.0612750619050355j)
```

Python 2.5.4

Red Hat Enterprise Linux 4, 64 bit

Not on RHE 4, 32 bit.  Not on Mac OSX Leopard, 32 bit python.  Not on RHE 5, 64 bit.  Not on Solaris 8, 32 bit python.

NumPy version 1.5.0.dev7996

**Comment by thouis** [comment]
Comment in Trac by atmention:chanley, 2010-02-17

**Comment by thouis** [comment]
Comment in Trac by trac user csernazs, 2011-03-02

I also have the same problem. I'm able to reproduce it, see the attached script.

If you execute the script, you will see a line with the function and the value, and three lines below, printing the result of the function called by converting the value to csingle, cdouble, clongdouble.

Surprisingly, the result of the function is constant (eg. not depends on the parameter) if called by a csingle value, that is 2.35619j.

It fails only on linux hosts, on windows if I install the provided binary it's ok.
I've compiled it with and without mkl, and I have the same error in both cases.

I have a 64-bit python interpreter:

Python 2.6.4 (r264:75706, Feb  9 2010, 11:07:13)
[GCC 3.4.5 20051201 (Red Hat 3.4.5-2)] on linux2

And I'm using numpy 1.5.1.

**Comment by thouis** [comment]
Attachment in Trac by trac user csernazs, 2011-03-02: [test_numpy.py](http://projects.scipy.org/numpy/attachment/ticket/1325/test_numpy.py)

**Comment by thouis** [comment]
Comment in Trac by trac user csernazs, 2011-03-02

Update: compiling with gcc 4.x fixes the bug.
