### ISSUE TITLE
FAIL: test_buffer_hashlib (test_regression.TestRegression) (migrated from Trac #1326)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2879]
Original ticket http://projects.scipy.org/numpy/ticket/1326
Reported 2009-12-11 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
FAIL: test_buffer_hashlib (test_regression.TestRegression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_regression.py", line 1255, in test_buffer_hashlib
    assert_equal(md5(x).hexdigest(), '2a1dd1e1e59d0a384c26951e316cd7e6')
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/utils.py", line 305, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: '1264d4a9f74dc462700fd163e3ff09a6'
 DESIRED: '2a1dd1e1e59d0a384c26951e316cd7e6'

----------------------------------------------------------------------
```

Python 2.5.4, 32 bit executable

Solaris 8

Not on Red Hat Enterprise Linux, 4 / 32 bit.  Not on RHE 4 / 64 bit.  Not on RHE 5 / 64 bit.  Not on Mac OSX Leopard, 32 bit python.

(That is, failing on the big-endian SPARC, passing on a bunch of x86 systems.)

NumPy version 1.5.0.dev7996

**Comment by thouis** [comment]
Comment in Trac by atmention:drnlm, 2010-01-20

Given that:

> > > x = np.array([1,2,3], dtype=np.dtype('<i4'))
> > > md5.new(x).hexdigest()
> > > '2a1dd1e1e59d0a384c26951e316cd7e6'
> > > 
> > > x = np.array([1,2,3], dtype=np.dtype('>i4'))
> > > md5.new(x).hexdigest()
> > > '1264d4a9f74dc462700fd163e3ff09a6'

It really looks like the test should specify the correct byte order.

**Comment by thouis** [comment]
Comment in Trac by atmention:drnlm, 2010-01-20

Trivial patch using np.dtype('<i4')

**Comment by thouis** [comment]
Attachment in Trac by atmention:drnlm, 2010-01-21: [1326_patch.diff](http://projects.scipy.org/numpy/attachment/ticket/1326/1326_patch.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-02-14

Patch applied in r8110.
