### ISSUE TITLE
ImportError from umath.so on OSX 10.6 (migrated from Trac #1343)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2896]
Original ticket http://projects.scipy.org/numpy/ticket/1343
Reported 2009-12-21 by atmention:fonnesbeck, assigned to unknown.

For the past several weeks, I have been unable to build a working version of Numpy from svn checkout on 64-bit Python on OSX 10.6. The build itself is successful, but the resulting package gives an import error:
## In [1]: import numpy

Traceback (most recent call last):
  File "<ipython console>", line 1, in <module>
  File "/Library/Python/2.6/site-packages/numpy-1.5.0.dev-py2.6-macosx-10.6-universal.egg/numpy/**init**.py", line 132, in <module>
    import add_newdocs
  File "/Library/Python/2.6/site-packages/numpy-1.5.0.dev-py2.6-macosx-10.6-universal.egg/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/Library/Python/2.6/site-packages/numpy-1.5.0.dev-py2.6-macosx-10.6-universal.egg/numpy/lib/**init**.py", line 4, in <module>
    from type_check import *
  File "/Library/Python/2.6/site-packages/numpy-1.5.0.dev-py2.6-macosx-10.6-universal.egg/numpy/lib/type_check.py", line 8, in <module>
    import numpy.core.numeric as _nx
  File "/Library/Python/2.6/site-packages/numpy-1.5.0.dev-py2.6-macosx-10.6-universal.egg/numpy/core/__init__.py", line 6, in <module>
    import umath
ImportError: dlopen(/Library/Python/2.6/site-packages/numpy-1.5.0.dev-py2.6-macosx-10.6-universal.egg/numpy/core/umath.so, 2): Symbol not found: _npy_cexp
  Referenced from: /Library/Python/2.6/site-packages/numpy-1.5.0.dev-py2.6-macosx-10.6-universal.egg/numpy/core/umath.so
  Expected in: flat namespace
 in /Library/Python/2.6/site-packages/numpy-1.5.0.dev-py2.6-macosx-10.6-universal.egg/numpy/core/umath.so

This has been occurring since at least rev 7726. Here is my build script:
    #!/bin/sh
    export MACOSX_DEPLOYMENT_TARGET=10.6
    export CFLAGS="-arch i386 -arch x86_64"
    export FFLAGS="-m32 -m64"
    export LDFLAGS="-Wall -undefined dynamic_lookup -bundle -arch i386 -arch x86_64"
    export PYTHONPATH="/Library/Python/2.6/site-packages/"
    python setupegg.py config_fc --fcompiler gfortran config -L/Users/fonnesbeck/Code/libs build bdist_egg
Following a suggestion, I have also tried without setting LDFLAGS, but the same result occurs. Here is the config.h that is generated, if that helps:

http://files.me.com/fonnesbeck/d9eyxi

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-07-18

Is this still a problem? If so, do the instructions at http://www.scipy.org/Installing_SciPy/Mac_OS_X work for you? Why specify all these flags by hand?

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-07-28

Also, default build with Python 2.7 is now 64-bit.

If there is actually something to fix, it would be good to get it into numpy 1.5. First beta is planned for this Sunday.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-07-30

Someone on the mailing list just pointed out http://stronginference.com/scipy-superpack/. I assume that means everything works for you again?

**Comment by thouis** [comment]
Comment in Trac by atmention:fonnesbeck, 2010-07-30

I have a newer machine now, and this problem seems to have disappeared. I never did get it working on my 2008 MacBook Pro, with what I believe to be the same setup.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-07-30

Hmm, something must have been fixed, or it was a hardware problem. My (Intel) iMac is from 2007 and your build script works fine for me.

Closing this issue, if it reoccurs please reopen.
