### ISSUE TITLE
ERROR: Test filled w/ mvoid (migrated from Trac #1346)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2899]
Original ticket http://projects.scipy.org/numpy/ticket/1346
Reported 2009-12-31 by atmention:stsci-sienkiew, assigned to unknown.

```
ERROR: Test filled w/ mvoid
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/ma/tests/test_core.py", line 506, in test_filled_w_mvoid
    a = mvoid(np.array((1, 2)), mask=[(0, 1)], dtype=ndtype)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/ma/core.py", line 5454, in __new__
    _data = ndarray.__new__(self, (), dtype=dtype, buffer=data.data)
TypeError: buffer is too small for requested array

----------------------------------------------------------------------
```

NumPy version 1.5.0.dev8039

Python 2.5.4

happens on:  Red Hat Enterprise 4 32 bit, Solaris 32 bit, Mac OSX Leopard 32 bit

does not happen on: RHE 4 64 bit, RHE 5 64 bit

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-01-06

The problem looks to be this line in test_core.py

```
        a = mvoid(np.array((1, 2)), mask=[(0, 1)], dtype=ndtype)
```

Note that the array has room for two integers, but the flexible type needs room for an integer and a float. On 64 bit systems with 64 bit integers this is not a problem, but when the integers are 32 bits...

Printing also fails with mvoid instances and it is not generally correct for **str** and **repr** to be the same.

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-02-08
- The invalid test should be fixed in r8095
- Printing should now work
- Let me know what you think of the repr/str before I close the ticket
