### ISSUE TITLE
Error when calling argsort on masked array (migrated from Trac #1349)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2902]
Original ticket http://projects.scipy.org/numpy/ticket/1349
Reported 2010-01-06 by trac user pschella, assigned to atmention:pierregm.

When calling argsort on a masked array the following error is produced:

Traceback (most recent call last):
  File "argsort_error.py", line 13, in <module>
    print np.argsort(x) # error
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/fromnumeric.py", line 573, in argsort
    return argsort(axis, kind, order)
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/ma/core.py", line 4034, in argsort
    return d.argsort(axis=axis, kind=kind, order=order)
TypeError: expected string or Unicode object, NoneType found

**Comment by thouis** [comment]
Attachment in Trac by trac user pschella, 2010-01-06: [argsort_error.py](http://projects.scipy.org/numpy/attachment/ticket/1349/argsort_error.py)

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-01-06

Confirmed. I'll work on it. Meanwhile, you can use np.ma.argsort

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-01-06

Should be fixed in r8040. Please give a try and report back. Thanks!

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-09-13

No comment for a while, I assume that everything's fine. Closing.

**Comment by thouis** [comment]
Comment in Trac by trac user pschella, 2010-09-13

Sorry about the slow response (reply got caught by my spamfilter), bug
is indeed gone in version 1.5.
