### ISSUE TITLE
repr for string item within array of dtype object is missing quotes (migrated from Trac #1361)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2914]
Original ticket http://projects.scipy.org/numpy/ticket/1361
Reported 2010-01-13 by atmention:yarikoptic, assigned to unknown.

In numpy version shipped with Debian
    $> python -c "from numpy import *; print **version**; r=repr(array(['s', None])); print r; eval(r)"
    1.3.0
    array([s, None], dtype=object)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<string>", line 1, in <module>
    NameError: name 's' is not defined
as well as current trunk
    $> python -c "from numpy import *; print **version**; r=repr(array(['s', None])); print r; eval(r)"
    1.5.0.dev
    array([s, None], dtype=object)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "<string>", line 1, in <module>
    NameError: name 's' is not defined

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-01-14

I suspect this is related to the fact that repr on arrays calls str on the elements rather than repr.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-01-14

Oops, looks like repr is called on the arguments. Hmm...
