### ISSUE TITLE
test_core.TestMaskedView fails with python2.4 (migrated from Trac #1367)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2920]
Original ticket http://projects.scipy.org/numpy/ticket/1367
Reported 2010-01-21 by atmention:drnlm, assigned to unknown.

Seen on both Linux i386 with python 2.4.6 and Linux sparc with python 2.4.4. Not seen with python 2.5

```
======================================================================
ERROR: test_view_to_flexible_dtype (test_core.TestMaskedView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neil/Trees/Numpy_svn/install2.4/lib/python2.4/site-packages/numpy/ma/tests/test_core.py", line 3313, in test_view_to_flexible_dtype
    test = a[0].view([('A', float), ('B', float)])
  File "../install2.4/lib/python2.4/site-packages/numpy/ma/core.py", line 2862, in view
  File "../install2.4/lib/python2.4/site-packages/numpy/ma/core.py", line 2786, in __array_finalize__
TypeError: attribute 'shape' of 'numpy.generic' objects is not writable

======================================================================
ERROR: test_view_to_subdtype (test_core.TestMaskedView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/neil/Trees/Numpy_svn/install2.4/lib/python2.4/site-packages/numpy/ma/tests/test_core.py", line 3334, in test_view_to_subdtype
    test = a[0].view((float, 2))
  File "../install2.4/lib/python2.4/site-packages/numpy/ma/core.py", line 2862, in view
  File "../install2.4/lib/python2.4/site-packages/numpy/ma/core.py", line 2786, in __array_finalize__
TypeError: attribute 'shape' of 'numpy.generic' objects is not writable

----------------------------------------------------------------------
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:drnlm, 2010-01-25: [1367_patch.diff](http://projects.scipy.org/numpy/attachment/ticket/1367/1367_patch.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:drnlm, 2010-01-25

It looks like python 2.4 raises a TypeError rather than a AttributeError when shape is void. The attached patch catches both, so the tests pass.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-02-07

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-04-05

There hasn't been any other failure report, I consider the bug fixed.
