### ISSUE TITLE
numpy.load() crashes on invalid data (migrated from Trac #1370)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2923]
Original ticket http://projects.scipy.org/numpy/ticket/1370
Reported 2010-01-21 by trac user dhelfman, assigned to unknown.

```
>>> import cStringIO as io
>>> import numpy as np
>>> np.load( io.StringIO( '0' ) )
```

When I run this, the Python interpreter crashes and exits unceremoniously. Note that if I change the '0' to a '1', I get a proper IOError exception and no crash.

This is in MSYS on Windows XP with Python 2.6.4 from python.org, running numpy 1.4.0 built with MSVC 9.0:

```
$ gdb python
GNU gdb 5.2.1
Copyright 2002 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i686-pc-mingw32"...(no debugging symbols found)...
(gdb) r -c "import cStringIO as IO ; import numpy as np ; np.load( IO.StringIO('0') )"
Starting program: c:\python26/python.exe -c "import cStringIO as io ; import numpy as np ; np.load( io.StringIO('0') )"

Program received signal SIGSEGV, Segmentation fault.
0x1e09ada3 in ?? ()
(gdb) bt
#0  0x1e09ada3 in ?? ()
#1  0x1e0e1fd5 in ?? ()
#2  0x00a4e530 in ?? ()
#3  0x1e1d1d30 in ?? ()
Cannot access memory at address 0x5
```

And this is on Mac OS X 10.4 with Python 2.6.4 from python.org, running numpy 1.4.0 built with gcc 4.0.1 from Apple:

```
$ gdb python
GNU gdb 5.2.1
Copyright 2002 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i686-pc-mingw32"...(no debugging symbols found)...
(gdb) r -c "import cStringIO as IO ; import numpy as np ; np.load( IO.StringIO('0') )"
Starting program: c:\python26/python.exe -c "import cStringIO as IO ; import numpy as np ; np.load( IO.StringIO('0') )"

Program received signal SIGSEGV, Segmentation fault.
0x1e09ada3 in ?? ()
(gdb) bt
#0  0x1e09ada3 in ?? ()
#1  0x1e0e1fd5 in ?? ()
#2  0x00a4e530 in ?? ()
#3  0x1e1d1d30 in ?? ()
Cannot access memory at address 0x5
```

**Comment by thouis** [comment]
Comment in Trac by trac user dhelfman, 2010-01-21

Interestingly, this code does not appear to crash numpy 1.2.x or 1.3.x.

**Comment by thouis** [comment]
Comment in Trac by trac user dhelfman, 2010-01-21

Oops, the Mac version of the backtrace should be:

```
$ gdb python
GNU gdb 6.3.50-20050815 (Apple version gdb-962) (Sat Jul 26 08:14:40 UTC 2008)
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "i386-apple-darwin"...Reading symbols for shared libraries .. done

(gdb) r -c "import cStringIO as io ; import numpy as np ; np.load( io.StringIO('0') )"
Starting program: /System/Library/Frameworks/Python.framework/Versions/2.6/bin/python -c "import cStringIO as io ; import numpy as np ; np.load( io.StringIO('0') )"
Reading symbols for shared libraries +. done

Program received signal SIGTRAP, Trace/breakpoint trap.
0x8fe01010 in __dyld__dyld_start ()
(gdb) bt
#0  0x8fe01010 in __dyld__dyld_start ()
Cannot access memory at address 0x4
```

**Comment by thouis** [comment]
Comment in Trac by trac user ChrisBarker, 2010-01-21

Just a note:

It does not crash with numpy 1.3, Python2.5.4, OS-PPC python.org build.

Perhaps a bug introduced in numpy 1.4

**Comment by thouis** [comment]
Comment in Trac by trac user ChrisBarker, 2010-01-21

Note 2:

nor does is crash with numpy1.4, Python2.6, OS-X 10.4.11, PPC:

```
Python 2.6 (trunk:66714:66715M, Oct  1 2008, 18:36:04) 
[GCC 4.0.1 (Apple Computer, Inc. build 5370)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.4.0'
>>> 
>>> import cStringIO as io
>>> np.load( io.StringIO( '0' ) )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/lib/io.py", line 301, in load
    "Failed to interpret file %s as a pickle" % repr(file)
IOError: Failed to interpret file <cStringIO.StringI object at 0xf500> as a pickle
>>> 
```

maybe an endian difference?

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-01-22

It's a bug in Python:
    >>> import cPickle as pickle
    >>> import cStringIO as io
    >>> pickle.load(io.StringIO('0'))
numpy.load is a thin wrapper for cPickle.

**Comment by thouis** [comment]
Comment in Trac by trac user dhelfman, 2010-01-22

Filed as a Python bug at: http://bugs.python.org/issue7758
