### ISSUE TITLE
mvoid.__str__ fails with python2.4 (migrated from Trac #1373)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2926]
Original ticket http://projects.scipy.org/numpy/ticket/1373
Reported 2010-01-25 by atmention:drnlm, assigned to unknown.

The following code fragment
    import numpy as np
    from numpy.ma.core import array, mvoid
    ndtype = [('a', int), ('b', float)]
    a = mvoid(np.array((1.0, 2.0, 3.0, 4.0)), mask=(0, 1), dtype=ndtype)
    str(a)

works fine with python2.5, but fails with python2.4

```
Traceback (most recent call last):
  File "./demo2.py", line 6, in ?
    str(a)
  File "/home/neil/Trees/Numpy_svn/install2.4/lib/python2.4/site-packages/numpy/ma/core.py", line 5470, in __str__
    r = [(str(_), p)[_m] for (_, _m) in zip(self._data.tolist(), tuple(m))]
TypeError: tuple indices must be integers
```

In 2.4, numpy.bool_ isn't converted to an appropriate type for use as an index. The attached patch adds an explicit cast to int to solve this.

**Comment by thouis** [comment]
Attachment in Trac by atmention:drnlm, 2010-01-25: [ma_tuple.diff](http://projects.scipy.org/numpy/attachment/ticket/1373/ma_tuple.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:drnlm, 2010-01-25

**Comment by thouis** [comment]
Comment in Trac by atmention:drnlm, 2010-02-08

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-03-18

That should be fixed in r8295. Can you check and report back ? Thanks

**Comment by thouis** [comment]
Comment in Trac by atmention:drnlm, 2010-03-26

Works fine here. Thanks.

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-03-26

OK. Closing the ticket.
