### ISSUE TITLE
distutils fails to build ppc64 support on Mac OS X when requested (migrated from Trac #1399)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2952]
Original ticket http://projects.scipy.org/numpy/ticket/1399
Reported 2010-02-18 by atmention:dwf, assigned to atmention:rgommers.

Stuff including Fortran code ends up missing the ppc64 architecture even when Python supports it, due to a small oversight in the detection code. Patch attached.

**Comment by thouis** [comment]
Attachment in Trac by atmention:dwf, 2010-02-18: [gfortran-osx-ppc64.patch](http://projects.scipy.org/numpy/attachment/ticket/1399/gfortran-osx-ppc64.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-06-02

Applied in r8453. Thanks David.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-09-26

This wasn't the right fix - it can break compilation of scipy when ppc64 is not available. The issue is that _can_target() checks if the arch is supported, but not if Python supports it too. So you end up with a missing architecture error during linking.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-09-26

**Comment by thouis** [comment]
Comment in Trac by trac user smarschner, 2010-10-05

Indeed, this logic prevents a straightforward build (under OS 10.6.4 with gcc/gfortran 4.2.1) of the current release version (scipy-0.8.0) against the current Python 2.7 distribution for MacOS 10.6 from http://www.python.org/download/releases/2.7/.  (Manually removing -arch ppc64 from FFLAGS produces a working build.)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-07

For the record, this issue was first discussed in http://thread.gmane.org/gmane.comp.python.scientific.devel/12825.

The difference between the 10.3 and 10.5 installers from python.org is mentioned in http://thread.gmane.org/gmane.comp.python.devel/111844/focus=112704, that email also claims that ppc64 is a dead end on OS X so it doesn't look like any future Python installers will support ppc64.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-12

Matthew Brett has a proposed fix at http://github.com/matthew-brett/numpy/compare/numpy:master...farchs-from-c. More testing would be very welcome, especially on systems with a non-python.org-binary Python. David?

**Comment by thouis** [comment]
Comment in Trac by atmention:dwf, 2010-10-14

Matthew,

Thanks for the fix. I've moved institutions but I still have SSH access to the machine (I think), I'll give it a whirl tonight.

As for ppc64 being a dead end, so is ppc as far as Snow Leopard is concerned, however I don't think that's a compelling reason for dropping support of either if it's possible to accommodate PPC users.

I must apologize for my broken patch -- I thought I had done the due diligence testing against several different builds of Python, including those from python.org, though I should've had a closer look at what _can_target was doing.

David

**Comment by thouis** [comment]
Comment in Trac by atmention:dwf, 2010-10-14

I just tried it with two different custom builds of Python, one on my MacBook Pro and another on a G5 in ppc64 mode. Both build and install fine. Assuming this works with the more conventional cases, we should merge the patch.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-14

It works with python.org binaries, so good to go then.

And I thought I did enough testing too when I merged your patch, so I'll add my apology to yours.

**Comment by thouis** [comment]
Comment in Trac by atmention:dwf, 2010-10-14

Great. Are you planning on a 1.5.1 bugfix release?

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-15

Yes, rc1 this Sunday.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-16

Committed Matthew's patch in commit:658a1dc.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-16

And to the 1.5.x branch in commit:4e177d36.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-17

Didn't work on Windows. Grr. Caught it early at least. Fixed in commit:ba019417 and commit:3bc31748b.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-18

OK, I admit. I'm not smart enough to understand distutils. Tested with 3 versions on OS X and 2 versions on Windows - all fine. Version nr. 4 on OS X (py27 + macosx10.5 installer) fails:
    building 'scipy.lib.lapack.calc_lwork' extension
    compiling C sources
    C compiler: gcc-4.0 -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch ppc -arch x86_64 -g -O2 -DNDEBUG -g -O3

```
creating build/temp.macosx-10.5-fat3-2.7/build/src.macosx-10.5-fat3-2.7/scipy
creating build/temp.macosx-10.5-fat3-2.7/build/src.macosx-10.5-fat3-2.7/scipy/lib
creating build/temp.macosx-10.5-fat3-2.7/build/src.macosx-10.5-fat3-2.7/scipy/lib/lapack
compile options: '-DNO_ATLAS_INFO=3 -Ibuild/src.macosx-10.5-fat3-2.7 -I/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
extra options: '-faltivec'
gcc-4.0: build/src.macosx-10.5-fat3-2.7/fortranobject.c
gcc-4.0: build/src.macosx-10.5-fat3-2.7/scipy/lib/lapack/calc_lworkmodule.c
compiling Fortran sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -arch i386 -arch ppc -arch x86_64
Fortran f90 compiler: /usr/local/bin/gfortran -Wall -fno-second-underscore -fPIC -O3 -funroll-loops -arch i386 -arch ppc -arch x86_64
Fortran fix compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -Wall -fno-second-underscore -fPIC -O3 -funroll-loops -arch i386 -arch ppc -arch x86_64
compile options: '-DNO_ATLAS_INFO=3 -Ibuild/src.macosx-10.5-fat3-2.7 -I/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/include -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c'
gfortran:f77: scipy/lib/lapack/calc_lwork.f
/usr/local/bin/gfortran -Wall -Wall -undefined dynamic_lookup -bundle build/temp.macosx-10.5-fat3-2.7/build/src.macosx-10.5-fat3-2.7/scipy/lib/lapack/calc_lworkmodule.o build/temp.macosx-10.5-fat3-2.7/build/src.macosx-10.5-fat3-2.7/fortranobject.o build/temp.macosx-10.5-fat3-2.7/scipy/lib/lapack/calc_lwork.o -Lbuild/temp.macosx-10.5-fat3-2.7 -lgfortran -o scipy/lib/lapack/calc_lwork.so -Wl,-framework -Wl,Accelerate
```

See how all the -arch flags are correct in the "Fortran f77/f90/fix compiler:" lines, but then are still missing from the actual compile command? You only see this when compiling with the {{{--verbose}}} switch by the way.

Let's give it one more week, but if no one figures this out by next Monday let's reverse the original patch for 1.5.1.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-18

**Comment by thouis** [comment]
Comment in Trac by atmention:matthew-brett, 2010-10-18

Yes - investigating further - my previous patch enables compilation with the C flags architectures, but doesn't affect the .so linker args.  We didn't see a problem before because the default linker args were generating i386-only .so files.  These worked OK for an i386 python, but python 2.7 is x86_64 and so blows up when trying to use the i386 .so files.

We can make fat (i386, ppc64, x86_64) .so files with something like this patch:

```
diff --git a/numpy/distutils/fcompiler/gnu.py b/numpy/distutils/fcompiler/gnu.py
index a18a7a6..b149c71 100644
--- a/numpy/distutils/fcompiler/gnu.py
+++ b/numpy/distutils/fcompiler/gnu.py
atmention:atmention: -102,6 +102,9 atmention:atmention: class GnuFCompiler(FCompiler):
     def get_flags_linker_so(self):
         opt = self.linker_so[1:]
         if sys.platform=='darwin':
+            # Add any arch flags
+            opt.extend(self._c_arch_flags())
+            # Work out deployment target
             target = os.environ.get('MACOSX_DEPLOYMENT_TARGET', None)
             # If MACOSX_DEPLOYMENT_TARGET is set, we simply trust the value
             # and leave it alone.  But, distutils will complain if the
```

However, this leads to problems when using the 'libmach.a' library:

```
/usr/local/bin/gfortran -Wall -Wall -undefined dynamic_lookup -bundle -arch i386 -arch ppc -arch x86_64 build/temp.macosx-10.5-fat3-2.7/scipy/integrate/_quadpackmodule.o -Lbuild/temp.macosx-10.5-fat3-2.7 -lquadpack -llinpack_lite -lmach -lgfortran -o build/lib.macosx-10.5-fat3-2.7/scipy/integrate/_quadpack.so
ld: warning: object file compiled with -mlong-branch which is no longer needed. To remove this warning, recompile without -mlong-branch: /usr/local/lib/gcc/powerpc-apple-darwin8/4.2.3/crt3.o
ld: warning: in build/temp.macosx-10.5-fat3-2.7/libmach.a, file was built for unsupported file format which is not the architecture being linked (ppc)
ld: warning: in build/temp.macosx-10.5-fat3-2.7/libmach.a, file was built for unsupported file format which is not the architecture being linked (x86_64)
```

This in turn is because libmach.a has opts turned off by setup.py, maybe because it's trying to detect machine specific things, and therefore should not (cannot?) be used in cross-compile mode, as we are doing here?

```
building 'mach' library
using additional config_fc from setup script for fortran compiler: {'noopt': ('scipy/integrate/setup.pyc', 1)}
customize Gnu95FCompiler
compiling Fortran sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -fPIC
Fortran f90 compiler: /usr/local/bin/gfortran -Wall -fno-second-underscore -fPIC
Fortran fix compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -Wall -fno-second-underscore -fPIC
```

and

```
building 'sc_mach' library
using additional config_fc from setup script for fortran compiler: {'noopt': ('scipy/special/setup.pyc', 1)}
customize Gnu95FCompiler
compiling Fortran sources
Fortran f77 compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -fPIC
Fortran f90 compiler: /usr/local/bin/gfortran -Wall -fno-second-underscore -fPIC
Fortran fix compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -Wall -fno-second-underscore -fPIC
```

leading to scipy.test() errors like:

```
======================================================================
ERROR: Failure: ImportError (dlopen(/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/scipy/special/_cephes.so, 2): Symbol not found: _d1mach_
  Referenced from: /Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/scipy/special/_cephes.so
  Expected in: dynamic lookup
)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/loader.py", line 382, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/nose-0.11.4-py2.7.egg/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/scipy/stats/__init__.py", line 7, in <module>
    from stats import *
  File "/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/scipy/stats/stats.py", line 202, in <module>
    import scipy.special as special
  File "/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/scipy/special/__init__.py", line 8, in <module>
    from basic import *
  File "/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/scipy/special/basic.py", line 6, in <module>
    from _cephes import *
ImportError: dlopen(/Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/scipy/special/_cephes.so, 2): Symbol not found: _d1mach_
  Referenced from: /Users/mb312/.virtualenvs/python27/lib/python2.7/site-packages/scipy/special/_cephes.so
  Expected in: dynamic lookup
```

So - I suppose our only hope is that someone understands the mach .f files well enough to know what to do.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-19

Not sure about the mach .f files, but let's take a step back. Your original patch removed the {{{get_flags}}} and {{{get_flags_linker_so}}} methods. How about putting those back? The latter is what we need I think. The logic I would choose is:

```
arch_flags = []
for arch in _universal_flags:
    if arch in _c_arch_flags:
        arch_flags.extend(arch)
if not arch_flags == _c_arch_flags:
    # it seems our compiler does not support all targets the installed Python does
    raise SomeError
```

Now if the {{{get_arch_flags}}} method results in arch flags being supplied twice, we revert that as well.

Note that this is not a patch yet, will try to make it into one tonight.

**Comment by thouis** [comment]
Comment in Trac by atmention:matthew-brett, 2010-10-19

I imagine that get_flags_linker_so will solve the same problem as my patch above (maybe in a better way) but my guess is the 'noopt' flag to setup.py above will remove the arch flags and therefore fail in the same way as my patch did.   I'm afraid I don't understand why the 'noopt' flag has been set, and I imagine there was a good reason that we'd have to understand before overriding it.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-19

Not sure what the answer is (and would be good to know), but it shouldn't matter. I'm proposing this: http://github.com/rgommers/numpy/tree/fortran-archflags. This partly reverts your changes, the diff with what we had before is:

```
205,217d204
<     def _c_arch_flags(self):
<         """ Return detected arch flags from CFLAGS """
<         from distutils import sysconfig
<         try:
<             cflags = sysconfig.get_config_vars()['CFLAGS']
<         except KeyError:
<             return []
<         arch_re = re.compile(r"-arch\s+(\w+)")
<         arch_flags = []
<         for arch in arch_re.findall(cflags):
<             arch_flags += ['-arch', arch]
<         return arch_flags
< 
219c206
<         return self._c_arch_flags()
---
>         return []

274,279d256
<         # get arches the C compiler gets.
<         c_archs = self.get_flags_arch()
<         if "i386" in c_archs:
<             c_archs[c_archs.index("i386")] = "i686"
<         # check the arches the Fortran compiler supports, and compare with
<         # arch flags from C compiler
281c258
<             if _can_target(cmd, arch) and arch in c_archs:
---
>             if _can_target(cmd, arch):
```

A first test shows it returns the correct flags. Now compiling scipy to see if it all works.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-19

Looks like there's an unrelated bug now in master, but not in 1.5.x. 

My suggestion above also still has an issue, don't bother trying. I ran out of time for today, continue tomorrow.....

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-11-01

Looks like I got it finally:
    building 'mach' library
    using additional config_fc from setup script for fortran compiler: {'noopt': ('scipy/integrate/setup.py', 1)}
    customize Gnu95FCompiler
    compiling Fortran sources
    Fortran f77 compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -arch ppc -arch i686 -arch x86_64 -fPIC
    Fortran f90 compiler: /usr/local/bin/gfortran -Wall -fno-second-underscore -arch ppc -arch i686 -arch x86_64 -fPIC
    Fortran fix compiler: /usr/local/bin/gfortran -Wall -ffixed-form -fno-second-underscore -Wall -fno-second-underscore -arch ppc -arch i686 -arch x86_64 -fPIC
The {{{noopt}}} flag does not remove arch flags from the linker_so list for the mach library.

Fix at http://github.com/rgommers/numpy/commit/98831b699. Tested on OS X with 2.6 and 2.7 (incl 64-bit), and on Windows with 2.6:
    >>> np.test('full')  # runs extra distutils tests that failed before
    >>> sp.test()

Please test if this works for you.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-11-08

Committed in commit:435c7262592e94c8519f and commit:8346ba04a5c574441304.
