### ISSUE TITLE
Python2.7 requires DistutilsExecError (migrated from Trac #1410)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2963]
Original ticket http://projects.scipy.org/numpy/ticket/1410
Reported 2010-02-24 by atmention:bsouthey, assigned to atmention:cournape.

DistutilsExecError is not defined by Python 2.7 alpha 3 in 
numpy/distutils/ccompiler.py

Traceback (most recent call last):  
  File "setup.py", line 210, in <module>  
    setup_package()  
  File "setup.py", line 203, in setup_package  
    configuration=configuration )  
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/core.py", line 186, in setup  
    return old_setup(*_new_attr)
  File "/usr/local/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/command/build.py", line 37, in run
    old_build.run(self)
  File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/command/build_src.py", line 152, in run
    self.build_sources()
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/command/build_src.py", line 163, in build_sources
    self.build_library_sources(_libname_info)
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/command/build_src.py", line 298, in build_library_sources
    sources = self.generate_sources(sources, (lib_name, build_info))
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/command/build_src.py", line 385, in generate_sources
    source = func(extension, build_dir)
  File "numpy/core/setup.py", line 671, in get_mathlib_info
    mlibs = check_mathlib(config_cmd)
  File "numpy/core/setup.py", line 337, in check_mathlib
    if config_cmd.check_func("exp", libraries=libs, decl=True, call=True):
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/command/config.py", line 313, in check_func
    libraries, library_dirs)
  File "/usr/local/lib/python2.7/distutils/command/config.py", line 251, in try_link
    libraries, library_dirs, lang)
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/command/config.py", line 149, in _link
    libraries, library_dirs, lang))
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/command/config.py", line 89, in _wrap_method
    ret = mth(*((self,)+args))
  File "/usr/local/lib/python2.7/distutils/command/config.py", line 148, in _link
    target_lang=lang)
  File "/usr/local/lib/python2.7/distutils/ccompiler.py", line 750, in link_executable
    debug, extra_preargs, extra_postargs, None, target_lang)
  File "/usr/local/lib/python2.7/distutils/unixccompiler.py", line 256, in link
    self.spawn(linker + ld_args)
  File "/home/bsouthey/python/numpy_svn/numpy/numpy/distutils/ccompiler.py", line 69, in CCompiler_spawn
    raise DistutilsExecError('Command "%s" failed with exit status %d%s' % (cmd, s, msg))
NameError: global name 'DistutilsExecError' is not defined

**Comment by thouis** [comment]
Attachment in Trac by atmention:bsouthey, 2010-02-24: [DistutilsExecError.diff](http://projects.scipy.org/numpy/attachment/ticket/1410/DistutilsExecError.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:bsouthey, 2010-02-24

Sorry! This is covered by ticket 1355:
[http://projects.scipy.org/numpy/ticket/1355]

**Comment by thouis** [comment]
Comment in Trac by atmention:stefanv, 2010-02-24
