### ISSUE TITLE
Array reshape bug [obsolete] (migrated from Trac #1411)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2964]
Original ticket http://projects.scipy.org/numpy/ticket/1411
Reported 2010-02-25 by trac user Han, assigned to unknown.

(See also: http://bugs.python.org/issue6562 -- might be related?)

When reshaping a flat ndarray with a (mistaken) 64-bits long, an OverflowError will be generated in the C layer, but not propagated 
to the Python layer. This error can then be caught later on, in a totally unrelated piece of code.

```
>>> from __future__ import with_statement
>>> import sys; sys.version
'2.5.1 (r251:54863, Apr 18 2007, 08:51:08) [MSC v.1310 32 bit  Intel)]'
>>> import threading
>>> import numpy as np
>>> # needing this to reproduce the error, but it can
... # also be reproduced in other ways
... lock = threading.RLock()
>>> # creating a flat array
... arr = np.arange(10)
>>> # reshaping the array, but mistakenly using a 64-bit integer
... arr_shaped = arr.reshape(1<<63)
>>> # all seems to go well up to this point..
... with lock:
...     print "done!"
...
C:\Python25\lib\threading.py:697: RuntimeWarning: tp_compare didn't return -1 or
 -2 for exception
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "c:\python25\lib\threading.py", line 94, in acquire
    me = currentThread()
  File "c:\python25\lib\threading.py", line 697, in currentThread
    return _active[_get_ident()]
OverflowError: long int too large to convert to int 
```

Other ways to reproduce the OverflowError after creating arr_shaped:

```
>>> print arr_shaped
>>> import <anything>
>>> arr_shaped + 10 # or other operations
```

I also tested it on Python 2.6, with similar results.

**Comment by thouis** [comment]
Comment in Trac by trac user Han, 2010-03-19

Ok, I've traced the original problem to the function  PyArray_IntpFromSequence in arrayobject.c:

This function converts the sequence of given shape values  into a C-array of integers. It has a special case, though,  when the sequence value is no sequence but a single (integer) value. The problem is, it checks if the value is a Python integer, and then it converts the Python value to  its C equivalent, but it never checks if the conversion went well.. 

```
/*NUMPY_API
 * PyArray_IntpFromSequence
 * Returns the number of dimensions or -1 if an error occurred.
 * vals must be large enough to hold maxvals
 */
static int
PyArray_IntpFromSequence(PyObject *seq, intp *vals, int maxvals)
[..]
    if ((nd=PySequence_Length(seq)) == -1) {
        if (PyErr_Occurred()) PyErr_Clear();
#if SIZEOF_LONG >= SIZEOF_INTP
        if (!(op = PyNumber_Int(seq))) {
            return -1;
        }
#else
        if (!(op = PyNumber_Long(seq))) {
            return -1;
        }
#endif
        nd = 1;
#if SIZEOF_LONG >= SIZEOF_INTP
        vals[0] = (intp ) PyInt_AsLong(op);   // Generates the OverflowError
#else
        vals[0] = (intp ) PyLong_AsLongLong(op);
#endif
        Py_DECREF(op);
    }
[..]
return nd
```

When adding

```
        if(PyErr_Occurred()) {
            return -1;
        }
```

after
        Py_DECREF(op);
it works as expected.

**Comment by thouis** [comment]
Comment in Trac by trac user Han, 2010-03-22

Ah sorry.. this has already been fixed for the development version in r6708. (And later exported to conversion_utils.c in r6950.)

Thanks,
Han

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-04-24
