### ISSUE TITLE
ma._extrema_operation subclasses' reduce method raise ValueError... (migrated from Trac #1422)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2975]
Original ticket http://projects.scipy.org/numpy/ticket/1422
Reported 2010-03-05 by trac user dgoldsmith, assigned to atmention:pierregm.

...if passed zero-size array.
    >>> mn = numpy.ma.core._minimum_operation()
    >>> mn.reduce(N.array(()))
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "C:\Python254\Lib\site-packages\numpy\ma\core.py", line 5570, in reduce
        t = self.ufunc.reduce(target, **kargs)
    ValueError: zero-size array to ufunc.reduce without identity

Notes:

0) Problem discovered via a call from matplotlib.imshow; here's that traceback:
    Traceback (most recent call last):
     File "<my_code.py>", line 108, in <module>
    ax.imshow(part2plot, cmap_name, extent = extent)
     File "C:\Python254\lib\site-packages\matplotlib\axes.py", line 6261, in imshow
    im.autoscale_None()
     File "C:\Python254\lib\site-packages\matplotlib\cm.py", line 236, in autoscale_None
    self.norm.autoscale_None(self._A)
     File "C:\Python254\lib\site-packages\matplotlib\colors.py", line 792, in autoscale_None
    if self.vmin is None: self.vmin = ma.minimum(A)
     File "C:\Python254\Lib\site-packages\numpy\ma\core.py", line 5555, in __call__
    return self.reduce(a)
     File "C:\Python254\Lib\site-packages\numpy\ma\core.py", line 5570, in reduce
    t = self.ufunc.reduce(target, **kargs)
    ValueError: zero-size array to ufunc.reduce without identity
    Script terminated.
1) Platform details: numpy 1.4.0, MPL 0.99.0, python 2.5.4, 32 bit Vista Home Premium SP2

**Comment by thouis** [comment]
Comment in Trac by trac user dgoldsmith, 2010-03-06

Here's a small self-contained example that reproduces the problem as it arises from matplotlib's imshow (thanks to Friedrich Romstedt friedrichromstedtatmention:gmail.com for providing it):
    >>> from matplotlib.figure import Figure
    >>> ax = Figure().add_subplot(1,1,1)
    >>> argW = numpy.asarray([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
    >>> argW[0:1, 0:0]
    array([], shape=(1, 0), dtype=int32)
    >>> ax.imshow(argW[0:1, 0:0])
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "C:\Python254\lib\site-packages\matplotlib\axes.py", line 6261, in imshow
        im.autoscale_None()
      File "C:\Python254\lib\site-packages\matplotlib\cm.py", line 236, in autoscale_None
        self.norm.autoscale_None(self._A)
      File "C:\Python254\lib\site-packages\matplotlib\colors.py", line 792, in autoscale_None
        if self.vmin is None: self.vmin = ma.minimum(A)
      File "C:\Python254\Lib\site-packages\numpy\ma\core.py", line 5555, in __call__
        return self.reduce(a)
      File "C:\Python254\Lib\site-packages\numpy\ma\core.py", line 5570, in reduce
        t = self.ufunc.reduce(target, **kargs)
    ValueError: zero-size array to ufunc.reduce without identity

**Comment by thouis** [comment]
Comment in Trac by trac user dgoldsmith, 2010-03-08

OK, it's been opined on numpy-discussion that this isn't a bug, but a feature, and indeed the fact that my code was causing it to be raised was traced to a bug in my code...so I leave it to the "owner" to decide how to proceed.

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-09-13

Well, considering that the same exception is raised with a standard ndarray of size 0, I gonna close the ticket as 'invalid'.
