### ISSUE TITLE
Error running: easy_install numpy (migrated from Trac #1423)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#2976]
Original ticket http://projects.scipy.org/numpy/ticket/1423
Reported 2010-03-05 by trac user rjain, assigned to unknown.

(demoenv)jainatmention:jain-desktop:/sandbox/demoenv$ easy_install numpy
Searching for numpy
Reading http://pypi.python.org/simple/numpy/
Reading http://numpy.scipy.org
Reading http://sourceforge.net/project/showfiles.php?group_id=1369&package_id=175103
Reading http://numeric.scipy.org
Best match: numpy 1.3.0
Downloading http://sourceforge.net/projects/numpy/files/NumPy/1.3.0/numpy-1.3.0.zip/download
Processing download
Running numpy-1.3.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zpQwWp/numpy-1.3.0/egg-dist-tmp-mmTb5S
Running from numpy source directory.
non-existing path in 'numpy/distutils': 'site.cfg'
/tmp/easy_install-zpQwWp/numpy-1.3.0/numpy/distutils/command/config.py:361: DeprecationWarning: 
+++++++++++++++++++++++++++++++++++++++++++++++++
Usage of get_output is deprecated: please do not 
use it anymore, and avoid configuration checks 
involving running executable on the target machine.
+++++++++++++++++++++++++++++++++++++++++++++++++

  DeprecationWarning)
Found executable /usr/bin/g77
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
compiling '_configtest.c':

/\* This file is generated from numpy/distutils/system_info.py */
void ATL_buildinfo(void);
int main(void) {
  ATL_buildinfo();
  return 0;
}
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to `_gfortran_st_write_done'
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to`_gfortran_transfer_integer'
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to `_gfortran_stop_numeric'
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to`_gfortran_st_write'
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to `_gfortran_transfer_character'
collect2: ld returned 1 exit status
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to`_gfortran_st_write_done'
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to `_gfortran_transfer_integer'
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to`_gfortran_stop_numeric'
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to `_gfortran_st_write'
/usr/lib/gcc/x86_64-linux-gnu/4.2.4/../../../../lib/libf77blas.so: undefined reference to`_gfortran_transfer_character'
collect2: ld returned 1 exit status
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
compiling '_configtest.c':

/\* This file is generated from numpy/distutils/system_info.py */
void ATL_buildinfo(void);
int main(void) {
  ATL_buildinfo();
  return 0;
}
ATLAS version 3.6.0 built by root on Thu Jun  3 21:13:07 UTC 2004:
   UNAME    : Linux ravel 2.6.5 #3 SMP Tue Apr 13 13:41:54 UTC 2004 x86_64 GNU/Linux
   INSTFLG  : 
   MMDEF    : /home/camm/atlas3-3.6.0/CONFIG/ARCHS/HAMMER64SSE2/gcc/gemm
   ARCHDEF  : /home/camm/atlas3-3.6.0/CONFIG/ARCHS/HAMMER64SSE2/gcc/misc
   F2CDEFS  : -DAdd__ -DStringSunStyle
   CACHEEDGE: 720896
   F77      : /home/camm/usr/bin/g77, version GNU Fortran (GCC) 3.3.3 (Debian 20040422)
   F77FLAGS : -fomit-frame-pointer -O -m64
   CC       : /usr/bin/gcc, version gcc (GCC) 3.3.3 (Debian 20040422)
   CC FLAGS : -fomit-frame-pointer -O -mfpmath=387 -m64
   MCC      : /usr/bin/gcc, version gcc (GCC) 3.3.3 (Debian 20040422)
   MCCFLAGS : -fomit-frame-pointer -O -mfpmath=387 -m64
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c: In function ‘main’:
_configtest.c:5: error: size of array ‘test_array’ is negative
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c: In function ‘main’:
_configtest.c:5: error: size of array ‘test_array’ is negative
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c: In function ‘main’:
_configtest.c:5: error: size of array ‘test_array’ is negative
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c: In function ‘main’:
_configtest.c:5: error: size of array ‘test_array’ is negative
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c: In function ‘main’:
_configtest.c:7: error: size of array ‘test_array’ is negative
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c: In function ‘main’:
_configtest.c:7: error: size of array ‘test_array’ is negative
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c:5: warning: function declaration isn’t a prototype
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:4: warning: function declaration isn’t a prototype
_configtest.c:5: warning: function declaration isn’t a prototype
/tmp/easy_install-zpQwWp/numpy-1.3.0/numpy/distutils/command/config.py:39: DeprecationWarning: 
+++++++++++++++++++++++++++++++++++++++++++++++++
Usage of try_run is deprecated: please do not 
use it anymore, and avoid configuration checks 
involving running executable on the target machine.
+++++++++++++++++++++++++++++++++++++++++++++++++

  DeprecationWarning)
_configtest.o: In function `main':
/tmp/easy_install-zpQwWp/numpy-1.3.0/_configtest.c:5: undefined reference to`exp'
collect2: ld returned 1 exit status
_configtest.o: In function `main':
/tmp/easy_install-zpQwWp/numpy-1.3.0/_configtest.c:5: undefined reference to`exp'
collect2: ld returned 1 exit status
_configtest.c:1: warning: conflicting types for built-in function ‘asin’
_configtest.c:2: warning: conflicting types for built-in function ‘cos’
_configtest.c:3: warning: conflicting types for built-in function ‘log’
_configtest.c:4: warning: conflicting types for built-in function ‘fabs’
_configtest.c:5: warning: conflicting types for built-in function ‘tanh’
_configtest.c:6: warning: conflicting types for built-in function ‘atan’
_configtest.c:7: warning: conflicting types for built-in function ‘acos’
_configtest.c:8: warning: conflicting types for built-in function ‘floor’
_configtest.c:9: warning: conflicting types for built-in function ‘fmod’
_configtest.c:10: warning: conflicting types for built-in function ‘sqrt’
_configtest.c:11: warning: conflicting types for built-in function ‘cosh’
_configtest.c:12: warning: conflicting types for built-in function ‘modf’
_configtest.c:13: warning: conflicting types for built-in function ‘sinh’
_configtest.c:14: warning: conflicting types for built-in function ‘frexp’
_configtest.c:15: warning: conflicting types for built-in function ‘exp’
_configtest.c:16: warning: conflicting types for built-in function ‘tan’
_configtest.c:17: warning: conflicting types for built-in function ‘ceil’
_configtest.c:18: warning: conflicting types for built-in function ‘log10’
_configtest.c:19: warning: conflicting types for built-in function ‘sin’
_configtest.c:20: warning: conflicting types for built-in function ‘ldexp’
_configtest.c:1: warning: conflicting types for built-in function ‘expm1’
_configtest.c:2: warning: conflicting types for built-in function ‘log2’
_configtest.c:3: warning: conflicting types for built-in function ‘rint’
_configtest.c:4: warning: conflicting types for built-in function ‘atanh’
_configtest.c:5: warning: conflicting types for built-in function ‘asinh’
_configtest.c:6: warning: conflicting types for built-in function ‘acosh’
_configtest.c:7: warning: conflicting types for built-in function ‘exp2’
_configtest.c:8: warning: conflicting types for built-in function ‘log1p’
_configtest.c:9: warning: conflicting types for built-in function ‘trunc’
_configtest.c:1: warning: conflicting types for built-in function ‘cosf’
_configtest.c:2: warning: conflicting types for built-in function ‘coshf’
_configtest.c:3: warning: conflicting types for built-in function ‘rintf’
_configtest.c:4: warning: conflicting types for built-in function ‘fabsf’
_configtest.c:5: warning: conflicting types for built-in function ‘floorf’
_configtest.c:6: warning: conflicting types for built-in function ‘tanhf’
_configtest.c:7: warning: conflicting types for built-in function ‘log10f’
_configtest.c:8: warning: conflicting types for built-in function ‘logf’
_configtest.c:9: warning: conflicting types for built-in function ‘sinhf’
_configtest.c:10: warning: conflicting types for built-in function ‘acosf’
_configtest.c:11: warning: conflicting types for built-in function ‘sqrtf’
_configtest.c:12: warning: conflicting types for built-in function ‘ldexpf’
_configtest.c:13: warning: conflicting types for built-in function ‘hypotf’
_configtest.c:14: warning: conflicting types for built-in function ‘log2f’
_configtest.c:15: warning: conflicting types for built-in function ‘exp2f’
_configtest.c:16: warning: conflicting types for built-in function ‘atanf’
_configtest.c:17: warning: conflicting types for built-in function ‘fmodf’
_configtest.c:18: warning: conflicting types for built-in function ‘atan2f’
_configtest.c:19: warning: conflicting types for built-in function ‘modff’
_configtest.c:20: warning: conflicting types for built-in function ‘ceilf’
_configtest.c:21: warning: conflicting types for built-in function ‘log1pf’
_configtest.c:22: warning: conflicting types for built-in function ‘asinf’
_configtest.c:23: warning: conflicting types for built-in function ‘acoshf’
_configtest.c:24: warning: conflicting types for built-in function ‘sinf’
_configtest.c:25: warning: conflicting types for built-in function ‘tanf’
_configtest.c:26: warning: conflicting types for built-in function ‘atanhf’
_configtest.c:27: warning: conflicting types for built-in function ‘truncf’
_configtest.c:28: warning: conflicting types for built-in function ‘asinhf’
_configtest.c:29: warning: conflicting types for built-in function ‘frexpf’
_configtest.c:30: warning: conflicting types for built-in function ‘powf’
_configtest.c:31: warning: conflicting types for built-in function ‘expf’
_configtest.c:32: warning: conflicting types for built-in function ‘expm1f’
_configtest.c:1: warning: conflicting types for built-in function ‘tanhl’
_configtest.c:2: warning: conflicting types for built-in function ‘log10l’
_configtest.c:3: warning: conflicting types for built-in function ‘coshl’
_configtest.c:4: warning: conflicting types for built-in function ‘cosl’
_configtest.c:5: warning: conflicting types for built-in function ‘floorl’
_configtest.c:6: warning: conflicting types for built-in function ‘rintl’
_configtest.c:7: warning: conflicting types for built-in function ‘fabsl’
_configtest.c:8: warning: conflicting types for built-in function ‘acosl’
_configtest.c:9: warning: conflicting types for built-in function ‘ldexpl’
_configtest.c:10: warning: conflicting types for built-in function ‘sqrtl’
_configtest.c:11: warning: conflicting types for built-in function ‘logl’
_configtest.c:12: warning: conflicting types for built-in function ‘expm1l’
_configtest.c:13: warning: conflicting types for built-in function ‘hypotl’
_configtest.c:14: warning: conflicting types for built-in function ‘log2l’
_configtest.c:15: warning: conflicting types for built-in function ‘exp2l’
_configtest.c:16: warning: conflicting types for built-in function ‘atanl’
_configtest.c:17: warning: conflicting types for built-in function ‘frexpl’
_configtest.c:18: warning: conflicting types for built-in function ‘atan2l’
_configtest.c:19: warning: conflicting types for built-in function ‘sinhl’
_configtest.c:20: warning: conflicting types for built-in function ‘fmodl’
_configtest.c:21: warning: conflicting types for built-in function ‘log1pl’
_configtest.c:22: warning: conflicting types for built-in function ‘asinl’
_configtest.c:23: warning: conflicting types for built-in function ‘ceill’
_configtest.c:24: warning: conflicting types for built-in function ‘sinl’
_configtest.c:25: warning: conflicting types for built-in function ‘acoshl’
_configtest.c:26: warning: conflicting types for built-in function ‘atanhl’
_configtest.c:27: warning: conflicting types for built-in function ‘tanl’
_configtest.c:28: warning: conflicting types for built-in function ‘truncl’
_configtest.c:29: warning: conflicting types for built-in function ‘powl’
_configtest.c:30: warning: conflicting types for built-in function ‘expl’
_configtest.c:31: warning: conflicting types for built-in function ‘modfl’
_configtest.c:32: warning: conflicting types for built-in function ‘asinhl’
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c:6: warning: function declaration isn’t a prototype
_configtest.c:6: warning: function declaration isn’t a prototype
File: build/src.linux-x86_64-2.5/numpy/core/include/numpy/config.h
# define SIZEOF_SHORT 2
# define SIZEOF_INT 4
# define SIZEOF_LONG 8
# define SIZEOF_FLOAT 4
# define SIZEOF_DOUBLE 8
# define SIZEOF_PY_INTPTR_T 8
# define SIZEOF_PY_LONG_LONG 8
# define MATHLIB m
# define HAVE_SIN
# define HAVE_COS
# define HAVE_TAN
# define HAVE_SINH
# define HAVE_COSH
# define HAVE_TANH
# define HAVE_FABS
# define HAVE_FLOOR
# define HAVE_CEIL
# define HAVE_SQRT
# define HAVE_LOG10
# define HAVE_LOG
# define HAVE_EXP
# define HAVE_ASIN
# define HAVE_ACOS
# define HAVE_ATAN
# define HAVE_FMOD
# define HAVE_MODF
# define HAVE_FREXP
# define HAVE_LDEXP
# define HAVE_EXPM1
# define HAVE_LOG1P
# define HAVE_ACOSH
# define HAVE_ASINH
# define HAVE_ATANH
# define HAVE_RINT
# define HAVE_TRUNC
# define HAVE_EXP2
# define HAVE_LOG2
# define HAVE_SINF
# define HAVE_COSF
# define HAVE_TANF
# define HAVE_SINHF
# define HAVE_COSHF
# define HAVE_TANHF
# define HAVE_FABSF
# define HAVE_FLOORF
# define HAVE_CEILF
# define HAVE_RINTF
# define HAVE_TRUNCF
# define HAVE_SQRTF
# define HAVE_LOG10F
# define HAVE_LOGF
# define HAVE_LOG1PF
# define HAVE_EXPF
# define HAVE_EXPM1F
# define HAVE_ASINF
# define HAVE_ACOSF
# define HAVE_ATANF
# define HAVE_ASINHF
# define HAVE_ACOSHF
# define HAVE_ATANHF
# define HAVE_HYPOTF
# define HAVE_ATAN2F
# define HAVE_POWF
# define HAVE_FMODF
# define HAVE_MODFF
# define HAVE_FREXPF
# define HAVE_LDEXPF
# define HAVE_EXP2F
# define HAVE_LOG2F
# define HAVE_SINL
# define HAVE_COSL
# define HAVE_TANL
# define HAVE_SINHL
# define HAVE_COSHL
# define HAVE_TANHL
# define HAVE_FABSL
# define HAVE_FLOORL
# define HAVE_CEILL
# define HAVE_RINTL
# define HAVE_TRUNCL
# define HAVE_SQRTL
# define HAVE_LOG10L
# define HAVE_LOGL
# define HAVE_LOG1PL
# define HAVE_EXPL
# define HAVE_EXPM1L
# define HAVE_ASINL
# define HAVE_ACOSL
# define HAVE_ATANL
# define HAVE_ASINHL
# define HAVE_ACOSHL
# define HAVE_ATANHL
# define HAVE_HYPOTL
# define HAVE_ATAN2L
# define HAVE_POWL
# define HAVE_FMODL
# define HAVE_MODFL
# define HAVE_FREXPL
# define HAVE_LDEXPL
# define HAVE_EXP2L
# define HAVE_LOG2L
# define HAVE_DECL_ISNAN
# define HAVE_DECL_ISINF
# define HAVE_DECL_SIGNBIT
# define HAVE_DECL_ISFINITE
# ifndef __cplusplus

/\* #undef inline */
# endif

EOF
_configtest.c:5: warning: function declaration isn’t a prototype
File: build/src.linux-x86_64-2.5/numpy/core/include/numpy/numpyconfig.h
# define NPY_SIZEOF_SHORT 2
# define NPY_SIZEOF_INT 4
# define NPY_SIZEOF_LONG 8
# define NPY_SIZEOF_FLOAT 4
# define NPY_SIZEOF_DOUBLE 8
# define NPY_SIZEOF_LONGDOUBLE 16
# define NPY_SIZEOF_PY_INTPTR_T 8
# define NPY_SIZEOF_PY_LONG_LONG 8
# define NPY_SIZEOF_LONGLONG 8
# define NPY_NO_SMP 0
# define NPY_HAVE_DECL_ISNAN
# define NPY_HAVE_DECL_ISINF
# define NPY_HAVE_DECL_SIGNBIT
# define NPY_HAVE_DECL_ISFINITE
# define NPY_USE_C99_FORMATS 1
# define NPY_INLINE inline
# ifndef __STDC_FORMAT_MACROS
# define __STDC_FORMAT_MACROS 1
# endif

EOF
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
gnu: no Fortran 90 compiler found
zip_safe flag not set; analyzing archive contents...
numpy._import_tools: module references __file__
numpy._import_tools: module references __path__
numpy.version: module references **file**
numpy.core.scons_support: module references **file**
numpy.core.setup: module references **file**
numpy.core.generate_numpy_api: module references **file**
numpy.doc.**init**: module references **file**
numpy.ma.core: module MAY be using inspect.trace
numpy.numarray.util: module references **file**
numpy.distutils.system_info: module references **file**
numpy.distutils.exec_command: module references **file**
numpy.distutils.misc_util: module references **file**
numpy.distutils.fcompiler.compaq: module references **file**
numpy.distutils.fcompiler.**init**: module references **file**
numpy.distutils.command.build_src: module references **file**
numpy.distutils.command.scons: module references **file**
numpy.lib.utils: module references **file**
numpy.lib.utils: module references **path**
numpy.lib.utils: module MAY be using inspect.getsource
numpy.lib.utils: module MAY be using inspect.getsourcefile
numpy.testing.numpytest: module references **file**
numpy.testing.utils: module references **file**
numpy.testing.noseclasses: module references **file**
numpy.testing.nosetester: module references **file**
numpy.f2py.setup: module references **file**
numpy.f2py.f2py2e: module references **file**
numpy.f2py.setupscons: module references **file**
numpy.f2py.diagnose: module references **file**
Adding numpy 1.3.0 to easy-install.pth file
Installing f2py script to /sandbox/demoenv/bin

Installed /sandbox/demoenv/lib/python2.5/site-packages/numpy-1.3.0-py2.5-linux-x86_64.egg
Processing dependencies for numpy
Finished processing dependencies for numpy
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.5/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/tmp/easy_install-zpQwWp/numpy-1.3.0/numpy/distutils/misc_util.py", line 219, in clean_up_temporary_directory
SystemError: Parent module 'numpy.distutils' not loaded
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.5/atexit.py", line 24, in _run_exitfuncs
    func(_targs, *_kargs)
  File "/tmp/easy_install-zpQwWp/numpy-1.3.0/numpy/distutils/misc_util.py", line 219, in clean_up_temporary_directory
SystemError: Parent module 'numpy.distutils' not loaded

**Comment by thouis** [comment]
Comment in Trac by trac user rjain, 2010-03-05

Let me know if you need details. rajeejaatmention:gmail.com

Rajeev Jain

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2010-03-06

There is no need to use easy_install, just install from sources with python setup.py install.

It seems also that your blas/lapack is built with gfortran: you should make sure to use gfortran when building numpy as well: python setup.py build_ext --fcompiler=gnu95 install

**Comment by thouis** [comment]
Comment in Trac by atmention:cournape, 2010-04-02
