### ISSUE TITLE
Datetime test_creation_overflow fails (migrated from Trac #1468)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3020]
Original ticket http://projects.scipy.org/numpy/ticket/1468
Reported 2010-04-29 by atmention:pv, assigned to atmention:stefanv.

On a 32-bit system, r8372:
    ======================================================================
    FAIL: test_creation_overflow (test_datetime.TestDateTime)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/pauli/wrk/scipy/numpy/dist/linux/lib/python2.6/site-packages/numpy/core/tests/test_datetime.py", line 68, in test_creation_overflow
        err_msg='Datetime conversion error for unit %s' % unit)
      File "/home/pauli/wrk/scipy/numpy/dist/linux/lib/python2.6/site-packages/numpy/testing/utils.py", line 313, in assert_equal
        raise AssertionError(msg)
    AssertionError: 
    Items are not equal: Datetime conversion error for unit ms
     ACTUAL: 567052800
     DESIRED: 322689600000
    >>  raise AssertionError('\nItems are not equal: Datetime conversion error for unit ms\n ACTUAL: 567052800\n DESIRED: 322689600000')

Any ideas what's wrong?

**Comment by thouis** [comment]
Comment in Trac by atmention:stefanv, 2010-05-01

I added this test to expose a failure in the datetime machinery.  I was able to fix the overflow problem on my 64-bit mac, but clearly there is still a 32-bit integer multiplication taking place somewhere that I overlooked.

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2010-05-05

Confirmed on Mac OSX, Solaris, and Red Hat Enterprise 4 Linux, all in 32 bit python 2.5 interpreters.  I see the same actual and desired values.

Confirmed not happening on Red Hat Enterprise 4 and 5, both 64 bit python 2.5.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-05-07

With python 3.1 there is another error in the test

```
ERROR: test_universal_newline (test_io.TestLoadTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.1/site-packages/numpy/lib/tests/test_io.py", line 412, in test_universal_newline
    data = np.loadtxt(name)
  File "/usr/local/lib/python3.1/site-packages/numpy/lib/npyio.py", line 632, in loadtxt
    first_vals = split_line(first_line)
  File "/usr/local/lib/python3.1/site-packages/numpy/lib/npyio.py", line 610, in split_line
    line = line.split(comments)[0].strip()
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-05-07

Oops, wrong ticket.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-09

Actually the bug is not in datetime code. The test should probably use `np.int64` instead of `int`. Fixed in r8400.

Compare,
    >>> import numpy as np
    >>> x = np.int32(322689600)
    >>> x *= 1000
    Warning: overflow encountered in long_scalars
    >>> x
    567052800
    >>> type(x)
    <type 'numpy.int32'>

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
