### ISSUE TITLE
numpy.take has a bug (ubuntu 10.4) (migrated from Trac #1474)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3026]
Original ticket http://projects.scipy.org/numpy/ticket/1474
Reported 2010-05-05 by trac user hillier_dani, assigned to unknown.

import numpy

a = numpy.ones((256,256,3))

b = numpy.take(a,[1,0,2],axis=2)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/dist-packages/numpy-1.4.1-py2.6-linux-x86_64.egg/numpy/core/fromnumeric.py", line 103, in take
    return take(indices, axis, out, mode)
IndexError: index out of range for array

Example fails with above error: numpy 1.4.1 python 2.6.5 ubuntu 10.4:

Example works: Mac OSX 10.6, same python/numpy version.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-05

Works for me. 32-bit system here, though.

**Comment by thouis** [comment]
Comment in Trac by trac user hillier_dani, 2010-05-06

I delected all numpy versions on my system and recompiled numpy from source. Now the example works. I suspect the problem was related to a conflict between 32 bit and 64 bit binaries.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-06

Ok, closing the ticket then.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31
