### ISSUE TITLE
Cannot access date-time internals without ctypes installed (migrated from Trac #1475)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3027]
Original ticket http://projects.scipy.org/numpy/ticket/1475
Reported 2010-05-05 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
ERROR: test_type_check.TestDateTimeData.test_basic
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/lib/tests/test_type_check.py", line 382, in test_basic
    assert_equal(datetime_data(a.dtype), ('us', 1, 1, 1))
  File "/usr/stsci/pyssgdev/2.5.4/numpy/lib/type_check.py", line 610, in datetime_data
    raise RuntimeError, "Cannot access date-time internals without ctypes installed"
RuntimeError: Cannot access date-time internals without ctypes installed
```

Happens on
- Mac OSX Leopard, 32 bit python 2.5.4
- Solaris 8, 32 bit Python 2.5.4

Not on
- Red Hat Enterprise 4 Linux, 32 or 64 bit python 2.5
- Red Hat Enterprise 5 linux, 32 bit python 2.5

When you compile python, it automatically decides whether to include ctypes.  In my experience, it likes Linux but not Mac or Solaris.

It is not clear to me if this means that the test should be changed (e.g. to skip if ctypes is not available) or if ctypes should become a hard and fast requirement to run numpy.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-06-02

Once we finally drop python 2.4 support this issue is resolved - ctypes is in the stdlib from python 2.5 so numpy can depend on it.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-06-02

There is a test that also uses ctypes. It should be checked to see that it is skipped if ctypes isn't present.

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2010-06-02

As far as I can tell, python 2.5 does not always have ctypes:

Mac OSX 10.5:
    w% python
    Python 2.5.4 (r254:67916, Nov  5 2009, 16:32:32) 
    [GCC 4.0.1 (Apple Inc. build 5465)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ctypes
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/stsci/pyssgdev/Python-2.5.4/lib/python2.5/ctypes/**init**.py", line 27, in <module>
        import gestalt
    ImportError: No module named gestalt
    >>> 

Solaris 8:
    % python
    Python 2.5.4 (r254:67916, Oct 23 2009, 16:32:19) [C] on sunos5
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import ctypes
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/stsci/pyssgdev/Python-2.5.4/lib/python2.5/ctypes/**init**.py", line 10, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: No module named _ctypes
    >>> 

It seems to work in python 2.5 on linux and python 2.6 on linux and mac.

These are all python interpreters that I compiled from source, but I did not make any special effort to include/exclude ctypes.  The auto config must have done it, or it must be built-in to python.

It is worth considering whether numpy should be dependent on "standard" libraries that may not be present.

On my machines that do not have ctypes, this is the only test that is reporting a problem.  That suggests that any other test that requires ctypes is automatically skipped.

**Comment by thouis** [comment]
Comment in Trac by atmention:bsouthey, 2010-09-15

I did a patch to skip this test. But that is not a complete solution because ctypes needs to be installed for Python2.4 from:
[http://starship.python.net/crew/theller/ctypes/ http://starship.python.net/crew/theller/ctypes/]. 

After installation of ctypes, the tests for NumPy version 2.0.0.dev8715 pass. Thus, the release and installation notes will need reference to this dependency if users want to use datetime under Python2.4.

**Comment by thouis** [comment]
Attachment in Trac by atmention:bsouthey, 2010-09-15: [test_type_check.diff](http://projects.scipy.org/numpy/attachment/ticket/1475/test_type_check.diff)
