### ISSUE TITLE
selector.choose  - more keyword list entries than argument specifiers (migrated from Trac #1476)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3028]
Original ticket http://projects.scipy.org/numpy/ticket/1476
Reported 2010-05-05 by atmention:stsci-sienkiew, assigned to unknown.

numpy.test() fails in many places with this error:

```
======================================================================
ERROR: test_all (test_multiarray.TestArgmax)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_multiarray.py", line 681, in test_all
    assert all(amax == aargmax.choose(*a.transpose(i,*axes)))
RuntimeError: more keyword list entries than argument specifiers

======================================================================
ERROR: test_basic (test_multiarray.TestChoose)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_multiarray.py", line 1190, in test_basic
    A = np.choose(self.ind, (self.x, self.y))
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/fromnumeric.py", line 295, in choose
    return _wrapit(a, 'choose', choices, out=out, mode=mode)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/fromnumeric.py", line 37, in _wrapit
    result = getattr(asarray(obj),method)(*args, **kwds)
RuntimeError: more keyword list entries than argument specifiers

======================================================================
ERROR: test_broadcast1 (test_multiarray.TestChoose)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_multiarray.py", line 1194, in test_broadcast1
    A = np.choose(self.ind, (self.x2, self.y2))
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/fromnumeric.py", line 295, in choose
    return _wrapit(a, 'choose', choices, out=out, mode=mode)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/fromnumeric.py", line 37, in _wrapit
    result = getattr(asarray(obj),method)(*args, **kwds)
RuntimeError: more keyword list entries than argument specifiers

======================================================================
ERROR: test_broadcast2 (test_multiarray.TestChoose)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_multiarray.py", line 1198, in test_broadcast2
    A = np.choose(self.ind, (self.x, self.y2))
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/fromnumeric.py", line 295, in choose
    return _wrapit(a, 'choose', choices, out=out, mode=mode)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/fromnumeric.py", line 37, in _wrapit
    result = getattr(asarray(obj),method)(*args, **kwds)
RuntimeError: more keyword list entries than argument specifiers

======================================================================
ERROR: Test native double input with array min/max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 436, in test_array_double
    act = self.clip(a, m, M)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 378, in clip
    return selector.choose((a, m, M), out=out)
RuntimeError: more keyword list entries than argument specifiers

======================================================================
ERROR: Ensure that the clip() function takes an out= argument.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 779, in test_clip_func_takes_out
    self.clip(a, m, M, ac)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 378, in clip
    return selector.choose((a, m, M), out=out)
RuntimeError: more keyword list entries than argument specifiers

======================================================================
ERROR: Test native double input with array min/max
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 758, in test_clip_inplace_array
    self.clip(a, m, M, ac)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 378, in clip
    return selector.choose((a, m, M), out=out)
RuntimeError: more keyword list entries than argument specifiers

======================================================================
ERROR: Test native double input with scalar min/max
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 768, in test_clip_inplace_simple
    self.clip(a, m, M, ac)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 378, in clip
    return selector.choose((a, m, M), out=out)
RuntimeError: more keyword list entries than argument specifiers

======================================================================
ERROR: Test clip for non contiguous native input and native scalar min/max.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 484, in test_clip_non_contig
    act = self.clip(a, -1.6, 1.7)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_numeric.py", line 378, in clip
    return selector.choose((a, m, M), out=out)
RuntimeError: more keyword list entries than argument specifiers
```

There are more, but this is a representative sample of the problem.

Happens on 
- Mac OSX Leopard, 32 bit python 2.5.4
- Solaris 8, 32 bit python 2.5.4
- Red Hat Enterprise 4 Linux, 32 bit python 2.5.4
- Red Hat Enterprise 4 Linux, 64 bit python 2.5.4

Not on
- Red Hat Enterprise 5 Linux, 64 bit python 2.5.4

First observed May 3 in version 2.0.0.dev8379

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-05

Probably due to r8377, possibly fixed in r8388. Can try it out?

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2010-05-06

Yes, it is fixed in 8388.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-06

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
