### ISSUE TITLE
test_universal_newline has string bug in python 3.1 (migrated from Trac #1479)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3031]
Original ticket http://projects.scipy.org/numpy/ticket/1479
Reported 2010-05-07 by atmention:charris, assigned to unknown.

```
ERROR: test_universal_newline (test_io.TestLoadTxt)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.1/site-packages/numpy/lib/tests/test_io.py", line 412, in test_universal_newline
    data = np.loadtxt(name)
  File "/usr/local/lib/python3.1/site-packages/numpy/lib/npyio.py", line 632, in loadtxt
    first_vals = split_line(first_line)
  File "/usr/local/lib/python3.1/site-packages/numpy/lib/npyio.py", line 610, in split_line
    line = line.split(comments)[0].strip()
TypeError: Can't convert 'bytes' object to str implicitly
```

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-08

Should be fixed in r8395

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
