### ISSUE TITLE
lapack interface handles non-native byte order in an invalid way (migrated from Trac #1482)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3034]
Original ticket http://projects.scipy.org/numpy/ticket/1482
Reported 2010-05-11 by atmention:yarikoptic, assigned to unknown.

Original report is at
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=581043

but now I've tested with current master: trunkatmention:8404 and issue present as well, e.g:

```
$> python -c "import numpy as N; print N.__version__;print N.linalg.cholesky(N.array([[ 5.7998084,  -2.1825367 ], [-2.1825367,   9.85910595]], dtype='>f8'))"
2.0.0.dev
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/yoh/proj/numpy/build/lib.linux-x86_64-2.5/numpy/linalg/linalg.py", line 517, in cholesky
    Cholesky decomposition cannot be computed'
numpy.linalg.linalg.LinAlgError: Matrix is not positive definite -         Cholesky decomposition cannot be computed

$> python -c "import numpy as N; print N.__version__;print N.linalg.cholesky(N.array([[ 5.7998084,  -2.1825367 ], [-2.1825367,   9.85910595]], dtype='<f8'))"
2.0.0.dev
[[ 2.40827914 -0.        ]
 [-0.90626401  3.00629199]]
```

myself I consider it of higher than normal priority since the issue is quite nastily veiled (some functions, e.g. svd would just produce bogus results) and I am surprised noone seems hit it by now.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-11

Good catch! Should be fixed in r8407.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-11

**Comment by thouis** [comment]
Comment in Trac by atmention:sandrotosi, 2010-06-30

Replying to [comment:1 pv]:

> Good catch! Should be fixed in r8407.

I've applied the patch against 1.4.1 but I still can see the problem: is there something else to do to make that patch work?

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-06-30

Replying to [comment:3 sandro.tosi]:

> Replying to [comment:1 pv]:
> 
> > Good catch! Should be fixed in r8407.
> 
> I've applied the patch against 1.4.1 but I still can see the problem: 
> is there something else to do to make that patch work?

You can see the problem how?

Check (see `numpy.__file__`) that you really are importing the newly built Numpy.
If in doubt, remove other Numpy installations.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
