### ISSUE TITLE
Delayed segfault in numpy + Python 2.4 (migrated from Trac #1483)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3035]
Original ticket http://projects.scipy.org/numpy/ticket/1483
Reported 2010-05-11 by atmention:pv, assigned to unknown.

Any ideas about this, ie. can someone with Python 2.4 reproduce it? 
Worksforme on Python 2.4.6. It's currently blocking the Scipy doc wiki from updating, so it would be nice to have it fixed.

Looks like a refcount bug somewhere in Numpy. Bisection search via git points that the first bad revision is r8262

```
Python 2.4.3 (#1, Jan 21 2009, 01:11:33) 
[GCC 4.1.2 20071124 (Red Hat 4.1.2-42)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy, scipy, gc
>>> numpy.__version__
'2.0.0.dev8404'
>>> scipy.__version__
'0.8.0.dev5623'
>>> import scipy.integrate
>>> gc.collect()
python: Modules/gcmodule.c:275: visit_decref: Assertion `gc->gc.gc_refs !
= 0' failed.

Program received signal SIGABRT, Aborted.
0x0000003238430215 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x0000003238430215 in raise () from /lib64/libc.so.6
#1  0x0000003238431cc0 in abort () from /lib64/libc.so.6
#2  0x0000003238429696 in __assert_fail () from /lib64/libc.so.6
#3  0x0000003c2e0b9c5c in ?? () from /usr/lib64/libpython2.4.so.1.0
#4  0x0000003c2e05a89d in ?? () from /usr/lib64/libpython2.4.so.1.0
#5  0x0000003c2e0ba157 in ?? () from /usr/lib64/libpython2.4.so.1.0
#6  0x0000003c2e0babf4 in ?? () from /usr/lib64/libpython2.4.so.1.0
#7  0x0000003c2e094747 in PyEval_EvalFrame ()
   from /usr/lib64/libpython2.4.so.1.0
#8  0x0000003c2e0958a5 in PyEval_EvalCodeEx ()
   from /usr/lib64/libpython2.4.so.1.0
#9  0x0000003c2e0958f2 in PyEval_EvalCode ()
   from /usr/lib64/libpython2.4.so.1.0
#10 0x0000003c2e0b1f29 in ?? () from /usr/lib64/libpython2.4.so.1.0
#11 0x0000003c2e0b37e7 in PyRun_InteractiveOneFlags ()
   from /usr/lib64/libpython2.4.so.1.0
#12 0x0000003c2e0b38de in PyRun_InteractiveLoopFlags ()
   from /usr/lib64/libpython2.4.so.1.0
#13 0x0000003c2e0b39ec in PyRun_AnyFileExFlags ()
   from /usr/lib64/libpython2.4.so.1.0
#14 0x0000003c2e0b980d in Py_Main () from /usr/lib64/libpython2.4.so.1.0
#15 0x000000323841d974 in __libc_start_main () from /lib64/libc.so.6
#16 0x0000000000400629 in _start ()
(gdb) q

(Yeah, debugging symbols missing ATM, but I guess the backtrace would be 
of little help anyway since the crash is nonlocal.)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-11

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-05-13

Fixed in r8408

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
