### ISSUE TITLE
numpydoc (sphinxext) broken by latest sphinx source. (migrated from Trac #1489)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3041]
Original ticket http://projects.scipy.org/numpy/ticket/1489
Reported 2010-05-22 by atmention:mforbes, assigned to atmention:pv.

The numpydoc (sphinxext) sphinx extension as of svn version 8426 is broken when used with the latest sphinx tip (2f0924a705b2).

The first hg version of sphinx where this starts failing is 98f9c2d6f51f where domains are introduced.  It is not clear to me right now how to fix this.

Using sphinx-quickstart and adding the 'numpydoc' extension (no other modifications to the defaults and including autodoc) gives the following:
    $ make html
    sphinx-build -b html -d _build/doctrees   . _build/html
    Making output directory...
    Running Sphinx v1.0pre

```
Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/6.0.4/lib/python2.6/site-packages/numpydoc-0.3.dev-py2.6.egg/numpydoc/numpydoc.py", line 137, in get_directive
    raise RuntimeError("No directive named '%s' found" % name)
RuntimeError: No directive named 'function' found
... 
make: *** [html] Error 1
```

Here is the traceback:
    # Sphinx version: 1.0pre
    # Docutils version: 0.6 release
    # Jinja2 version: 2.2.1
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/6.0.4/lib/python2.6/site-packages/Sphinx-1.0pre_2f0924a705b2dev_20100521-py2.6.egg/sphinx/cmdline.py", line 172, in main
        warningiserror, tags)
      File "/Library/Frameworks/Python.framework/Versions/6.0.4/lib/python2.6/site-packages/Sphinx-1.0pre_2f0924a705b2dev_20100521-py2.6.egg/sphinx/application.py", line 114, in **init**
        self.setup_extension(extension)
      File "/Library/Frameworks/Python.framework/Versions/6.0.4/lib/python2.6/site-packages/Sphinx-1.0pre_2f0924a705b2dev_20100521-py2.6.egg/sphinx/application.py", line 251, in setup_extension
        mod.setup(self)
      File "/Library/Frameworks/Python.framework/Versions/6.0.4/lib/python2.6/site-packages/numpydoc-0.3.dev-py2.6.egg/numpydoc/numpydoc.py", line 120, in setup
        app.add_directive('np-' + name, wrap_mangling_directive(name, objtype))
      File "/Library/Frameworks/Python.framework/Versions/6.0.4/lib/python2.6/site-packages/numpydoc-0.3.dev-py2.6.egg/numpydoc/numpydoc.py", line 140, in wrap_mangling_directive
        base_directive = get_directive(base_directive_name)
      File "/Library/Frameworks/Python.framework/Versions/6.0.4/lib/python2.6/site-packages/numpydoc-0.3.dev-py2.6.egg/numpydoc/numpydoc.py", line 137, in get_directive
        raise RuntimeError("No directive named '%s' found" % name)
    RuntimeError: No directive named 'function' found

**Comment by thouis** [comment]
Comment in Trac by trac user gruel, 2010-06-03

I do think that the problem is coming from the domain name http://sphinx.pocoo.org/latest/domains.html

I don't know what to change in numpydoc to introduce the new behavior.

**Comment by thouis** [comment]
Comment in Trac by atmention:matthew-brett, 2010-06-15

This is beyond my sphinx skills.

get_directive() from numpydoc does this:

```
def get_directive(name):
    from docutils.parsers.rst import directives
    try:
        return directives.directive(name, None, None)[0]
    except AttributeError:
        pass
    try:
        # docutils 0.4
        return directives._directives[name]
    except (AttributeError, KeyError):
        raise RuntimeError("No directive named '%s' found" % name)
```

The '''directives.directive(name, None, None)''' call does not look as if it could have worked with docutils 0.3 or later, maybe earlier, so in practice the code is always falling back to the '''return directives._directives[name]''' line.  The function directive that we are looking for is always put into the '''_directives''' cache by sphinx.directives.desc:

```
directives.register_directive('function', directive_dwim(ModulelevelDesc))
```

through sphinx 0.6.7 and up until the 1.0 beta, at which point, sphinx switches to the domains idea pointed to above, the 'function' directive is no longer in the docutils '''_directives''' cache, and the numpydoc extension therefore fails.

The 'function' directive appears to be defined in sphinx.domains.python, but not registered with the '''register_directive''' call.

**Comment by thouis** [comment]
Comment in Trac by trac user howarn, 2010-07-29

**Comment by thouis** [comment]
Comment in Trac by trac user howarn, 2010-07-29

Maybe, I find temporary decision:

http://bitbucket.org/birkenfeld/sphinx/issue/477/function-directive-not-registered#comment-222937

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-07-29

The best fix is probably to scrap the `np-function` et al. directives. I doubt many people are using those.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-07-29

Fixed in r8549

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-10-06
