### ISSUE TITLE
Make nose --detailed-errors optional (migrated from Trac #1498)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3050]
Original ticket http://projects.scipy.org/numpy/ticket/1498
Reported 2010-05-30 by atmention:jseabold, assigned to unknown.

Right now the use of the --detailed-errors flag for assert introspection in nose tests is not optional.  I have attached a patch to make it optional.  The default behavior of using introspection is not changed (though maybe it should be?), as it is useful for the build bots.  I find it to be extra noise while debugging tests though.

Consider a failure with detailed errors flag in scipy r6447:
scipy.test()

```
======================================================================
FAIL: test_mio.test_mat4_3d(<type 'exceptions.DeprecationWarning'>, <functools.partial object at 0x479a418>, <StringIO.StringIO instance at 0x753c6c8>, {'a': array([[[ 0,  1,  2,  3],
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/usr/local/lib/python2.6/dist-packages/numpy/testing/utils.py", line 982, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
AssertionError: DeprecationWarning not raised
    if hasattr(excClass,'__name__'): 'DeprecationWarning' = excClass.'unittest'
    else: 'DeprecationWarning' = str(excClass)
>>  raise self.failureException, "%s not raised" % 'DeprecationWarning'
```

The same one without the flag:
scipy.test(extra_argv=[])
    ======================================================================
    FAIL: test_mio.test_mat4_3d(<type 'exceptions.DeprecationWarning'>, <functools.partial object at 0x479a418>, <StringIO.StringIO instance at 0x6ac1248>, {'a': array([[[ 0,  1,  2,  3],
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/local/lib/python2.6/dist-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
        self.test(_self.arg)
      File "/usr/local/lib/python2.6/dist-packages/numpy/testing/utils.py", line 982, in assert_raises
        return nose.tools.assert_raises(_args,**kwargs)
    AssertionError: DeprecationWarning not raised

**Comment by thouis** [comment]
Attachment in Trac by atmention:jseabold, 2010-05-30: [diff.txt](http://projects.scipy.org/numpy/attachment/ticket/1498/diff.txt)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-09-21

That flag was removed in commit:d5382aa64.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31
