### ISSUE TITLE
numpy.random.permutations fails for non-integer arguments (migrated from Trac #1535)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3087]
Original ticket http://projects.scipy.org/numpy/ticket/1535
Reported 2010-07-05 by atmention:robince, assigned to unknown.

When calling numpy.random.permutation with non-integer arguments it fails with a cryptic error message:

```
In [49]: np.random.permutation(12)
Out[49]: array([10,  9,  4,  7,  3,  8,  0,  6,  5,  1, 11,  2])

In [50]: np.random.permutation(12.0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)

D:\robin\pyentropy-0.4.0\<ipython console> in <module>()

C:\Python26\lib\site-packages\numpy\random\mtrand.pyd in mtrand.RandomState.permutation (build\scons\numpy\random\mtrand
\mtrand.c:18669)()

C:\Python26\lib\site-packages\numpy\random\mtrand.pyd in mtrand.RandomState.shuffle (build\scons\numpy\random\mtrand\mtr
and.c:18261)()

TypeError: len() of unsized object
> d:\robin\pyentropy-0.4.0\mtrand.pyx(4174)mtrand.RandomState.shuffle (build\scons\numpy\random\mtrand\mtrand.c:18261)()
```

This also happens with long arguments, and so np.random.permutation(X.shape[0]) where X is an array fails on 64 bit windows (where shape is a tuple of longs).

It would be great if it could cast to integer or at least raise a proper error for non-integer types.

**Comment by thouis** [comment]
Comment in Trac by atmention:vincentdavis, 2010-07-05

 np.random.permutation(num) It appears that num needs to be an integer (not converted from float), in the case of the X.shape[0] 
I think this is because numpy does not have a dtype "long" rather it is an object.
Also if type(num)='Long' than np.random.permutation(num) fails

```
>>> x = 10000000000000000000
>>> type(x)
<type 'long'>
>>> np.random.permutation(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4233, in mtrand.RandomState.permutation (build/scons/numpy/random/mtrand/mtrand.c:18875)
  File "mtrand.pyx", line 4176, in mtrand.RandomState.shuffle (build/scons/numpy/random/mtrand/mtrand.c:18466)
TypeError: len() of unsized object
```

But these errors are different than just choosing too large int, in that case the error is 

```
>>> x = 1000000000000000000
>>> type(x)
<type 'int'>
>>> np.random.permutation(x)
Python(9434) malloc: *** mmap(size=8000000000000000000) failed (error code=12)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4230, in mtrand.RandomState.permutation (build/scons/numpy/random/mtrand/mtrand.c:18823)
MemoryError



>>> x = np.array([1,2,3], dtype=float)
>>> np.random.permutation(x[1])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4233, in mtrand.RandomState.permutation (build/scons/numpy/random/mtrand/mtrand.c:18875)
  File "mtrand.pyx", line 4176, in mtrand.RandomState.shuffle (build/scons/numpy/random/mtrand/mtrand.c:18466)
TypeError: len() of unsized object
```

**Comment by thouis** [comment]
Comment in Trac by atmention:cgohlke, 2010-07-06

How about this?

```
Index: mtrand.pyx
===================================================================
--- mtrand.pyx  (revision 8469)
+++ mtrand.pyx  (working copy)
atmention:atmention: -4226,10 +4226,10 atmention:atmention:
         array([15,  1,  9,  4, 12])

         """
-        if isinstance(x, (int, np.integer)):
+        if hasattr(x, '__iter__'):
+            arr = np.array(x)
+        else:
             arr = np.arange(x)
-        else:
-            arr = np.array(x)
         self.shuffle(arr)
         return arr


>>> x = np.array([1,2,3], dtype=float)
>>> np.random.permutation(x[1])
array([ 0.,  1.])
>>> type(x.shape[0])
<type 'long'>
>>> np.random.permutation(x.shape[0])
array([0, 2, 1], dtype=int64)


>>> x = 10000000000000000000
>>> type(x)
<type 'long'>
>>> np.random.permutation(x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 4232, in mtrand.RandomState.permutation 
  (build\scons\numpy\random\mtrand\mtrand.c:18840)
ValueError: Maximum allowed size exceeded
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:cgohlke, 2010-07-06: [mtrand.diff](http://projects.scipy.org/numpy/attachment/ticket/1535/mtrand.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-07-09

Fixed in r8474

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
