### ISSUE TITLE
MSVC specific TypeError when using double, longdouble in numpy.dot (migrated from Trac #1539)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3091]
Original ticket http://projects.scipy.org/numpy/ticket/1539
Reported 2010-07-08 by atmention:cgohlke, assigned to unknown.

This issue has been discussed at [http://mail.scipy.org/pipermail/numpy-discussion/2010-July/051352.html] and is the cause of the scipy.sparse TypeError test failures reported at [http://mail.scipy.org/pipermail/scipy-user/2010-July/025961.html].

Using Python 2.6.5 32 bit on Windows and numpy 1.4.1 built with Visual Studio 2008 (msvc9), I get the following:

```
>>> a = numpy.array([[1.0]])
>>> numpy.dot(a.astype('double'), a.astype('longdouble'))
array([[ 1.]]) 

>>> a = numpy.array([[1]])
>>> numpy.dot(a.astype('double'), a.astype('longdouble'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: array cannot be safely cast to required type

>>> a = numpy.array([[1]])
>>> numpy.dot(a.astype('single'), a.astype('longdouble'))
array([[1.0]], dtype=float64)

>>> a = numpy.array([[1]])
>>> numpy.dot(a.astype('longdouble'), a.astype('double'))
array([[1.0]], dtype=float64) 

>>> numpy.array([1]).astype('longdouble').dtype.num
13
>>> numpy.array([1.0]).astype('longdouble').dtype.num
12 
```

The TypeError is unexpected. The same results are obtained when using a msvc7 build of numpy 1.4.1 on Python 2.5, or a msvc9 64 bit build of numpy 2.0.dev on Python 3.1.

Using numpy 1.4.1 built with mingw does not raise a TypeError:

```
>>> a = numpy.array([[1]])
>>> numpy.dot(a.astype('double'), a.astype('longdouble'))
array([[1.0]], dtype=float96)
```

Note that for MSVC compilers sizeof(longdouble) = sizeof(double) = 8

**Comment by thouis** [comment]
Attachment in Trac by atmention:cgohlke, 2010-07-08: [test_issue1539.py](http://projects.scipy.org/numpy/attachment/ticket/1539/test_issue1539.py)

**Comment by thouis** [comment]
Comment in Trac by atmention:cgohlke, 2010-07-08

The attached test passes on mingw/gcc and fails on msvc builds:

```
ERROR: Test for issue #1539.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\test_issue1539.py", line 16, in test_issue1539
    np.dot(b, c)
TypeError: array cannot be safely cast to required type
-------------------- >> begin captured stdout << ---------------------
TypeError: array cannot be safely cast to required type (12, 13)
TypeError: array cannot be safely cast to required type (15, 16)

--------------------- >> end captured stdout << ----------------------
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:cgohlke, 2010-07-08: [convert_datatype.diff](http://projects.scipy.org/numpy/attachment/ticket/1539/convert_datatype.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:cgohlke, 2010-07-08

The convert_datatype.diff patch fixes the issue.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-07-09

Thanks, applied in r8477

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
