### ISSUE TITLE
atleast_?d() breaks masked arrays (migrated from Trac #1559)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3111]
Original ticket http://projects.scipy.org/numpy/ticket/1559
Reported 2010-07-27 by atmention:WeatherGod, assigned to atmention:pierregm.

calling a function like .atleast_2d() to change the number of dimensions an array has can break the original masked array object.  See the following example using a 1d masked array:
    >>> import numpy
    >>> a = numpy.ma.masked_array([0.0, 1.2, 3.5], mask=[False, True, False])
    >>> b = numpy.atleast_2d(a)
    >>> b
    masked_array(data =
     [[0.0 -- 3.5]],
                 mask =
     [[False  True False]],
           fill_value = 1e+20)

```
>>> a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bvr/Programs/numpy/numpy/ma/core.py", line 3570, in __repr__
    data=str(self), mask=str(self._mask),
  File "/home/bvr/Programs/numpy/numpy/ma/core.py", line 3554, in __str__
    res[m] = f
ValueError: boolean index array should have 1 dimension
>>>
```

The problem does not occur if there is no change to the number of dimensions.

**Comment by thouis** [comment]
Comment in Trac by atmention:WeatherGod, 2010-07-27

Addendum: it does not appear that .atleast_3d() breaks the array.

**Comment by thouis** [comment]
Attachment in Trac by atmention:WeatherGod, 2010-07-27: [atleast_breaksmasks.patch](http://projects.scipy.org/numpy/attachment/ticket/1559/atleast_breaksmasks.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:WeatherGod, 2010-07-27

Please note that the attached patch may cause conflicts with the proposed patch in ticket #1560 at the import line.

Also, there is probably a much better way to deal with atleast_1d() and atleast_2d() than what I have here, but this does work AFAICT.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-07-27

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-08-10

Mmh, this illustrates an actual obscure bug.
See, in **array_finalize**(self, obj), we set self._mask to obj._mask (if any), and then set self._mask.shape to self.shape. The second step is required to make sure that setting the shape in place (like in self.shape=newshape) updates the shape of the mask.
Except that in the np.atleast_nd case, this step also updates obj._mask, which we don't want... 
In fact, we should take a view of obj._mask and update this one, but that breaks setting the shape in place...

So, the solution being proposed is rather a monkeypatch than a real fix. Let me try to figure this one out, at worst we'll use that patch as a back-up plan.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-11-22

Hi Pierre,

I put this patch up as a pull request on github if you want to apply it.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-30

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-04-02

Pierre, I went ahead and committed the patch. If you want to make a better fix open another ticket.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31
