### ISSUE TITLE
Python3.2a1 errors (migrated from Trac #1571)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3123]
Original ticket http://projects.scipy.org/numpy/ticket/1571
Reported 2010-08-03 by atmention:bsouthey, assigned to unknown.

First, string.maketrans function that was depreciated in Python 3.1 was removed in Python3.2.
http://docs.python.org/dev/py3k/whatsnew/3.2.html

Consequently a minor change is needed in line 116 of
numpy/core/code_generators/generate_umath.py

After doing that, the build on Linux 64 bit, python3.2 crashes due to 'undefined symbol: PyCObject_AsVoidPtr'.

```
$ python3.2 -c "import numpy; numpy.test()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.2/site-packages/numpy/__init__.py", line 136, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.2/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.2/site-packages/numpy/lib/__init__.py", line 4, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.2/site-packages/numpy/lib/type_check.py", line 8, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.2/site-packages/numpy/core/__init__.py", line 5, in <module>
    from . import multiarray
ImportError: /usr/local/lib/python3.2/site-packages/numpy/core/multiarray.so: undefined symbol: PyCObject_AsVoidPtr
```

From the build logs, this is appears to be this section:

```
In file included from /usr/local/include/python3.2/Python.h:8,
                 from numpy/core/src/multiarray/common.c:2,
                 from numpy/core/src/multiarray/multiarraymodule_onefile.c:8:
/usr/local/include/python3.2/pyconfig.h:137:1: warning: this is the location of the previous definition
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:14:
numpy/core/src/multiarray/arraytypes.c.src: In function ‘VOID_getitem’:
numpy/core/src/multiarray/arraytypes.c.src:633: warning: assignment from incompatible pointer type
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:21:
numpy/core/src/multiarray/ctors.c: In function ‘_array_from_buffer_3118’:
numpy/core/src/multiarray/ctors.c:1656: warning: assignment from incompatible pointer type
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:25:
numpy/core/src/multiarray/getset.c: In function ‘array_data_get’:
numpy/core/src/multiarray/getset.c:283: warning: passing argument 1 of ‘PyMemoryView_FromObject’ from incompatible pointer type
/usr/local/include/python3.2/memoryobject.h:54: note: expected ‘struct PyObject *’ but argument is of type ‘struct PyArrayObject *’
In file included from numpy/core/src/multiarray/multiarraymodule_onefile.c:28:
numpy/core/src/multiarray/convert_datatype.c: In function ‘PyArray_GetCastFunc’:
numpy/core/src/multiarray/convert_datatype.c:106: warning: implicit declaration of function ‘PyCObject_AsVoidPtr’
numpy/core/src/multiarray/convert_datatype.c:106: warning: assignment makes pointer from integer without a cast
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:bsouthey, 2010-08-03: [generate_umath.diff](http://projects.scipy.org/numpy/attachment/ticket/1571/generate_umath.diff)

**Comment by thouis** [comment]
Attachment in Trac by atmention:bsouthey, 2010-08-03: [python3.2_build.log](http://projects.scipy.org/numpy/attachment/ticket/1571/python3.2_build.log)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-08-03

Fixed in r8588 & r8589. Thanks!

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
