### ISSUE TITLE
FloatingPointError: invalid value encountered in isfinite (migrated from Trac #1572)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3124]
Original ticket http://projects.scipy.org/numpy/ticket/1572
Reported 2010-08-04 by trac user nwatanabe, assigned to atmention:pierregm.

numpy.ma.log10([0.0]) raises an unexpected FloatingPointError in NumPy v1.4.1:

```
>>> j = numpy.seterr(invalid='ignore')
>>> numpy.log10(0.0)
-inf
>>> numpy.ma.log10([0.0])
masked_array(data = [--],
             mask = [ True],
       fill_value = 1e+20)

>>> j = numpy.seterr(invalid='raise')
>>> numpy.log10(0.0)
-inf
>>> numpy.ma.log10([0.0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/apps/python/2.6.5/lib/python2.6/site-packages/numpy/ma/core.py", line 856, in __call__
    m = ~umath.isfinite(result)
FloatingPointError: invalid value encountered in isfinite
```

**Comment by thouis** [comment]
Comment in Trac by atmention:pierregm, 2010-08-09
- Already fixed in 1.5.x and above.
