### ISSUE TITLE
1.5.0b1 umath complex failures on Windows (migrated from Trac #1574)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3126]
Original ticket http://projects.scipy.org/numpy/ticket/1574
Reported 2010-08-08 by atmention:rgommers, assigned to unknown.

Reported on Windows with Python 2.7 by two people with the 1.5.0b1 binary.

```
Python 2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.test()
Running unit tests for numpy
NumPy version 1.5.0b1
NumPy is installed in C:\Python27\lib\site-packages\numpy
Python version 2.7 (r27:82525, Jul  4 2010, 09:01:59) [MSC v.1500 32 bit (Intel)]
nose version 0.11.0
..........................................................................................
....................E.....................................................................
..........................................................................................
..........................................................................................
..........................................................................................
.....................K....................................................................
..........................................................................................
..................................................................K.......................
...................................K..K.............Warning: invalid value encountered in
absolute
.Warning: invalid value encountered in absolute
................K........F....FFFF.....K.F.........FF..FFF.....F..........................
......................................................S...................................
..........................................................................................
..........................................................................................
..........................................................................................
..........................................................................................
.......................................K.........K........................................
..........................................................................................
..........................................................................................
..........................................................................................
..........................................................................................
..........................................S...............................................
..........................................................................................
..........................................................................................
..........................................................................................
..........................................................................................
..........................................................................................
..........................................................................................
................................................................
======================================================================
ERROR: test_filename (test_memmap.TestMemmap)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_memmap.py", line 60, in test_f
ilename
    os.unlink(tmpname)
WindowsError: [Error 32] The process cannot access the file because it is being used by an
other process: 'c:\\users\\alanis~1\\appdata\\local\\temp\\mmapoo5c2b'

======================================================================
FAIL: test_umath_complex.TestCexp.test_special_values(<ufunc 'exp'>, inf, 0, inf, 0)
test_umath_complex.TestCexp.test_special_values(<ufunc 'exp'>, inf, 0, inf, 0)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 539, i
n check_complex_value
    assert_equal(f(z1), z2)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 686, in assert_array_e
qual
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 596, in assert_array_c
ompare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(x and y nan location mismatch [ True], False mismatch)
 x: array([ inf nanj])
 y: array((inf+0j))
>>  raise AssertionError('\nArrays are not equal\n\n(x and y nan location mismatch [ True]
, False mismatch)\n x: array([ inf nanj])\n y: array((inf+0j))')


======================================================================
FAIL: test_umath_complex.TestCexp.test_special_values(None,)
test_umath_complex.TestCexp.test_special_values(None,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 60, in
 _check_ninf_inf
    raise AssertionError(msgform %(z.real, z.imag))
AssertionError: cexp(-inf, inf) is (nan, nan), expected (+-0, +-0)
>>  raise AssertionError('cexp(-inf, inf) is (%f, %f), expected (+-0, +-0)' %((nan+nan*j).
real, (nan+nan*j).imag))


======================================================================
FAIL: test_umath_complex.TestCexp.test_special_values(None,)
test_umath_complex.TestCexp.test_special_values(None,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 73, in
 _check_inf_inf
    raise AssertionError(msgform % (z.real, z.imag))
AssertionError: cexp(inf, inf) is (nan, nan), expected (+-inf, nan)
>>  raise AssertionError('cexp(inf, inf) is (%f, %f), expected (+-inf, nan)' % ((nan+nan*j
).real, (nan+nan*j).imag))


======================================================================
FAIL: test_umath_complex.TestCexp.test_special_values(None,)
test_umath_complex.TestCexp.test_special_values(None,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 86, in
 _check_ninf_nan
    raise AssertionError(msgform % (z.real, z.imag))
AssertionError: cexp(-inf, nan) is (nan, nan), expected (+-0, +-0)
>>  raise AssertionError('cexp(-inf, nan) is (%f, %f), expected (+-0, +-0)' % ((nan+nan*j)
.real, (nan+nan*j).imag))


======================================================================
FAIL: test_umath_complex.TestCexp.test_special_values(None,)
test_umath_complex.TestCexp.test_special_values(None,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 99, in
 _check_inf_nan
    raise AssertionError(msgform % (z.real, z.imag))
AssertionError: cexp(-inf, nan) is (nan, nan), expected (+-inf, nan)
>>  raise AssertionError('cexp(-inf, nan) is (%f, %f), expected (+-inf, nan)' % ((nan+nan*
j).real, (nan+nan*j).imag))


======================================================================
FAIL: test_special_values (test_umath_complex.TestClog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 144, i
n test_special_values
    self.assertRaises(FloatingPointError, np.log, x)
AssertionError: FloatingPointError not raised


======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, 1, inf, inf, inf)
test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, 1, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 539, i
n check_complex_value
    assert_equal(f(z1), z2)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 686, in assert_array_e
qual
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 596, in assert_array_c
ompare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(x and y nan location mismatch [ True], False mismatch)
 x: array([ inf nanj])
 y: array((inf+infj))
>>  raise AssertionError('\nArrays are not equal\n\n(x and y nan location mismatch [ True]
, False mismatch)\n x: array([ inf nanj])\n y: array((inf+infj))')


======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, -1, inf, inf, inf)
test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, -1, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 539, i
n check_complex_value
    assert_equal(f(z1), z2)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 686, in assert_array_e
qual
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 596, in assert_array_c
ompare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(x and y nan location mismatch [ True], False mismatch)
 x: array([ nan infj])
 y: array((inf+infj))
>>  raise AssertionError('\nArrays are not equal\n\n(x and y nan location mismatch [ True]
, False mismatch)\n x: array([ nan infj])\n y: array((inf+infj))')


======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, inf, inf, inf, inf)

test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, inf, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 539, i
n check_complex_value
    assert_equal(f(z1), z2)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 686, in assert_array_e
qual
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 596, in assert_array_c
ompare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(x and y nan location mismatch [ True], False mismatch)
 x: array([ inf nanj])
 y: array((inf+infj))
>>  raise AssertionError('\nArrays are not equal\n\n(x and y nan location mismatch [ True]
, False mismatch)\n x: array([ inf nanj])\n y: array((inf+infj))')


======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, -inf, inf, inf, inf
)
test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, -inf, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 539, i
n check_complex_value
    assert_equal(f(z1), z2)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 686, in assert_array_e
qual
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 596, in assert_array_c
ompare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(x and y nan location mismatch [ True], False mismatch)
 x: array([ nan infj])
 y: array((inf+infj))
>>  raise AssertionError('\nArrays are not equal\n\n(x and y nan location mismatch [ True]
, False mismatch)\n x: array([ nan infj])\n y: array((inf+infj))')


======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, nan, inf, inf, inf)

test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, nan, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 539, i
n check_complex_value
    assert_equal(f(z1), z2)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 686, in assert_array_e
qual
    verbose=verbose, header='Arrays are not equal')
  File "C:\Python27\lib\site-packages\numpy\testing\utils.py", line 596, in assert_array_c
ompare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(x and y nan location mismatch [ True], False mismatch)
 x: array([ nan nanj])
 y: array((inf+infj))
>>  raise AssertionError('\nArrays are not equal\n\n(x and y nan location mismatch [ True]
, False mismatch)\n x: array([ nan nanj])\n y: array((inf+infj))')


======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(None,)
test_umath_complex.TestCsqrt.test_special_values(None,)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\case.py", line 183, in runTest
    self.test(*self.arg)
  File "C:\Python27\lib\site-packages\numpy\core\tests\test_umath_complex.py", line 340, i
n _check_ninf_nan
    raise AssertionError(msgform % (z.real, z.imag))
AssertionError: csqrt(-inf, nan) is (nan, nan), expected (nan, +-inf)
>>  raise AssertionError('csqrt(-inf, nan) is (%f, %f), expected (nan, +-inf)' % ((nan+nan
*j).real, (nan+nan*j).imag))


----------------------------------------------------------------------
Ran 2456 tests in 19.070s

FAILED (KNOWNFAIL=8, SKIP=2, errors=1, failures=12)
<nose.result.TextTestResult run=2456 errors=1 failures=12>
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:rgommers, 2010-08-08: [build-py27.log](http://projects.scipy.org/numpy/attachment/ticket/1574/build-py27.log)

**Comment by thouis** [comment]
Attachment in Trac by atmention:rgommers, 2010-08-08: [build-py26.log](http://projects.scipy.org/numpy/attachment/ticket/1574/build-py26.log)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-08-08

Yep, `HAVE_CSQRT`, `HAVE_CEXP`, et al. are defined, so it's using the platform-provided routines. And those appear to be buggy on that platform.

It's not so clear how to fix this:

1) It's a bug, but,

2) it's not a bug in Numpy,

3) Probably, most users won't care if `exp(inf+0j) == inf+0j` or `inf+nanj`.

One could re-check that the results in `test_umath_complex.py` are specified by C99 as mandatory and not as optional, though.

If we want to provide reliable corner-case behavior on all platforms, we should check some simple cases on compile time.

But if we don't really care, we could as well add a check in `test_umath_complex.py` that sets
    functions_seem_flaky = (np.exp(complex(np.inf, 0)).imag != 0)
    skip_complex_tests = have_platform_functions and functions_seem_flaky

```
def platform_skip(func):
    return dec.skipif(skip_complex_tests, 
        "Numpy is using complex functions (e.g. sqrt) provided by your platform's C library. "
        "However, they do not seem to behave according to C99 -- so C99 tests are skipped.")(func)
```

and sprinkle `platform_skip` to all C99-specific tests. I'm not sure how to best check for the platform functions though.

I think just skipping these tests is a sensible option.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-08-10

These things are defined in sec. G of the C99 spec, which starts:
''This annex supplements annex F to specify complex arithmetic for compatibility with IEC 60559 real floating-point arithmetic. Although these specifications have been carefully designed, there is little existing practice to validate the design decisions. Therefore, these specifications are not normative, but should be viewed more as recommended practice. An implementation that defines {{{**STDC_IEC_559_COMPLEX**}}} should conform to the specifications in this annex.''

So it depends. I agree skipping these tests is fine.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-08-14

Is there a way right now for nose to figure out your have_platform_functions? Maybe this requires build info to be available at runtime. Like: http://projects.scipy.org/scipy/ticket/961

For 1.5 shall we just skip them on Windows only?

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-08-14

like so: http://github.com/rgommers/numpy/commit/5bf28c24144ae4fa20f117725239a33c64e1393d

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-09-21

Applied in commit:6037fd4. Case closed I think.
