### ISSUE TITLE
format gives ValueError when passed float32 (migrated from Trac #1575)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3127]
Original ticket http://projects.scipy.org/numpy/ticket/1575
Reported 2010-08-09 by trac user crm, assigned to unknown.

Passing a float32 to the inbuilt format function returns a value error:

```
>>> format(np.float32(1.23),'.1f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Unknown format code 'f' for object of type 'str'
```

float64 works as expected:
    >>> format(np.float64(1.23),'.1f')
    '1.2'

python version: 2.6.5[[BR]]
numpy version: 1.4.1[[BR]]
OS: WindowsXP

**Comment by thouis** [comment]
Comment in Trac by trac user kisielk, 2011-08-05

Any word on this issue? Seems to still affect current versions. Do numpy dtypes implement their own `__format__` or do they rely on being coerced in to the appropriate Python intrinsic types for formatting?

**Comment by thouis** [comment]
Comment in Trac by trac user pfctdayelise, 2011-11-16

It's not just Windows, also on Linux (Fedora 14) with Python 2.7.1.

> > > 'hello {:.1f}'.format(1.39)
> > > 'hello 1.4'
> > > 
> > > 'hello {:.1f}'.format(np.float64(1.39))
> > > 'hello 1.4'
> > > 
> > > 'hello {:.1f}'.format(np.float32(1.39))
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ValueError: Unknown format code 'f' for object of type 'str'

**Comment by thouis** [comment]
Comment in Trac by trac user pfctdayelise, 2011-11-16

hmm.... unexpectedly using the old-style "%" formatting works:

> > > 'hello %.1f' % (1.39)
> > > 'hello 1.4'
> > > 
> > > 'hello %.1f' % (np.float64(1.39))
> > > 'hello 1.4'
> > > 
> > > 'hello %.1f' % (np.float32(1.39))
> > > 'hello 1.4'

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-11-16

This looks to have been fixed. With current master and Python 2.7.2

```
In [1]: 'hello {:.1f}'.format(np.float32(1.39))
Out[1]: 'hello 1.4'

In [2]: 'hello {:.1f}'.format(np.float64(1.39))
Out[2]: 'hello 1.4'

In [3]: 'hello {:.1f}'.format(np.float16(1.39))
Out[3]: 'hello 1.4'
```

I expect things should work for the 1.6.x release also, but I haven't tested it.
