### ISSUE TITLE
fromfile/tofile py3k errors on Windows (migrated from Trac #1583)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3135]
Original ticket http://projects.scipy.org/numpy/ticket/1583
Reported 2010-08-14 by atmention:rgommers, assigned to unknown.

In total 38 errors (see attached), all like this:
    ======================================================================
    ERROR: test_multiarray.TestIO.test_ascii
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "Z:\Users\rgommers.wine\drive_c\Python31\lib\site-packages\nose-3.0.0.dev-py3.1.egg\nose\case.py", line 178, in runTest
        self.test(_self.arg)
      File "Z:\Users\rgommers.wine\drive_c\Python31\lib\site-packages\numpy\core\tests\test_multiarray.py", line 1017, in test_ascii
        self._check_from('1 , 2 , 3 , 4', [1.,2.,3.,4.], sep=',')
      File "Z:\Users\rgommers.wine\drive_c\Python31\lib\site-packages\numpy\core\tests\test_multiarray.py", line 980, in _check_from
        y = np.fromfile(self.filename, *_kw)
    IOError: first argument must be an open file

```
======================================================================
ERROR: test_multiarray.TestIO.test_ascii
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Z:\Users\rgommers\.wine\drive_c\Python31\lib\site-packages\nose-3.0.0.dev-py3.1.egg\nose\case.py", line 370, in tearDown
    try_run(self.inst, ('teardown', 'tearDown'))
  File "Z:\Users\rgommers\.wine\drive_c\Python31\lib\site-packages\nose-3.0.0.dev-py3.1.egg\nose\util.py", line 469, in try_run
    return func()
  File "Z:\Users\rgommers\.wine\drive_c\Python31\lib\site-packages\numpy\core\tests\test_multiarray.py", line 918, in tearDown
    os.unlink(self.filename)
WindowsError: [Error 32] Sharing violation: 'z:\\var\\folders\\uu\\uuxfo1nlfae4yyypscz-xe+++ti\\-tmp-\\tmpdtktwh'
```

Looks like #1345 is related.

**Comment by thouis** [comment]
Attachment in Trac by atmention:rgommers, 2010-08-14: [fromtofile_errors.txt](http://projects.scipy.org/numpy/attachment/ticket/1583/fromtofile_errors.txt)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-08-22

This problem does not occur when compiling with MSVC, as reported by Christoph Gohlke.

**Comment by thouis** [comment]
Comment in Trac by atmention:cgohlke, 2010-08-24

I could reproduce this with MinGW 5.1.6.

The function call "fdopen(fd2, mode)" in line 181 of npy_3kcompat.h returns NULL even though the input parameters seem correct. As a consequence the result of the npy_PyFile_Dup call in line 1694 of multiarraymodule.c is NULL and the exception is raised.

Could this be related to mixing two different C runtime libraries: msvcrt90/Python and msvcrt/mingw? Even though the -lmsvcr90 linker option is set, the resulting pyd files depend on the two runtime dlls. 

I'll try the get_osfhandle workaround mentioned at [http://mail.python.org/pipermail/python-list/2007-March/1102307.html]

**Comment by thouis** [comment]
Comment in Trac by atmention:cgohlke, 2010-08-24

Using osfhandle did not work for mingw. Same failures. Seems that it's not a crt issue. For the records, in the npy_PyFile_Dup function in npy_3kcompat.h I tried (error handling omitted):

```
PyObject_CallMethod(file, "flush", "");

/* get osfhandle using Python/msvcrt90 */
fd = PyObject_AsFileDescriptor(file);
msvcrt = PyImport_ImportModule("msvcrt");
ret = PyObject_CallMethod(msvcrt, "get_osfhandle", "i", fd);
fh = PyNumber_AsSsize_t(ret, 0);

/* get FILE* from osfhandle using mingw/msvcrt */
fd2 = _open_osfhandle(fh, 0); /* TODO: second parameter should match mode */
return fdopen(fd2, mode);
```

This code works with msvc9 (aside from the TODO).

**Comment by thouis** [comment]
Comment in Trac by atmention:cgohlke, 2010-08-24

This page [http://www.pygame.org/wiki/PreparingMinGW] gave the clue. _fdopen is the correct function to use. fdopen is linked to the old msvcrt even though the -lmsvcr90 option is set. fclose and _fdopen are linked to libmsvcr90.

A patch is attached.

**Comment by thouis** [comment]
Attachment in Trac by atmention:cgohlke, 2010-08-24: [fdopen.patch](http://projects.scipy.org/numpy/attachment/ticket/1583/fdopen.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-08-24

Looks straight forward. I'll apply it in a day or two unless Ralf or Pauli want to handle it differently.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-08-24

Looks good to me. Thanks a lot for tracking that down!

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-08-25

I want to get an RC out tonight, so committed already, in r8665 and r8666.
