### ISSUE TITLE
loadtxt gets stuck on empty files (migrated from Trac #1597)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3148]
Original ticket http://projects.scipy.org/numpy/ticket/1597
Reported 2010-09-01 by trac user ctmedra, assigned to unknown.

I have found that loadtxt gets stuck on empty files. 
My numpy.**version**  is  '1.2.1'

For instance:

In [1]: import numpy

In [2]: fp=open('foo.dat','w')

In [3]: fp.close()

In [4]: numpy.loadtxt('foo.dat')

then I wait with no answer.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-09-05

Has been fixed since then:
    >>> import numpy
    >>> fp=open('foo.dat','w') 
    >>> fp.close() 
    >>> numpy.loadtxt('foo.dat') 
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python2.6/dist-packages/numpy/lib/io.py", line 456, in loadtxt
        raise IOError('End-of-file reached before encountering data.')
    IOError: End-of-file reached before encountering data.
    >>> numpy.**version**
    '1.3.0'
