### ISSUE TITLE
numpy.genfromtxt() with Python 3.1.2 fails (migrated from Trac #1607)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3158]
Original ticket http://projects.scipy.org/numpy/ticket/1607
Reported 2010-09-09 by trac user magiclamp, assigned to unknown.

Hello:

genfromtxt() fails with the following TypeError.

Thanks for the nice package!

[search_dist][10273] > cat z.dat 

0.01604 0.02668         0.03254 0.03254         0.15647 0.20313         0.02214 0.02214

[search_dist][10274] > python

Python 3.1.2 (r312:79147, Sep  2 2010, 17:16:43) 

[GCC 4.5.0] on linux2

Type "help", "copyright", "credits" or "license" for more information.

> > > import numpy 
> > > 
> > > numpy.version.version

'1.5.0'

> > > numpy.genfromtxt('z.dat')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/intel/pkgs/python/3.1.2/lib/python3.1/site-packages/numpy/lib/npyio.py", line 1126, in genfromtxt
    first_values = split_line(first_line)
  File "/usr/intel/pkgs/python/3.1.2/lib/python3.1/site-packages/numpy/lib/_iotools.py", line 206, in _delimited_splitter
    line = line.split(self.comments)[0].strip(asbytes(" \r\n"))
TypeError: Can't convert 'bytes' object to str implicitly

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-03-04

**Comment by thouis** [comment]
Comment in Trac by atmention:matthew-brett, 2011-03-30

Proposed fix to open passed filenames as binary.

https://github.com/numpy/numpy/pull/64

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-03-31

Applied in 706c9b6.
