### ISSUE TITLE
FAIL: test_complex_scalar_warning (test_regression.TestRegression) (migrated from Trac #1639)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3190]
Original ticket http://projects.scipy.org/numpy/ticket/1639
Reported 2010-10-14 by atmention:stsci-sienkiew, assigned to atmention:pv.

```
======================================================================
FAIL: test_complex_scalar_warning (test_regression.TestRegression)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_regression.py", line 1407, in test_complex_scalar_warning
    assert_warns(np.ComplexWarning, float, x)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/utils.py", line 1432, in assert_warns
    % func.__name__)
AssertionError: No warning raised when calling float

----------------------------------------------------------------------
```

Python 2.5.4

Red Hat Enterprise 5, 64 bit

Mac Leopard

Solaris

Red Hat Enterprise 4, 32 bit

Red Hat Enterprise 4, 64 bit

This was recently observed in:

```
origin?http://github.com/numpy/numpy.git (fetch)
origin?http://github.com/numpy/numpy.git (push)
1ee71d93fd069a51f45b4fa91e9e91d083a9334e
```

but has been happening at least since Sept 30.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2010-10-16

I see this too on OS X and Python 2.5 (but not on 2.6). This got introduced in commit:d82003ba6.

Q1: the doc for PyErr_WarnEx (http://docs.python.org/release/2.6.5/c-api/exceptions.html) says that the last int argument should be positive, from the doc it appears this argument should be 1, not 0. Or is this because ComplexWarning is defined in Python, not C?

Q2: why is PyErr_Warn not working? The call seems fine. Unless it has to do with the above 0/1 difference. And for clarity: the test is fine, the warning just does not get emitted:
    >>> a = np.cdouble(1+2j)
    >>> float(a)
    1.0
    >>>

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-10-16

commit:d24db3430, commit:0e792e6

The last argument to WarnEx controls which stack level the warning is raised from. I think also 0 is valid (= current stack level), but here it results to something inside the warnings module -- so the warning is visited at the same location least once before simplefilter("error", ...) and is not raised. Something is different in Python 2.6, but it seems WarnEx(...., 1) is the correct thing to do.
