### ISSUE TITLE
structured array incorrectly gives a broadcast error (migrated from Trac #1640)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3191]
Original ticket http://projects.scipy.org/numpy/ticket/1640
Reported 2010-10-15 by atmention:mwiebe, assigned to unknown.

Here's a simple failure that should work:

> > > p = np.rec.recarray((2,),dtype=[('f0','f4',3),('f1','f4',1)])
> > > p==p
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ValueError: shape mismatch: objects cannot be broadcast to a single shape

A slightly different dtype, and it works:

> > > p = np.rec.recarray((2,),dtype=[('f0','f4',2),('f1','f4',1)])
> > > p==p
> > > rec.array([[ True,  True],
> > >        [ True,  True]], dtype=bool)

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2010-10-18

It looks like the problem is caused by two features conflicting:
- dtypes with fields are compared one field at a time, and ANDed together
- types with a shape have their shape appended to the array's shape
  Here's what the code is effectively doing to get the failure, in function _void_compare of arrayobject.c
  >>> p = np.rec.recarray((2,),dtype=[('f0','f4',3),('f1','f4',1)])
  >>> q = p.copy()
  # in _void_compare:
  >>> a = p.f0             # line 836
  >>> b = q.f0             # line 841
  >>> temp = a==b          # line 847
  >>> temp.shape      # (problem here) _void_compare assumes this has the same
  (2, 3)              # shape as p and q, but it doesn't
  >>> res = temp           # line 855
  >>> a = p.f1             # line 836
  >>> b = q.f1             # line 841
  >>> temp = a==b          # line 847
  >>> temp.shape
  (2,)                # this is the shape that _void_compare expects
  >>> temp2 = res & temp   # line 858
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  ValueError: shape mismatch: objects cannot be broadcast to a single shape

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2010-10-19

http://github.com/m-paradox/numpy/compare/master...fix_structured_compare

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-25

The fix was applied.
