### ISSUE TITLE
FAIL: test_special_values (test_umath_complex.TestClog)  on Solaris/Sun Studio (migrated from Trac #1642)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3193]
Original ticket http://projects.scipy.org/numpy/ticket/1642
Reported 2010-10-19 by trac user opk, assigned to unknown.

I'm trying to build 1.5.1rc1 on Solaris using Sun Studio. I'm getting messages saying undefined symbol for exp. -lm is needed for exp(). Even the Linux man page for exp suggests linking with -lm. Error message is below. Thank you

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/include -I/opt/csw/include/python2.6 -c'
cc: _configtest.c
/opt/SUNWspro/bin/cc _configtest.o -o _configtest
Undefined                       first referenced
 symbol                             in file
exp                                 _configtest.o
ld: fatal: Symbol referencing errors. No output written to _configtest
Undefined                       first referenced
 symbol                             in file
exp                                 _configtest.o
ld: fatal: Symbol referencing errors. No output written to _configtest
failure.
removing: _configtest.c _configtest.o

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2010-10-19

Lots of configtests fail, they are probing the system to see what is available. What other problems are you having with the build?

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-10-19

**Comment by thouis** [comment]
Comment in Trac by trac user opk, 2010-10-20

This particular configtest has the outward appearance of being broken rather than of failing so I was assuming the build had failed. Autoconf manages to handle failing tests in a rather less alarming way, printing just yes or no, so if this is just a no it'd be nice if it looked less fatal. It seems numpy may have gone on to build fully. I just tried to install it and run the tests. (Is there a way to run the test cases from the build directory without first installing?)

From the test cases I get one failure and some warnings. The warnings are:
  Warning: overflow encountered in ldexp
  Warning: invalid value encountered in power

The failure is:

## FAIL: test_special_values (test_umath_complex.TestClog)

Traceback (most recent call last):
  File "/opt/csw/lib/python/site-packages/numpy/testing/decorators.py", line 215, in knownfailer
    return f(_args, *_kwargs)
  File "/opt/csw/lib/python/site-packages/numpy/core/tests/test_umath_complex.py", line 173, in test_special_values
    assert_almost_equal(np.log(x), y)
  File "/opt/csw/lib/python/site-packages/numpy/testing/utils.py", line 443, in assert_almost_equal
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal
 ACTUAL: array([-inf+0.j])
 DESIRED: (-inf+3.1415926535897931j)

config tests failing are:
cc: _configtest.c
"_configtest.c", line 1: cannot find include file: <endian.h>
"_configtest.c", line 3: warning: empty translation unit
cc: acomp failed for _configtest.c

cc: _configtest.c
"_configtest.c", line 5: zero or negative subscript
cc: acomp failed for _configtest.c

cc: _configtest.c
"_configtest.c", line 7: undefined symbol: SIZEOF_LONGDOUBLE
cc: acomp failed for _configtest.c

cc: _configtest.c
"_configtest.c", line 8: undefined symbol: HAVE_DECL_SIGNBIT
cc: acomp failed for _configtest.c

cc: _configtest.c
"_configtest.c", line 5: warning: tokens ignored at end of directive line
"_configtest.c", line 6: undefined symbol: die
"_configtest.c", line 6: syntax error before or at: in
cc: acomp failed for _configtest.c

Thanks

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-10-20

The test failure indicates that your platform has a non-C99 compliant implementation of `clog`. Not fatal, but the test should be marked as a known failure on the platform.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-10-20

commit:05be85c
commit:c0bd3df
