### ISSUE TITLE
numpy.test() fails test_umath_complex.TestClog on Solaris 5.10 (migrated from Trac #1644)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3195]
Original ticket http://projects.scipy.org/numpy/ticket/1644
Reported 2010-10-20 by trac user lytenyn, assigned to unknown.

Running numpy.test() fails one test on Sun Solaris 5.10. This is IMHO not a critical test. Do you agree with that?

If so, could you please mark this test as a known failure, in order to not scare other users? Thanks in advance!

The following test is failing: 

```
FAIL: test_special_values (test_umath_complex.TestClog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/csw/lib/python/site-packages/numpy/testing/decorators.py", line 215, in knownfailer
    return f(*args, **kwargs)
  File "/opt/csw/lib/python/site-packages/numpy/core/tests/test_umath_complex.py", line 173, in test_special_values
    assert_almost_equal(np.log(x), y)
  File "/opt/csw/lib/python/site-packages/numpy/testing/utils.py", line 443, in assert_almost_equal
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal
 ACTUAL: array([-inf+0.j])
 DESIRED: (-inf+3.1415926535897931j)
>>  raise AssertionError('\nArrays are not almost equal\n ACTUAL: array([-inf+0.j])\n DESIRED: (-inf+3.1415926535897931j)')
```

The full output of numpy.test() is:

```
>>> numpy.test()
Running unit tests for numpy
NumPy version 1.5.0
NumPy is installed in /opt/csw/lib/python/site-packages/numpy
Python version 2.6.6 (r266:84292, Oct 12 2010, 15:25:47) [C]
nose version 0.11.2
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................
................................................................K...
....................................................................
....................................................................
....................................................................
...................K.........................................Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
Warning: invalid value encountered in power
...................................................K................
......K.F...........................................................
...........................................S........................
....................................................................
........................................................................................................................................
....................................................................
....................................................................
....................................................................
...................................................................
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................
............................................................................................................................S...........
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................
....................................................................................................
======================================================================
FAIL: test_special_values (test_umath_complex.TestClog)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/csw/lib/python/site-packages/numpy/testing/decorators.py", line 215, in knownfailer
    return f(*args, **kwargs)
  File "/opt/csw/lib/python/site-packages/numpy/core/tests/test_umath_complex.py", line 173, in test_special_values
    assert_almost_equal(np.log(x), y)
  File "/opt/csw/lib/python/site-packages/numpy/testing/utils.py", line 443, in assert_almost_equal
    raise AssertionError(msg)
AssertionError:
Arrays are not almost equal
 ACTUAL: array([-inf+0.j])
 DESIRED: (-inf+3.1415926535897931j)
>>  raise AssertionError('\nArrays are not almost equal\n ACTUAL: array([-inf+0.j])\n DESIRED: (-inf+3.1415926535897931j)')


----------------------------------------------------------------------
Ran 2608 tests in 60.639s

FAILED (KNOWNFAIL=4, SKIP=2, failures=1)
<nose.result.TextTestResult run=2608 errors=0 failures=1>
```

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2010-10-20

dup of #1642
