### ISSUE TITLE
Patch for utils.py  lookfor() (migrated from Trac #1704)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3255]
Original ticket http://projects.scipy.org/numpy/ticket/1704
Reported 2011-01-03 by atmention:sebhaase, assigned to unknown.

lookfor chokes on SWIG globals vars
e.g. wx module

An easy patch is:
/numpy/lib/utils.py
928,933c928
<                 try:
<                     item_name = getattr(v, '**name**', "%s.%s" % (name, n))
<                 except NameError: 
<                     # ref. SWIG's global cvars
<                     #    NameError: Unknown C global variable
## <                     item_name = "%s.%s" % (name, n)

> ```
>             item_name = getattr(v, '__name__', "%s.%s" % (name, n))
> ```

**Comment by thouis** [comment]
Comment in Trac by atmention:sebhaase, 2011-01-03

correct formatting
    928c928,933
    <                 item_name = getattr(v, '**name**', "%s.%s" % (name, n))
    ---
    >                 try:
    >                     item_name = getattr(v, '**name**', "%s.%s" % (name, n))
    >                 except NameError: 
    >                     # ref. SWIG's global cvars
    >                     #    NameError: Unknown C global variable
    >                     item_name = "%s.%s" % (name, n)

**Comment by thouis** [comment]
Attachment in Trac by atmention:sebhaase, 2011-01-03: [original.patch](http://projects.scipy.org/numpy/attachment/ticket/1704/original.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-30

Looks sensible and won't break anything.

Can you add a test for something that is throwing the NameError?

**Comment by thouis** [comment]
Comment in Trac by atmention:sebhaase, 2011-03-30

You could use this as a test.
    >>> import numpy as np
    >>> import wx
    >>> np.lookfor('Bell', wx)
    Search results for 'bell'
    -------------------------
    wx.Bell
        Bell()
    wx.CheckBox
        A checkbox is a labelled box which by default is either on (the
    wx.Validator_SetBellOnError

```
wx.PyValidator.SetBellOnError
```

wx is widely used, but big, so the command takes a few seconds on my machine.

without the patch I get:
    >>> import numpy as np
    >>> import wx
    >>> np.lookfor('window',wx)
    Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "/home/shaase/Priithon_27_lin64/numpy/lib/utils.py", line 748, in lookfor
        cache = _lookfor_generate_cache(module, import_modules, regenerate)
      File "/home/shaase/Priithon_27_lin64/numpy/lib/utils.py", line 933, in _lookfor_generate_cache
        mod_name = getattr(v, '__module__', None)
    NameError: Unknown C global variable

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-30

Don't have wx installed, and it doesn't make much sense to add that as a test since it will be skipped for the majority of users. I tried with everything in scipy.sparse, but that's all fine even though it's a SWIGed module. So could be a wx issue.

Either way, this looks OK to me.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-30

Pauli, you wrote lookfor I believe. Can this go in?

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-03-30

Looks good to me. Committed in commit:51a1895

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31
