### ISSUE TITLE
new_iterator branch - bus error (migrated from Trac #1724)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3274]
Original ticket http://projects.scipy.org/numpy/ticket/1724
Reported 2011-01-27 by atmention:rgommers, assigned to unknown.

After building Mark Wiebe's new-iterator branch, commit  527de17, I get a bus error on running the tests:
    In [2]: np.test()
    Running unit tests for numpy
    NumPy version 1.6.0.dev-527de17
    NumPy is installed in /Users/rgommers/Code/numpy/numpy
    Python version 2.6.4 (r264:75821M, Oct 27 2009, 19:48:32) [GCC 4.0.1 (Apple Inc. build 5493)]
    nose version 0.11.1
    Bus error
This on OS X 10.6, Intel 32-bit and Python 2.6 from python.org.

Build log attached. There are many build warnings like:
    numpy/core/src/npymath/halffloat.c: In function ‘npy_doublebits_to_halfbits’:
    numpy/core/src/npymath/halffloat.c:355: warning: integer constant is too large for ‘unsigned long’ type

```
numpy/core/src/multiarray/lowlevel_strided_loops.c.src: In function ‘_aligned_swap_strided_to_strided_size8’:
```

**Comment by thouis** [comment]
Attachment in Trac by atmention:rgommers, 2011-01-27: [build_new-iterator.log](http://projects.scipy.org/numpy/attachment/ticket/1724/build_new-iterator.log)

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-27

The warnings are caused by the 64-bit constants - does anyone know a portable way to specify them?  I saw the warnings on one of the buildbots when I tested float16, and it still passed the tests.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-27

It looks like 'ull' is actually portable enough, I thought it might not be.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-27

Is it possible to get a stack trace with debug info?  The source location where the bus error occurs would be helpful.

**Comment by thouis** [comment]
Attachment in Trac by atmention:rgommers, 2011-01-28: [buserror_traceback.txt](http://projects.scipy.org/numpy/attachment/ticket/1724/buserror_traceback.txt)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-01-28

Is the attached traceback helpful at all? I only have the Python installed from python.org binaries at the moment, and am going on holiday after tomorrow so won't be able to do much more about this for a week or so.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-28

The error looks a bit odd - Compress gets 0x1486380 for 'self', then passes NULL to TakeFrom (unless optimizations cause the wrong values to be seen and it's a red herring).  That shouldn't be possible, since Compress doesn't modify 'self'.

Did you by chance delete the build folder?  The Python build system tracks dependencies incorrectly, and especially with ABI changes, I consistently get crashing builds without deleting the build folder.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-01-29

I assume you mean whether or not I removed the build folder before a new build? Yes, I do:
    $ git clean -xdf
    $ python setup.py build_ext -i
A build folder present or not after building that makes any difference is something I've never heard of. Just in case I've checked, both with and without it I get segfaults.

What I missed in the build log the first time around is the following, right at the start:
    Running from numpy source directory.non-existing path in 'numpy/distutils': 'site.cfg'
    F2PY Version 2
    numpy/core/setup_common.py:86: MismatchCAPIWarning: API mismatch detected, the C API
    version numbers have to be updated. Current C api version is 5, with checksum
    72b9c4298262b6e0e3d4c77845f48135, but recorded checksum for C API version 5 in
    codegen_dir/cversions.txt is 77e2e846db87f25d7cf99f9d812076f0. If functions were
    added in the C API, you have to update C_API_VERSION  in numpy/core/setup_common.py.
      MismatchCAPIWarning)

It's not just running the tests that gives a segfault, a simple
    >>> import numpy
    >>> numpy.linspace(1, 10)
will do it too.

I was asking before on the list for someone to review the ABI fixes because my understanding from 1.4.0 was that it is just not possible to add new types while keeping ABI compatibility, because the size of the struct holding the types increases. Disclaimer: I don't know too much about the numpy core, so I may have misunderstood.

Another thing to fix is that any changes to setup.py should be applied to the corresponding SConscript file.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-29

Hmmm, none of that sounds like it would cause this crash.  Looking at the stack trace again, I see it's crashing during the repr() call to print the array.  I'd need to play with it a bit to diagnose further.

I tried building with the build_ext -i, and it still worked fine for me.

I read through the mailing list archives to try and get an understanding of the issues, and there were a few.  The one I wasn't sure about, the type metadata, appears to already be in 1.5, and the rest of them seemed reasonable to deal with.  Here's a summary:
- Any type enum value like NPY_OBJECT needs to stay the same.  I did this by moving the new types to the end of the enum, which also required gutting the existing type promotion system.
- The PyArray_ArrFuncs struct needs to keep the exact same layout (this was the main roadblock discussed on the list for 1.4.0).  At issue is the array 'cast' which has one cast function per type enum value.  I changed it so it just has values for the types that were in 1.5, and new types go in the 'castdict', which formerly just held cast functions for custom user types.
- The PyArray_Descr had some small changes which I had to revert (but which had no effect on functionality).

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-01-29

In-place build shouldn't make a difference, it's quite robust.

I also tried with Python 2.7 64-bit on OS X (build log attached), same warnings, same result:
    $ python2.7
    Python 2.7.1 (r271:86882M, Nov 30 2010, 10:35:34) 
    [GCC 4.2.1 (Apple Inc. build 5664)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import numpy as np
    >>> np.linspace(1, 10)
    Segmentation fault

I assume you're on Linux? Have you tried on any other platform?

**Comment by thouis** [comment]
Attachment in Trac by atmention:rgommers, 2011-01-29: [python27-macosx10.6-buildlog.txt](http://projects.scipy.org/numpy/attachment/ticket/1724/python27-macosx10.6-buildlog.txt)

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-29

I've fixed this particular crash, there was an uninitialized variable used in PyArray_Nonzero (which curiously triggered no gcc warning).

I'm on Linux 64-bit, yes.  I haven't tried other platforms, was hoping to use the buildbot for that.  It worked for me before, but now the github svn connection seems broken.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-01-30

That works for me, thanks!

The build warnings are also gone, except for the C API mismatch one.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-01-30

Tested with scipy 0.9.0rc1 compiled against 1.5.1 as well. One issue in ndimage related to types:
    ======================================================================
    ERROR: gaussian gradient magnitude filter 1
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
        self.test(*self.arg)
      File "/Users/rgommers/Code/scipy/scipy/ndimage/tests/test_ndimage.py", line 668, in test_gaussian_gradient_magnitude01
        tmp1 = ndimage.gaussian_filter(array, 1.0, [1, 0])
      File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 268, in gaussian_filter
        mode, cval)
      File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 220, in gaussian_filter1d
        return correlate1d(input, weights, axis, output, mode, cval, 0)
      File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 129, in correlate1d
        origin)
    RuntimeError: array type 5 not supported

```
======================================================================
ERROR: gaussian gradient magnitude filter 2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/tests/test_ndimage.py", line 682, in test_gaussian_gradient_magnitude02
    tmp1 = ndimage.gaussian_filter(array, 1.0, [1, 0])
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 268, in gaussian_filter
    mode, cval)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 220, in gaussian_filter1d
    return correlate1d(input, weights, axis, output, mode, cval, 0)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 129, in correlate1d
    origin)
RuntimeError: array type 5 not supported

======================================================================
ERROR: gaussian laplace filter 1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/tests/test_ndimage.py", line 625, in test_gaussian_laplace01
    tmp1 = ndimage.gaussian_filter(array, 1.0, [2, 0])
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 268, in gaussian_filter
    mode, cval)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 220, in gaussian_filter1d
    return correlate1d(input, weights, axis, output, mode, cval, 0)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 129, in correlate1d
    origin)
RuntimeError: array type 5 not supported

======================================================================
ERROR: gaussian laplace filter 2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/tests/test_ndimage.py", line 636, in test_gaussian_laplace02
    tmp1 = ndimage.gaussian_filter(array, 1.0, [2, 0])
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 268, in gaussian_filter
    mode, cval)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 220, in gaussian_filter1d
    return correlate1d(input, weights, axis, output, mode, cval, 0)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 129, in correlate1d
    origin)
RuntimeError: array type 5 not supported

======================================================================
ERROR: laplace filter 1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/tests/test_ndimage.py", line 602, in test_laplace01
    tmp1 = ndimage.correlate1d(array, [1, -2, 1], 0)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 129, in correlate1d
    origin)
RuntimeError: array type 5 not supported

======================================================================
ERROR: laplace filter 2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
    self.test(*self.arg)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/tests/test_ndimage.py", line 613, in test_laplace02
    tmp1 = ndimage.correlate1d(array, [1, -2, 1], 0)
  File "/Users/rgommers/Code/scipy/scipy/ndimage/filters.py", line 129, in correlate1d
    origin)
RuntimeError: array type 5 not supported
```

They're somehow failing with int32 now.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-30

The only place that could be throwing this exception appears to be the function

```
int NI_ArrayToLineBuffer(NI_LineBuffer *buffer,
                         npy_intp *number_of_lines, int *more)
```

which certainly has int32 support, and the enum just references NumPy's.  This has got to be the side effect of some other silent error somewhere.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-01-30

The error seems to come from npy_common.h thru noprefix.h. The error itself is raised in scipy/ndimage/src/ni_support.c at line 330.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-01-30

I see the same errors for scipy trunk built on a 32-bit system.

**Comment by thouis** [comment]
Attachment in Trac by atmention:mwiebe, 2011-01-31: [scipy_int32_debugprints.patch](http://projects.scipy.org/numpy/attachment/ticket/1724/scipy_int32_debugprints.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-31

I've attached a patch which prints out some debug information in the immediate vicinity of the exception.  Can you run the tests with it to see what it says?

**Comment by thouis** [comment]
Attachment in Trac by atmention:charris, 2011-01-31: [debug.log.zip](http://projects.scipy.org/numpy/attachment/ticket/1724/debug.log.zip)

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-01-31

Done. I ran the scipy.test() and compressed the output because it's rather long. The bit with the exception and 5 is just a small bit of the whole.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-01-31

I'll guess the problem comes from ints and longs being the same size.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-31

Good call - that makes perfect sense.  Since the ufunc code now always takes the first function that will work, this could switch between int and long in some places.

The NumPy implementation should change to defining the enum with the sized types, so that either NPY_INT and NPY_LONG are the same number, or NPY_LONG and NPY_LONGLONG are the same number.  That's a 2.0 thing, though...

**Comment by thouis** [comment]
Attachment in Trac by atmention:mwiebe, 2011-01-31: [scipy_canonical_long.patch](http://projects.scipy.org/numpy/attachment/ticket/1724/scipy_canonical_long.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-01-31

There's a scipy patch which should hopefully fix it.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-01-31

That solves that problem. There is another failing test involving float16 for scipy 7.2 built against 1.4.1, I haven't looked yet, but I suspect some test is being run for all floats.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-01-31

The float16 error was from the Recaster function, a function that seems to have been removed since 7.2. One of the things it did was to continue down in precision within a given kind. When float32 was the smallest float continuing down gave float32. Now it gives float16. I don't know if this is worth worrying about, but it's a small incompatibility.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-02-02

Let's not worry about the Recaster failure, it was never used much and is already removed.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-02-28

Scipy 0.9.0 is tagged, this can be closed.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31
