### ISSUE TITLE
syntax error - development numpy in python 2.5 (migrated from Trac #1741)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3291]
Original ticket http://projects.scipy.org/numpy/ticket/1741
Reported 2011-02-11 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (test_regression.py, line 1525))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/nose/loader.py", line 379, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/stsci/pyssgdev/2.5.4/nose/importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/stsci/pyssgdev/2.5.4/nose/importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_regression.py", line 1525
    a[()] = b"hello1"
                    ^
SyntaxError: invalid syntax
```

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-02-11

Should be fixed in df57147.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-02-28

Indeed fixed.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-24
