### ISSUE TITLE
numpy.median() and numpy.mean() shoud be more predictable (migrated from Trac #1747)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3297]
Original ticket http://projects.scipy.org/numpy/ticket/1747
Reported 2011-02-19 by trac user eriko, assigned to unknown.

numpy.mean() and numpy.median() behave differnetly when presented one dimensional input and a given "axis" argument. While mean() returns a result, median() raises an IndexError. I think, both ways are fine as long as both functions behave simmilar. 

Example code:

```
>>> import numpy
>>> numpy.mean(1, axis=0)
1.0
>>> numpy.median(1, axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/6.2/lib/python2.6/site-packages/numpy/lib/function_base.py", line 2805, in median
    index = int(sorted.shape[axis]/2)
IndexError: tuple index out of range
>>> 
```

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-29

Fixed in commit:dce8638

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-04-26
