### ISSUE TITLE
Segfault in pandas. (migrated from Trac #1757)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3307]
Original ticket http://projects.scipy.org/numpy/ticket/1757
Reported 2011-03-06 by atmention:charris, assigned to unknown.

The following code segfaults.

```
>>> import pandas
>>> import pandas.util.testing as common
>>> df = common.makeTimeDataFrame()
>>> objs = [df, df]
>>> s = pandas.Series(objs, index=[0, 1])
```

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-03-06

The immediate problem is

```
#0  discover_dimensions (s=0x0, maxndim=0x7fffffffd14c, d=0x7fffffffd440, 
    check_it=1, stop_at_string=1, stop_at_tuple=0, out_is_object=
    0x7fffffffd3cc) at numpy/core/src/multiarray/ctors.c:666
        e = <value optimized out>
        n = <value optimized out>
        i = <value optimized out>
        buffer_view = {buf = 0xb, obj = 
    <unknown at remote 0x-53425ff84629df63>, len = 269111108832, 
          itemsize = 11584208, readonly = -1468220032, ndim = 62, format = 
    0x1 <Address 0x1 out of bounds>, shape = 0x0, strides = 0x3ea8449025, 
          suboffsets = 0x7ffff0b9f710, smalltable = {269111386692, 11584208}, 
          internal = 0x7ffff0b9f510}
```

That is, s is a null pointer to a PyObject. This comes from line 825 in ctors.c

```
        e = PySequence_GetItem(s, 0);
        r = discover_dimensions(e, &maxndim_m1, d + 1, check_it,
                                        stop_at_string, stop_at_tuple,
                                        out_is_object);
```

So numpy should to check the value of e and raise an error if it is the Null pointer and also check the value of r for an error return. 

So why is it the Null pointer? None may be involved.

**Comment by thouis** [comment]
Attachment in Trac by atmention:charris, 2011-03-06: [panda-debug.patch](http://projects.scipy.org/numpy/attachment/ticket/1757/panda-debug.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-03-07

The problem may be that df exposes the **array** attribute. In 1.5.x calling

```
np.array([df]*2, np.object)
```

Produces a (2,) array of df objects. In 1.6 the array constructor continues to descend.

Also, 

```
np.array([df]*2)
```

should return a ValueError to be consistent.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-03-07

For reference, in 1.5

```
>>> import numpy as np
>>> import pandas.util.testing as common
>>> x = common.makeTimeDataFrame()
>>> a = np.array([x])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: setting an array element with a sequence.
>>> a = np.array([x,x])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: setting an array element with a sequence.
>>> a = np.array([x,x],object)
>>>
```

The last two segfault in 1.6

**Comment by thouis** [comment]
Attachment in Trac by atmention:charris, 2011-03-07: [pandas-fix.patch](http://projects.scipy.org/numpy/attachment/ticket/1757/pandas-fix.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-03-07

Added a patch that actually works for pandas. One pandas test remains in error, it looks to be due to the stricter assignment broadcasting rules. I think more needs to be done with discover_dimensions to catch more errors along the way, but the patch could be a starting point. The pandas DataFrame object is a complicated thing.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-11

Can this be closed?

For any final tweaks maybe open a new enhancement ticket if needed.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-03-11

Fixed.
