### ISSUE TITLE
Inconsistency with type in scalar operations (migrated from Trac #1761)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3311]
Original ticket http://projects.scipy.org/numpy/ticket/1761
Reported 2011-03-08 by atmention:FrancescAlted, assigned to unknown.

I'm getting different behaviour with type comparison in scalar operations between 1.5.1 and 1.6.  Here it is code that shows the issue:

```
import numpy as np

print "numpy-->", np.__version__

r1 = np.array(8L)
print "r1-->", `r1`, r1.dtype
r1 = r1[()]
print "r1(2)-->", `r1`, r1.dtype

f = long(3)
g = np.int16(2)
r2 = f+g   # assertion fails only with 1.6
#r2 = g+f  # assertion fails with 1.5.1 too
print "r2-->", `r2`, r2.dtype

print "types-->", type(r1), type(r2)
assert type(r1) is type(r2)
```

Output when using 1.5.1:

```
numpy--> 1.5.1
r1--> array(8L) int64
r1(2)--> 8 int64
r2--> 5 int64
types--> <type 'numpy.int64'> <type 'numpy.int64'>
```

When using 1.6 (master):

```
numpy--> 1.6.0.dev-c081ad7
r1--> array(8L) int64
r1(2)--> 8 int64
r2--> 5 int64
types--> <type 'numpy.int64'> <type 'numpy.int64'>
Traceback (most recent call last):
  File "/tmp/scalar-types.py", line 17, in <module>
    assert type(r1) is type(r2)
AssertionError
```

Interestingly, if we change the order of the operation:

```
r2 = g+f
```

the resulting type also differs with 1.5.1:

```
numpy--> 1.5.1
r1--> array(8L) int64
r1(2)--> 8 int64
r2--> 5 int64
types--> <type 'numpy.int64'> <type 'numpy.int64'>
Traceback (most recent call last):
  File "/tmp/scalar-types.py", line 17, in <module>
    assert type(r1) is type(r2)
AssertionError
```

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-03-08

This is because NumPy bases its fundamental types on the C types instead of sized types (something which IMO should be changed). On some 64 bit systems, sizeof(long) == sizeof(long long), and the thing to check is the type number. (7 is NPY_LONG, 9 is NPY_LONGLONG). In 1.6:

```
>>> r1.dtype.num
9
>>> r2.dtype.num
7
>>> r1.dtype == r2.dtype
True
```

In 1.6, because the result type of a+b should always be the same as b+a, at least it's behaving a bit more consistently even if its still weird.

I'm marking this as wontfix, since to properly fix this in all possible cases requires changing the types enumeration which deserves its own bug. Is it breaking any specific code for you?

**Comment by thouis** [comment]
Comment in Trac by atmention:FrancescAlted, 2011-03-09

It was breaking some tests, not code.  But your explanation makes sense to me, so I've changed my tests to use the `dtype` when handling NumPy objects.  Everything works well now using both 1.5.x and 1.6.

And +1 for basing NumPy types on sized types, not C types (but I know that would not be easy; perhaps for NumPy 2.0?).
