### ISSUE TITLE
f2py assumed shape merge - test failure (migrated from Trac #1767)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3315]
Original ticket http://projects.scipy.org/numpy/ticket/1767
Reported 2011-03-11 by atmention:rgommers, assigned to atmention:pearu.

The merge of the branch that closed #1532 and #1750 introduced a test failure:
    ======================================================================
    FAIL: test_kind.TestKind.test_all
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/nose-0.11.1-py2.6.egg/nose/case.py", line 183, in runTest
        self.test(*self.arg)
      File "/Users/rgommers/Code/numpy/numpy/f2py/tests/test_kind.py", line 27, in test_all
        assert selected_int_kind(i)==selectedintkind(i),`i, selected_int_kind(i), selectedintkind(i)`
    AssertionError: (19, 16, -1)

```
----------------------------------------------------------------------
Ran 3279 tests in 60.489s
```

This fails with Python 2.6 on OS X but works with Python 3.2.

Also, some print statements have been left in the code:
    ..............This module '_test_ext_module_5403' is auto-generated with f2py (version:2).
    Functions:
      res = sum(x)
      res = fsum(x)
      res = sum_with_use(x)
    Fortran 90/95 modules:
      precision --- ik,rk.
    ..This module '_test_ext_module_5405' is auto-generated with f2py (version:2).
    Functions:
      res = selectedrealkind(p,r=0)
      res = selectedintkind(p)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-11

Also, please use assert_() from numpy.testing instead of plain assert in tests.

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-03-11

The assertion errors are probably due to the usage of different fortran compilers or due to differences in underlying architectures (32 or 64 bit). I have applied the corresponding workarounds to these tests. Also the print statements are now removed and assert statements are replaced with assert_ calls.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-11

Works for me, thanks. For future reference:
    $ gfortran --version
    GNU Fortran (GCC) 4.2.3
    Copyright (C) 2007 Free Software Foundation, Inc.

```
GNU Fortran comes with NO WARRANTY, to the extent permitted by law.
You may redistribute copies of GNU Fortran
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING
```

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-03-24

The assertion errors still persists on MacOS X 10.5/ppc:

On 24 Mar 2011, at 09:11, Pearu Peterson wrote:

PowerPC:

## FAIL: test_kind.TestKind.test_all

Traceback (most recent call last):
 File "/sw/lib/python2.5/site-packages/nose/case.py", line 187, in runTest
   self.test(*self.arg)
 File "/sw/lib/python2.5/site-packages/numpy/f2py/tests/test_kind.py", line 30, in test_all
   'selectedrealkind(%s): expected %r but got %r' %  (i, selected_real_kind(i), selectedrealkind(i)))
 File "/sw/lib/python2.5/site-packages/numpy/testing/utils.py", line 34, in assert_
   raise AssertionError(msg)
AssertionError: selectedrealkind(16): expected 10 but got 16

Regarding this test failure, could you hack the numpy/f2py/tests/test_kind.py script by adding the following code

for i in range(20):
  print '%s -> %s, %s' % (i, selected_real_kind(i), selectedrealkind(i))

and send me the output? Also, what Fortran compiler version has been used to build the test modules?

1 -> 4, 4
2 -> 4, 4
3 -> 4, 4
4 -> 4, 4
5 -> 4, 4
6 -> 4, 4
7 -> 8, 8
8 -> 8, 8
9 -> 8, 8
10 -> 8, 8
11 -> 8, 8
12 -> 8, 8
13 -> 8, 8
14 -> 8, 8
15 -> 8, 8
16 -> 10, 16
17 -> 10, 16
18 -> 10, 16
19 -> -1, 16

tested with both gfortran from 

Target: powerpc-apple-darwin9.8.0
Configured with: ../gcc-4.4.4/configure --prefix=/sw --prefix=/sw/lib/gcc4.4 --mandir=/sw/share/man --infodir=/sw/lib/gcc4.4/info --enable-languages=c,c++,fortran,objc,obj-c++,java --with-gmp=/sw --with-libiconv-prefix=/sw --with-ppl=/sw --with-cloog=/sw --with-mpc=/sw --with-system-zlib --x-includes=/usr/X11R6/include --x-libraries=/usr/X11R6/lib --program-suffix=-fsf-4.4 --disable-libjava-multilib
Thread model: posix
gcc version 4.4.4 (GCC) 

and

Target: powerpc-apple-darwin9
Configured with: ../gcc-4.2.4/configure --prefix=/sw --prefix=/sw/lib/gcc4.2 --mandir=/sw/share/man --infodir=/sw/share/info --enable-languages=c,c++,fortran,objc,java --host=powerpc-apple-darwin9 --with-gmp=/sw --with-libiconv-prefix=/sw --with-system-zlib --x-includes=/usr/X11R6/include --x-libraries=/usr/X11R6/lib --disable-libjava-multilib
Thread model: posix
gcc version 4.2.4

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-03-24

Thanks for the info!
In addition, could you send the output of
    import numpy
    print numpy.finfo(numpy.float64)
    print numpy.finfo(numpy.float96) # when available
    print numpy.finfo(numpy.float128)

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-03-24

A fix is committed to numpy repo:

  https://github.com/numpy/numpy/commit/2e96d915

See also the note about PowerPC in

  http://en.wikipedia.org/wiki/Long_double

Please confirm whether the kind tests passes or not.

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-03-24

Thanks, this test passes now! It was the float128 indeed...
If you still need the info:

print(numpy.finfo(numpy.float128))
Warning: overflow encountered in add
Warning: invalid value encountered in subtract
Warning: invalid value encountered in subtract
Warning: overflow encountered in add
Warning: invalid value encountered in subtract
Warning: invalid value encountered in subtract

## Machine parameters for float128

precision= 75   resolution= 1e-75
machep=    -4   eps=        1.3817869701e-76
negep =    -4   epsneg=     1.3817869701e-76
minexp=    -1   tiny=       -1.08420217274e-19
maxexp=     1   max=        -9.22337203471e+18

## nexp  =     1   min=        -max

compared to i386:
print(np.finfo(np.float128))

## Machine parameters for float128

precision= 18   resolution= 1e-18
machep=   -63   eps=        1.08420217249e-19
negep =   -64   epsneg=     5.42101086243e-20
minexp=-16382   tiny=       3.36210314311e-4932
maxexp= 16384   max=        1.18973149536e+4932

## nexp  =    15   min=        -max

The tiny and max certainly seem wrong, but maybe it's just print() can't handle them? 
Anyway the other failures (notably fpe 'overflow' and 'underflow' for numpy.float128) are still present on ppc.

Cheers

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-03-25

IRC, numpy.finfo is known to fail on ppc, though I could not find the corresponding ticket
(may be I saw it in ML). Anyway, that is another issue.
