### ISSUE TITLE
KeyError in crackfortran.py (migrated from Trac #1782)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3330]
Original ticket http://projects.scipy.org/numpy/ticket/1782
Reported 2011-03-24 by atmention:fonnesbeck, assigned to atmention:pearu.

I get the following when I try to build extensions with f2py:

Traceback (most recent call last):
  File "setupegg.py", line 7, in <module>
    execfile('setup.py')
  File "setup.py", line 131, in <module>
    **(config_dict))
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/distutils/core.py", line 186, in setup
    return old_setup(**new_attr)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/setuptools/command/develop.py", line 27, in run
    self.install_for_development()
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/distutils/command/develop.py", line 15, in install_for_development
    old_develop.install_for_development(self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/setuptools/command/develop.py", line 85, in install_for_development
    self.run_command('egg_info')
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/distutils/command/egg_info.py", line 8, in run
    self.run_command("build_src")
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/distutils/command/build_src.py", line 152, in run
    self.build_sources()
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/distutils/command/build_src.py", line 169, in build_sources
    self.build_extension_sources(ext)
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/distutils/command/build_src.py", line 334, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/distutils/command/build_src.py", line 593, in f2py_sources
    ['-m',ext_name]+f_sources)
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/f2py2e.py", line 359, in run_main
    postlist=callcrackfortran(files,options)
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/f2py2e.py", line 281, in callcrackfortran
    postlist=crackfortran.crackfortran(files)
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/crackfortran.py", line 2721, in crackfortran
    postlist=postcrack(grouplist[0])
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/crackfortran.py", line 1554, in postcrack
    g=postcrack(g,tab=tab+'\t')
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/crackfortran.py", line 1573, in postcrack
    block['body']=analyzebody(block,args,tab=tab)
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/crackfortran.py", line 1722, in analyzebody
    b=postcrack(b,as_,tab=tab+'\t')
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/crackfortran.py", line 1573, in postcrack
    block['body']=analyzebody(block,args,tab=tab)
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/crackfortran.py", line 1719, in analyzebody
    b['saved_interface'] = crack2fortrangen(b, '\n'+' '*6, as_interface=True)
  File "/Library/Python/2.6/site-packages/numpy-2.0.0.dev_2e96d91_20110324-py2.6-macosx-10.6-universal.egg/numpy/f2py/crackfortran.py", line 2511, in crack2fortrangen
    al = [a for a in block['args'] if not isintent_callback(vars[a])]
KeyError: 'n'

**Comment by thouis** [comment]
Comment in Trac by atmention:fonnesbeck, 2011-03-24

Apparently f2py now checks the arguments of subroutines that are not set up for f2py, as this error comes from a subroutine that vas not given any f2py goodness.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-25

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-03-25

This bug is already fixed by
  https://github.com/numpy/numpy/commit/d4ee39f3

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-04-30
