### ISSUE TITLE
histogramdd doesn't like bins with infinite edges (migrated from Trac #1788)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3336]
Original ticket http://projects.scipy.org/numpy/ticket/1788
Reported 2011-03-30 by trac user eschlafly, assigned to unknown.

The following code causes an Overflow Error and doesn't need to:

```
h,e = histogramdd(randn(100,2), bins=(100,[-inf,0,inf]))
```

The problem is the section of code which looks for points on the right edge of the rightmost edge.  Specifically, it looks for the amount that is "close enough" to the edge via line 314 (in lib/function_base.py, v1.5.1):

```
decimal = int(-log10(dedges[i].min())) +6
```

but in this case dedges[i].min() == inf, triggering the overflow.
I would propose looking for the case dedges[i].min() == inf explicitly and not trying to find such points in that case.

Of course, I can get around this, but it's really convenient when the library is robust against such situations.

Thanks a lot.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-31

This shouldn't be too hard to fix. In addition, bins can be specified in two ways, mixing them gives confusing errors:
    >>> x = np.arange(8).reshape(2, 4)
    >>> h, e = np.histogramdd(x, bins=[1, 2, 4, 5])
    >>> h, e = np.histogramdd(x, bins=[-1, 2, 4, 5])
    ------------------------------------------------------------
    Traceback (most recent call last):
      File "<ipython console>", line 1, in <module>
      File "/Users/zouzoujing/Code/numpy/numpy/lib/function_base.py", line 341, in histogramdd
        decimal = int(-log10(dedges[i].min())) +6
    ValueError: zero-size array to minimum.reduce without identity

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-03-31

Can you see if this works: https://github.com/rgommers/numpy/tree/ticket-1788-histogramdd

Any additional improvements welcome.

**Comment by thouis** [comment]
Comment in Trac by trac user eschlafly, 2011-03-31

I downloaded and installed your branch.  I can confirm that this fixes the problem for my use case---thanks a lot!

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-04-01

Fixed in commit:fdf84d9.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-05-31

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-04-30
