### ISSUE TITLE
genfromtxt should probably return an empty array if there is no data. (migrated from Trac #1793)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3341]
Original ticket http://projects.scipy.org/numpy/ticket/1793
Reported 2011-04-04 by atmention:charris, assigned to unknown.

genfromtxt currently raises an IOError if it reaches the eof without finding a line of data.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-04-04

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-07-31

Fixed in commit:72ab385

**Comment by thouis** [comment]
Attachment in Trac by atmention:dhomeier, 2011-08-05: [1793-py3.patch](http://projects.scipy.org/numpy/attachment/ticket/1793/1793-py3.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-08-05

{{{first_line = ''}}} raises an error with Python3 due to the usual string vs. bytes mess:

```
ERROR: Test that an empty file raises the proper warning.
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/derek/lib/python3.2/site-packages/numpy/lib/tests/test_io.py", line 966, in test_empty_file
test = np.genfromtxt(data)
File "/Users/derek/lib/python3.2/site-packages/numpy/lib/npyio.py", line 1498, in genfromtxt
values = split_line(line)
File "/Users/derek/lib/python3.2/site-packages/numpy/lib/_iotools.py", line 206, in _delimited_splitter
line = line.split(self.comments)[0].strip(asbytes(" \r\n"))
TypeError: Can't convert 'bytes' object to str implicitly
```

Tested the attached fix on python2.5 + 2.7 as well; also added an appropriate warning to loadtxt().

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-08-10

Committed in commit:57b56bc. Thanks Derek.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-04-30
