### ISSUE TITLE
test fails: test_array_too_big (test_regression.TestRegression) (migrated from Trac #1811)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3359]
Original ticket http://projects.scipy.org/numpy/ticket/1811
Reported 2011-04-27 by atmention:stsci-sienkiew, assigned to unknown.

```
======================================================================
ERROR: test_array_too_big (test_regression.TestRegression)
Ticket #1080.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_regression.py", line 1157, in test_array_too_big
    assert_raises(MemoryError, np.zeros, [2**30]*2, np.int8)
  File "/usr/stsci/pyssgdev/2.7/numpy/testing/utils.py", line 1007, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
  File "/usr/stsci/pyssgdev/Python-2.7/lib/python2.7/unittest/case.py", line 456, in assertRaises
    callableObj(*args, **kwargs)
ValueError: array is too big.
```

This is in Python 2.7 on 32 bit Mac and 32 bit Red Hat Enterprise 4.

Works on Python 2.5, 2.6, 2.7 on 64 bit RHE 5.  Works on Python 2.7 on 64 bit Mac Snow Leopard.  Works on Python 2.7 on 64 bit RHE 4.

The line of the test that is erroring is:        

```
        assert_raises(MemoryError, np.zeros, [2**30]*2, np.int8)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2011-04-27

This is the trunk.  GIT says 433b02a909c6ada47c721088d1fc6df67bab8ac8

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-04-27

Yeah, The test is bogus on 32 bits, I'll fix it up. Or maybe I'll just remove it.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-04-27

Fixed in commit:f7eda58

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-04-27

This gives a ValueError on win32 but still a MemoryError on 64-bit OS X:
    ======================================================================
    ERROR: Ticket #1080.
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/tests/test_regression.py", line 1158, in test_array_too_big
        assert_raises(ValueError, np.zeros, [2**30]_2, np.int8)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 1008, in assert_raises
        return nose.tools.assert_raises(_args,**kwargs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 456, in assertRaises
        callableObj(_args, *_kwargs)
    MemoryError

So better to just delete this test? Or make it dependent on32/64-bit?

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-04-27

I was going to mention that ;) I think it better to just delete the test. To set it up right requires choosing a size that is addressable but exceeds the available memory and that isn't easy so easy to determine since it will vary depending on both the user's hardware and the operating system.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-04-28

Looks like you deleted it, so closing again.
