### ISSUE TITLE
FAIL: string test on win 32 Py 3.2 has dtype U5 instead of S5 (migrated from Trac #1812)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3360]
Original ticket http://projects.scipy.org/numpy/ticket/1812
Reported 2011-04-27 by atmention:rgommers, assigned to unknown.

```
======================================================================
FAIL: Ticket #1748
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Z:\Users\zouzoujing\.wine\drive_c\Python32\lib\site-packages\numpy\core\tests\test_regression.py", line 1550, in test_string_astype
    assert_equal(b.dtype, np.dtype('S5'))
  File "Z:\Users\zouzoujing\.wine\drive_c\Python32\lib\site-packages\numpy\testing\utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: dtype('<U5')
 DESIRED: dtype('|S5')
```

Test issue or actual issue?

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-04-29

This looks to me like a minor issue. I'm going to mark it knownfail for 1.6.0 and tag RC1 tomorrow if no one disagrees.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-05-14
