### ISSUE TITLE
assert_array_less behavior with inf/nan (migrated from Trac #1825)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3373]
Original ticket http://projects.scipy.org/numpy/ticket/1825
Reported 2011-05-08 by atmention:rgommers, assigned to unknown.

This passed with 1.5.1 but fails with 1.6.0 due to Inf fixes to assert_array_compare for functions testing (near-)equality.
    np.testing.assert_array_less(2, np.inf)
    np.testing.assert_array_less(np.array([ 0.911,  1.065,  1.325,  1.587]), np.inf)

These functions pass butit's not clear that they should:
    assert_array_less([1, np.inf], [2, np.inf])
    assert_array_less([1, np.nan], [2, np.nan])

**Comment by thouis** [comment]
Comment in Trac by atmention:WarrenWeckesser, 2011-08-09

Adding to Ralf's description: the second of the two examples that previously passed comes from a test in scipy that is now failing:
    ======================================================================
    FAIL: test_expon (test_morestats.TestAnderson)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/warren/local_scipy/lib/python2.7/site-packages/scipy/stats/tests/test_morestats.py", line 72, in test_expon
        assert_array_less(crit[:-1], A)
      File "/Library/Frameworks/Python.framework/Versions/7.1/lib/python2.7/site-packages/numpy/testing/utils.py", line 869, in assert_array_less
        header='Arrays are not less-ordered')
      File "/Library/Frameworks/Python.framework/Versions/7.1/lib/python2.7/site-packages/numpy/testing/utils.py", line 613, in assert_array_compare
        chk_same_position(x_id, y_id, hasval='inf')
      File "/Library/Frameworks/Python.framework/Versions/7.1/lib/python2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
        raise AssertionError(msg)
    AssertionError: 
    Arrays are not less-ordered

```
x and y inf location mismatch:
 x: array([ 0.911,  1.065,  1.325,  1.587])
 y: array(inf)

----------------------------------------------------------------------
```
