### ISSUE TITLE
f2py fails to compile(KeyError: 'coutput') (migrated from Trac #1828)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3376]
Original ticket http://projects.scipy.org/numpy/ticket/1828
Reported 2011-05-12 by trac user Iceman, assigned to atmention:pearu.

When I try to compile any fortran file with f2py I get the next error message:

```
f2py -c control.f90 -m control

running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "control" sources
f2py options: []
f2py:> /tmp/tmps7XyGJ/src.linux-i686-2.6/controlmodule.c
creating /tmp/tmps7XyGJ
creating /tmp/tmps7XyGJ/src.linux-i686-2.6
Reading fortran codes...
    Reading file 'control.f90' (format:free)
Post-processing...
    Block: control
            Block: control_fortran
                Block: control_1
Post-processing (stage 2)...
    Block: control
        Block: unknown_interface
            Block: control_fortran
                Block: control_1
Building modules...
    Building module "control"...
        Constructing F90 module support for "control_fortran"...
            Constructing wrapper function "control_fortran.control_1"...
              salidas = control_1(ent_analogicas,ent_digitales,[n_analogicas,n_digitales])
Traceback (most recent call last):
  File "/usr/local/bin/f2py", line 24, in <module>
    main()
  File "/usr/local/lib/python2.6/dist-packages/numpy/f2py/f2py2e.py", line 561, in main
    run_compile()
  File "/usr/local/lib/python2.6/dist-packages/numpy/f2py/f2py2e.py", line 547, in run_compile
    setup(ext_modules = [ext])
  File "/usr/local/lib/python2.6/dist-packages/numpy/distutils/core.py", line 186, in setup
    return old_setup(**new_attr)
  File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.6/dist-packages/numpy/distutils/command/build.py", line 37, in run
    old_build.run(self)
  File "/usr/lib/python2.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.6/dist-packages/numpy/distutils/command/build_src.py", line 152, in run
    self.build_sources()
  File "/usr/local/lib/python2.6/dist-packages/numpy/distutils/command/build_src.py", line 169, in build_sources
    self.build_extension_sources(ext)
  File "/usr/local/lib/python2.6/dist-packages/numpy/distutils/command/build_src.py", line 334, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/usr/local/lib/python2.6/dist-packages/numpy/distutils/command/build_src.py", line 593, in f2py_sources
    ['-m',ext_name]+f_sources)
  File "/usr/local/lib/python2.6/dist-packages/numpy/f2py/f2py2e.py", line 369, in run_main
    ret=buildmodules(postlist)
  File "/usr/local/lib/python2.6/dist-packages/numpy/f2py/f2py2e.py", line 316, in buildmodules
    dict_append(ret[mnames[i]],rules.buildmodule(modules[i],um))
  File "/usr/local/lib/python2.6/dist-packages/numpy/f2py/rules.py", line 1254, in buildmodule
    fn = os.path.join(options['buildpath'],vrd['coutput'])
KeyError: 'coutput'
```

Why I get this error message? I am under Ubuntu 10.04 and I am compiling with gfortran.

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-05-12

Could you attached on of those fortran codes that give this exception?

**Comment by thouis** [comment]
Attachment in Trac by trac user Iceman, 2011-05-12: [control.f90](http://projects.scipy.org/numpy/attachment/ticket/1828/control.f90)

**Comment by thouis** [comment]
Comment in Trac by trac user Iceman, 2011-05-12

The most annoying it's that with numpy 1.5 I haven't any problem.

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-05-12

I cannot reproduce this issue. Neither with 1.6.0rc3 nor with numpy master branch.
Try reinstalling numpy.

**Comment by thouis** [comment]
Comment in Trac by atmention:pearu, 2011-05-12

From
    File "/usr/local/lib/python2.6/dist-packages/numpy/f2py/f2py2e.py", line 316, in buildmodules
        dict_append(ret[mnames[i]],rules.buildmodule(modules[i],um))
note that f2py2e.py line #316 is not the same as in 1.6.0rc3 branch:

https://github.com/numpy/numpy/blob/maintenance%2F1.6.x/numpy/f2py/f2py2e.py

So, there must be something wrong with your numpy installation.
