### ISSUE TITLE
numpy.rec.array fails with open file on Py3 (migrated from Trac #1843)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3391]
Original ticket http://projects.scipy.org/numpy/ticket/1843
Reported 2011-05-26 by atmention:cgohlke, assigned to unknown.

As discussed on the [http://mail.scipy.org/pipermail/numpy-discussion/2011-May/056446.html mailing list], the following code raises a ValueError on Python 3, but works as expected with Python 2:

```
import sys, numpy
fd = open(sys.executable, 'rb')
numpy.rec.array(fd, dtype=[('_', 'b')])
Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "C:\Python32\lib\site-packages\numpy\core\records.py", line 799, 
in array
     raise ValueError("Unknown input type")
ValueError: Unknown input type
```

The problem seems to be the test for file objects in numpy/compat/py3k.py:

```
     def isfileobj(f):
         return isinstance(f, io.FileIO)
```

If this is updated to include _io.BufferedReader, the type of `fd`, 
numpy.rec.array works with file objects opened in 'rb' mode:

```
    def isfileobj(f):
         return isinstance(f, (io.FileIO, io._io.BufferedReader))
```

I am not sure this is the best/correct fix.

Tested with numpy 1.6.0 on Windows.

**Comment by thouis** [comment]
Attachment in Trac by atmention:cgohlke, 2011-05-26: [test_recarray_fromfile.diff](http://projects.scipy.org/numpy/attachment/ticket/1843/test_recarray_fromfile.diff)

**Comment by thouis** [comment]
Attachment in Trac by atmention:cgohlke, 2011-05-26: [py3k_isfileobj.diff](http://projects.scipy.org/numpy/attachment/ticket/1843/py3k_isfileobj.diff)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-06-23

Tested, looks OK and works for me.  I've sent a pull request for this: https://github.com/numpy/numpy/pull/97

Charles had a question about encodings on the pull request, could you have a look at that Christoph?

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-07-01

Committed in 5e4a4075a8476a6c6d46481f33a4c873f545d4c7
