### ISSUE TITLE
1-D masked array (numpy.ma) is corrupted by numpy.atleast_2d (migrated from Trac #1844)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3392]
Original ticket http://projects.scipy.org/numpy/ticket/1844
Reported 2011-05-26 by trac user doylejg, assigned to atmention:pierregm.

I construct a 1 dimensional masked array then create a second 2-D array from the original array and the original array is modified. Best explained with an example shown below.

```
ar = numpy.ma.masked_where([False,False,False,True],[1,2,3,99])
ar2 = numpy.atleast_2d(ar)
print ar
```

Below is the traceback from the failed print line
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/pymodules/python2.7/numpy/ma/core.py", line 3570, in **repr**
        data=str(self), mask=str(self._mask),
      File "/usr/lib/pymodules/python2.7/numpy/ma/core.py", line 3554, in __str__
        res[m] = f
    ValueError: boolean index array should have 1 dimension

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-05-27

Seems to have been fixed since:
    >>> import numpy
    >>> ar = numpy.ma.masked_where([False,False,False,True],[1,2,3,99])
    >>> ar2 = numpy.atleast_2d(ar)
    >>> print ar
    [1 2 3 --]
    >>> numpy.**version**
    '1.6.0'
