### ISSUE TITLE
nose-1.0.0 test failures on Mac OS X 10.6.7 and Xcode 4.0.2 using numpy-1.6.0 (migrated from Trac #1849)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3397]
Original ticket http://projects.scipy.org/numpy/ticket/1849
Reported 2011-05-29 by trac user elvisjohndowson, assigned to unknown.

Hi,
      I just installed numpy-1.6.0 and nose-1.0.0 on Mac OS X 10.6.7, using Xcode-4.0.2 and gfortran-4.2-5664 (from the R tools site).

When I run the tests, I get 1 failure and 1 error. 
# 
## ERROR: Tests the min/max functions with explicit outputs

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/ma/tests/test_core.py", line 699, in test_minmax_funcs_with_output
    result = npfunc(xm,axis=0,out=nout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/fromnumeric.py", line 1569, in amin
    return amin(axis, out)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/ma/core.py", line 3119, in min
    np.putmask(out, newmask, np.nan)
ValueError: cannot convert float NaN to integer
# 
## FAIL: test_umath.TestComplexFunctions.test_against_cmath

Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/nose-1.0.0-py2.6.egg/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/numpy/core/tests/test_umath.py", line 268, in test_against_cmath
    assert abs(a - b) < atol, "%s %s: %s; cmath: %s"%(fname,p,a,b)
AssertionError: arcsin 2: (1.57079632679-1.31695789692j); cmath: (1.57079632679+1.31695789692j)

---

Ran 1740 tests in 11.679s

FAILED (KNOWNFAIL=1, errors=1, failures=1)
<nose.result.TextTestResult run=1740 errors=1 failures=1>

Here are the commands that I used to build numpy and nose:

Step 36.00: Install Numerical Python library.

Step 36.01: Download numpy 1.6.0 for python-2.6 from 

http://sourceforge.net/projects/numpy/files/NumPy/1.6.0/numpy-1.6.0.tar.gz/download

$ cd numpy-1.6.0
$ env ARCHFLAGS="-arch i386 -arch x86_64" python setup.py build 
$ sudo env ARCHFLAGS="-arch i386 -arch x86_64" python setup.py install
$ cd ../

Step 36.02: Download nose-1.0.0 to test the numpy installation from 

http://somethingaboutorange.com/mrl/projects/nose/nose-1.0.0.tar.gz

$ cd nose-1.0.0
$ env ARCHFLAGS="-arch i386 -arch x86_64" python setup.py build 
$ sudo env ARCHFLAGS="-arch i386 -arch x86_64" python setup.py install
$ cd ../

Step 36.03: Test the numpy installation.

$ export VERSIONER_PYTHON_PREFER_32_BIT=yes

$ python

> > > import numpy
> > > numpy.test('1','10')
> > > exit()
> > > $

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-05-29

You are probably picking up numpy from some older install or the version shipped by Apple, because the line numbers are way off. Please check with
    import numpy as np
    np.**version**
    np.**file**
    import numpy.core
    np.core.**file**
etc. what is going on.

Also, unless you have a specific reason to use the Python shipped by Apple, it is better to avoid using it completely. It's very outdated and you may get problems with conflicting packages. Just grab an installer from python.org.
