### ISSUE TITLE
Broadcasting fails for A *= B (migrated from Trac #1859)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3407]
Original ticket http://projects.scipy.org/numpy/ticket/1859
Reported 2011-06-07 by atmention:gerritholl, assigned to unknown.

The shape of the rhs in an operation A *= B is wrongly read, and thus the operation fails. See code below.

```
$ python
Python 2.6.6 (r266:84292, Sep 15 2010, 16:22:56) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from numpy import zeros
>>> A1 = zeros((2, 1, 1))
>>> A2 = zeros((2,))
>>> A1 * A2 # works
array([[[ 0.,  0.]],

       [[ 0.,  0.]]])
>>> A1 *= A2 # fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: non-broadcastable output operand with shape (2,1,1) doesn't match the broadcast shape (0,140018678770184,2)
>>> A1 *= A2 # fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: non-broadcastable output operand with shape (2,1,1) doesn't match the broadcast shape (0,0,2)
>>> A1 *= A2 # fails
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: non-broadcastable output operand with shape (2,1,1) doesn't match the broadcast shape (14885712,6881,2)
>>> from numpy.version import full_version, git_revision
>>> print full_version
2.0.0.dev-3071eab
>>> print git_revision
3071eab84b81ef6e0d157d46404c631547fed763
```

The same for +=, /=, etc.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-06-07

The problem here is the error message, the error definitely should be happening. The broadcast shape is (2,1,2), with 4 elements (you can see that in your printout of A1 \* A2). A1 *= A2 is saying to assign those 4 elements to the 2 elements of A1, so is an invalid operation.

I've fixed this on master in commit:fd9ef72d. Leaving it out of 1.6.x because it's an error message bug, not a functionality bug.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-06-07

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-04-30
