### ISSUE TITLE
test_datetime.TestDateTime errors (migrated from Trac #1865)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3413]
Original ticket http://projects.scipy.org/numpy/ticket/1865
Reported 2011-06-13 by atmention:stsci-sienkiew, assigned to unknown.

Started doing this on RHE 5 64 bit, python 2.7, on Jun 8.  

```
======================================================================
ERROR: test_datetime_add (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 459, in test_datetime_add
    (np.datetime64('2012-12-21', '[D]'),
SystemError: NULL result without error in PyObject_Call

======================================================================
ERROR: test_datetime_as_string (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 880, in test_datetime_as_string
    assert_equal(np.datetime_as_string(np.datetime64(date, 'Y')),
SystemError: NULL result without error in PyObject_Call

======================================================================
ERROR: test_datetime_divide (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 635, in test_datetime_divide
    (np.datetime64('2012-12-21', '[D]'),
SystemError: NULL result without error in PyObject_Call

======================================================================
ERROR: test_datetime_multiply (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 594, in test_datetime_multiply
    (np.datetime64('2012-12-21', '[D]'),
SystemError: NULL result without error in PyObject_Call

======================================================================
ERROR: test_datetime_nat_casting (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 163, in test_datetime_nat_casting
    b = np.datetime64('NaT', '[D]')
SystemError: NULL result without error in PyObject_Call

======================================================================
ERROR: test_datetime_scalar_construction (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 78, in test_datetime_scalar_construction
    assert_equal(np.datetime64('1950-03-12', 'D'),
SystemError: NULL result without error in PyObject_Call

======================================================================
ERROR: test_datetime_subtract (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 532, in test_datetime_subtract
    (np.datetime64('2012-12-21', '[D]'),
SystemError: NULL result without error in PyObject_Call

======================================================================
ERROR: test_different_unit_comparison (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 371, in test_different_unit_comparison
    assert_equal(np.datetime64('1945', unit1),
SystemError: NULL result without error in PyObject_Call

======================================================================
ERROR: test_string_parser_variants (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/core/tests/test_datetime.py", line 787, in test_string_parser_variants
    assert_equal(np.datetime64('1977-03-02T12:30-0230'),
SystemError: NULL result without error in PyObject_Call

----------------------------------------------------------------------
```

Checked out on Jun 8 ~20:00 EDT.  Version 

76ca55f8f399a9eb8081b75c3c9c2ac075a4af9a

through

a1e7be3cb49577d77831e2246f39bb80acd5a22f

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2011-06-13

That is, "first checked out".  The test has been failing each day ever since on Red Hat Enterprise 5 / 64 bit.  It is passing on mac leopard (32 bit), mac snow leopard (64 bit), and RHE 4 (32 and 64 bit).

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-06-14

It might be an error I've fixed in my datetime_dev branch. Here's the pull request:

https://github.com/numpy/numpy/pull/87

and the commit which may be the fix:

https://github.com/m-paradox/numpy/commit/fdb4190225df2cd4f1d966f4086372f0a866e54a

These changes are awaiting review.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-06-16

Can you try it with the latest master, to see if it still fails?

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2011-06-20

There are no failing tests in my latest install.

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-06-20

Great, thanks for testing.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-04-26
