### ISSUE TITLE
datetime-fixes break numpy on python2.4 (migrated from Trac #1868)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3416]
Original ticket http://projects.scipy.org/numpy/ticket/1868
Reported 2011-06-15 by atmention:dhomeier, assigned to unknown.

Since merging of the datetime-fixes [commits a827436 - does not build +  f986fd4]  numpy fails to load in python2.4, at least on MacOS X i386+ppc:

```
Python 2.4.4 (#1, Jan  5 2011, 03:05:41) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy 
Traceback (most recent call last):
  File "<stdin>", line 1, in ?
  File "/Users/derek/lib/python2.4/site-packages/numpy/__init__.py", line 137, in ?
    import add_newdocs
  File "/Users/derek/lib/python2.4/site-packages/numpy/add_newdocs.py", line 9, in ?
    from numpy.lib import add_newdoc
  File "/Users/derek/lib/python2.4/site-packages/numpy/lib/__init__.py", line 4, in ?
    from type_check import *
  File "/Users/derek/lib/python2.4/site-packages/numpy/lib/type_check.py", line 8, in ?
    import numpy.core.numeric as _nx
  File "/Users/derek/lib/python2.4/site-packages/numpy/core/__init__.py", line 5, in ?
    import multiarray
ImportError: Failure linking new module: /Users/derek/lib/python2.4/site-packages/numpy/core/multiarray.so: Symbol not found: _PyErr_WarnEx
  Referenced from: /Users/derek/lib/python2.4/site-packages/numpy/core/multiarray.so
  Expected in: dynamic lookup
```

I reckon the solution can be found in this changeset [http://projects.scipy.org/numpy/changeset/7996]

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-06-16

Please consider a fix at [https://github.com/dhomeier/numpy/compare/master...warnex24], tested on OS X i386+ppc

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-06-19

Fixed in [https://github.com/numpy/numpy/commit/5cb956e4]

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-06-19

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-04-26
