### ISSUE TITLE
hex output format changed in Python3 (migrated from Trac #1875)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3423]
Original ticket http://projects.scipy.org/numpy/ticket/1875
Reported 2011-06-21 by atmention:dhomeier, assigned to unknown.

test_arrayprint.py fails on python3.x with 

```
FAIL: Test custom format function for each element in array.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/derek/lib/python3.2/site-packages/numpy/core/tests/test_arrayprint.py", line 86, in test_format_function
    "[0x0L 0x1L 0x2L]")
  File "/Users/derek/lib/python3.2/site-packages/numpy/testing/utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: '[0x0 0x1 0x2]'
 DESIRED: '[0x0L 0x1L 0x2L]'
```

Apparently the hex() and oct() functions have been decided to print out a format without the trailing 'L' as of python3 - [http://mail.python.org/pipermail/python-dev/2006-June/065946.html], so I suggest to define the expected result depending on the version (see patch).

**Comment by thouis** [comment]
Attachment in Trac by atmention:dhomeier, 2011-06-21: [hexPy3k.patch](http://projects.scipy.org/numpy/attachment/ticket/1875/hexPy3k.patch)

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-06-21

Applied in commit:adab903. Thanks for figuring that out Derek.

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2012-04-26
