### ISSUE TITLE
FAIL: test_timedelta_scalar_construction (migrated from Trac #1880)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3428]
Original ticket http://projects.scipy.org/numpy/ticket/1880
Reported 2011-06-26 by atmention:nilswagner01, assigned to unknown.

```
======================================================================
FAIL: test_timedelta_scalar_construction (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nwagner/local/lib64/python2.6/site-packages/numpy/core/tests/test_datetime.py", line 189, in test_timedelta_scalar_construction
    assert_equal(str(np.timedelta64(3, 's')), '3 seconds')
  File "/home/nwagner/local/lib64/python2.6/site-packages/numpy/testing/utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: '%lld seconds'
 DESIRED: '3 seconds'
```

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-06-27

Could you provide some details about the operating system, 32 bit/64 bit, etc this is on?

**Comment by thouis** [comment]
Comment in Trac by atmention:mwiebe, 2011-06-29

Marking as duplicate of #1887, because that ticket has more details.
