### ISSUE TITLE
Segfault during garbage collection after some operations with arrays (migrated from Trac #1881)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3429]
Original ticket http://projects.scipy.org/numpy/ticket/1881
Reported 2011-06-28 by trac user Bogdan, assigned to unknown.

System:
OSX 10.6.7
Python 2.6.1 (the one provided with system)
Numpy 2.0.0.dev-3071eab (installed via SciPy Superpack)

After running the file (attached) I get a segfault. Can't find any other lines to remove, because the bug disappears. GDB trace:

```
Program received signal EXC_BAD_ACCESS, Could not access memory.
Reason: KERN_INVALID_ADDRESS at address: 0x000000000000000a
0x00000001000b03eb in Py_Main ()
(gdb) bt
#0  0x00000001000b03eb in Py_Main ()
#1  0x0000000100039751 in PyDict_GetItemString ()
#2  0x00000001000b0bc4 in PyObject_GC_Track ()
#3  0x00000001000b118a in PyGC_Collect ()
#4  0x00000001000a30ca in Py_Finalize ()
#5  0x00000001000b03b1 in Py_Main ()
#6  0x0000000100000e6c in ?? ()
```

**Comment by thouis** [comment]
Attachment in Trac by trac user Bogdan, 2011-06-28: [bugtest.py](http://projects.scipy.org/numpy/attachment/ticket/1881/bugtest.py)

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-06-28

I can confirm that for 3071eab Valgrind indeed spews errors, but I don't see them any more with the current Git master (78ff5e04). I'd guess this issue has already been fixed.
