### ISSUE TITLE
broken int64 format in timedelta64 for Python < 2.7 (migrated from Trac #1887)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3435]
Original ticket http://projects.scipy.org/numpy/ticket/1887
Reported 2011-06-29 by atmention:dhomeier, assigned to unknown.

With Python versions 2.4-2.6, the output of np.timedelta only produces the format string since (probably) merging the datetime branch, like this:
    >>> np.**version**
    '2.0.0.dev-f7c16d7'
    >>> np.timedelta64(3)
    numpy.timedelta64(%lld,'generic')
    >>> str(np.timedelta64(3, 's'))
    '%lld seconds'
or in the most recent version
    >>> np.**version**
    '2.0.0.dev-192ac74'
    >>> np.timedelta64(3)
    numpy.timedelta64(%lld)
making the corresponding tests fail, whereas with 2.7 and 3.2 the intended output is produced:
    >>> np.timedelta64(3)
    numpy.timedelta64(3)
    >>> str(np.timedelta64(3, 's'))
    '3 seconds'
(Tested on MacOS X 10.5/ppc and 10.6/x86_64)

**Comment by thouis** [comment]
Comment in Trac by atmention:stsci-sienkiew, 2011-07-05

Also observed on Red Hat Enterprise 5 Linux in python 2.5 and python 2.6; started happening on 2011-06-22.

```
======================================================================
FAIL: test_timedelta_scalar_construction (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.5.4/numpy/core/tests/test_datetime.py", line 189, in test_timedelta_scalar_construction
    assert_equal(str(np.timedelta64(3, 's')), '3 seconds')
  File "/usr/stsci/pyssgdev/2.5.4/numpy/testing/utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: '%lld seconds'
 DESIRED: '3 seconds'
```
