### ISSUE TITLE
Numpy links wrong lapack blas and atlas in lapack_lite.so (migrated from Trac #1889)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3437]
Original ticket http://projects.scipy.org/numpy/ticket/1889
Reported 2011-06-30 by trac user maldun, assigned to atmention:cournape.

I'm working on Ubuntu 10.10/11.04, and Opensuse 11.4. I installed Gentoo prefix on both systems and compiled the blas lapack and atlas versions from. 

No I installed numpy linked with the libraries from prefix
On Ubuntu it worked fine. On openSuse I got the following error message when I try to import numpy

```
parmenidesatmention:math146 ~/gentoo $ python
Python 2.7.1 (r271:86832, Jun 30 2011, 08:50:27) 
[GCC 4.4.5] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/parmenides/gentoo/usr/lib/python2.7/site-packages/numpy/__init__.py", line 136, in <module>
    import add_newdocs
  File "/home/parmenides/gentoo/usr/lib/python2.7/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/home/parmenides/gentoo/usr/lib/python2.7/site-packages/numpy/lib/__init__.py", line 13, in <module>
    from polynomial import *
  File "/home/parmenides/gentoo/usr/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 17, in <module>
    from numpy.linalg import eigvals, lstsq
  File "/home/parmenides/gentoo/usr/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 48, in <module>
    from linalg import *
  File "/home/parmenides/gentoo/usr/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 23, in <module>
    from numpy.linalg import lapack_lite
ImportError: liblapack.so.0: cannot open shared object file: No such file or directory
>>> quit()
```

but blas, lapack and atlas should have been built properly.

Then after some other failed experiments I tried my build of lapack_lite.so from ubuntu in the opensuse version and got this:

```
....
    from numpy.linalg import lapack_lite
ImportError: liblapack.so.3gf: cannot open shared object file: No such file or directory
```

when I opended with emacs the lapack_lite.so with my emacs I found this entry within the assembler code:

```
liblapack.so.3gf...libblas.so.3gf
```

The gag behind this is that this doesn't appear in my directory where I installed blas, lapack and atlas but in my /usr/lib directory. But my site cfg holds the following:

```
[atlas]
include_dirs = /home/maldun/Gentoo/usr/include  
library_dirs = /home/maldun/Gentoo/usr/lib/blas/threaded-atlas:/home/maldun/Gentoo/usr/lib/blas/reference:/home/maldun/Gentoo/usr/lib/lapack/atlas:/home/maldun/Gentoo/usr/lib
atlas_libs = cblas, atlas, blas  
lapack_libs = lapack, blas, cblas, atlas  
[blas_opt]
include_dirs = /home/maldun/Gentoo/usr/include  
library_dirs = /home/maldun/Gentoo/usr/lib/blas/threaded-atlas:/home/maldun/Gentoo/usr/lib/blas/reference:/home/maldun/Gentoo/usr/lib
libraries = cblas, atlas, blas  
[lapack_opt]
library_dirs = /home/maldun/Gentoo/usr/lib/lapack/atlas:/home/maldun/Gentoo/usr/lib/blas/reference:/home/maldun/Gentoo/usr/lib/blas/threaded-atlas:/home/maldun/Gentoo/usr/lib
libraries = lapack, blas, cblas, atlas  
```

and those files are not located there!

My PATH, LIBRARY_PATH, and LD_LIBRARY_PATH also don't point there:

```
maldunatmention:math112:~/Gentoo$ echo $LD_LIBRARY_PATH
/home/maldun/Gentoo/usr/lib:/home/maldun/Gentoo/lib/
maldunatmention:math112:~/Gentoo$ echo $LIBRARY_PATH
/home/maldun/Gentoo/usr/lib:/home/maldun/Gentoo/lib/
maldunatmention:math112:~/Gentoo$ echo $PATH                        
/home/maldun/Gentoo/usr/bin:/home/maldun/Gentoo/bin:/home/maldun/Gentoo/opt/bin:/home/maldun/Gentoo/usr/sbin:/home/maldun/Gentoo/sbin:/home/maldun/Gentoo/usr/x86_64-pc-linux-gnu/binutils-bin/2.21.51.0.7:/home/maldun/Gentoo/usr/x86_64-pc-linux-gnu/gcc-bin/4.4.5
```

This shouldn't be happening if I want to build exclusively with one version of BLAS/LAPACK/ATLAS, but I don't know how to fix this issue!

Please help me!

greez,
maldun

**Comment by thouis** [comment]
Comment in Trac by trac user maldun, 2011-06-30

**Comment by thouis** [comment]
Comment in Trac by trac user maldun, 2011-06-30

**Comment by thouis** [comment]
Comment in Trac by trac user maldun, 2011-07-01

It appears that the problem is resolved with an update of gcc in Gentoo prefix.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-07-03

You like a little bit of complexity in your setup it seems:)

Thanks for reporting that this is resolved.
