### ISSUE TITLE
piecewise throws TypeError for int input and sin (migrated from Trac #1890)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3438]
Original ticket http://projects.scipy.org/numpy/ticket/1890
Reported 2011-07-01 by trac user deil, assigned to unknown.

I would have expected the following np.piecewise call to work:
    >>> x = np.arange(0, 10)
    >>> np.piecewise(x, [x < 5, x >= 5], [lambda x: -x, lambda x: np.sin(x)])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/function_base.py", line 715, in piecewise
        y[condlist[k]] = item(vals, _args, *_kw)
    TypeError: array cannot be safely cast to required type
    >>> x.dtype
    dtype('int64')

It works for an array of floats though:
    >>> x = np.arange(0, 10, dtype=float)
    >>> np.piecewise(x, [x < 5, x >= 5], [lambda x: -x, lambda x: np.sin(x)])
    array([-0.        , -1.        , -2.        , -3.        , -4.        ,
           -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

Is this a bug?

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-07-01

The problem is this line

y = zeros(x.shape, x.dtype)

y should probably have a type compatible with all the outputs, which means running the functions before splicing them together for the output. The stricter casting rules are catching this, and I think that is a good thing.

```
 Is this a bug?
```

Looks like it. Or a least a defect.

Chuck

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-07-01

In fact it is documented to use the same type as x

_The output is the same shape and type as x and is found by..._

If you truly want integer output, then you should use np.sin(x).astype(x.dtype).

**Comment by thouis** [comment]
Comment in Trac by trac user deil, 2011-07-01

Replying to [comment:2 charris]:

> If you truly want integer output, then you should use np.sin(x).astype(x.dtype).

I want float output, I now use this, which works fine:
    >>> np.piecewise(x.astype(float), [x < 5, x >= 5], [lambda x: -x, lambda x: np.sin(x)])

I didn't know that numpy automatically casts if the rhs is a list, but not if it is an array:
    a = np.zeros(10, dtype=int)
    a[[1,4]] = [1.1, 4] # Casts to int
    a[[1,4]] = np.array([1.1, 4]) # TypeError

I imagine there are good reasons for not automatically casting the array, but throwing a TypeError?!
I just had never run into this 'problem' of having to cast myself  and couldn't figure out why piecewise was throwing the error.

Btw., this is the second ticket I filed for numpy which turned out to be missing understanding on my part.
In the future, should I ask on the mailing list instead?

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-07-02

It's a good idea if you suspect you don't understand. However, I think your example of casting inconsistency should also posted on the list; the error raised during the assignment should be consistent. The choice to raise an error in the first place is a design decision, and I think fairly recent, but probably a good thing as having floats silently cast to integers is asking for unnoticed bugs. And it does need to be cast since the lhs type is fixed and a new array is not dynamically allocated.

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-07-02

atmention:charris: there is an inconsistency:
    a[1:3] = np.array([1.1, 4])    # ok
    a[[1,4]] = np.array([1.1, 4])  # fails
I don't think this is intentional, so that's certainly a bug, yes?

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-07-02

Yep, I opened ticket #1891.
