### ISSUE TITLE
Pickling a numpy.ma.MaskedConstant fails (migrated from Trac #1897)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3445]
Original ticket http://projects.scipy.org/numpy/ticket/1897
Reported 2011-07-07 by atmention:jpaalasm, assigned to atmention:pierregm.

```
Python 2.7.1+ (r271:86832, Apr 11 2011, 18:13:53) 
[GCC 4.5.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle; import numpy; numpy.__version__
'1.5.1'
>>> ma = numpy.ma.MaskedArray([0, 0, 0], mask=True)
>>> m = ma[0]
>>> m
masked
>>> pickle.dumps(m)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/pickle.py", line 1374, in dumps
    Pickler(file, protocol).dump(obj)
  File "/usr/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/usr/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/usr/lib/pymodules/python2.7/numpy/ma/core.py", line 5494, in __reduce__
    self.__getstate__())
  File "/usr/lib/pymodules/python2.7/numpy/ma/core.py", line 5467, in __getstate__
    self._fill_value,
AttributeError: 'MaskedConstant' object has no attribute '_fill_value'
>>> 
```

**Comment by thouis** [comment]
Comment in Trac by trac user AnthonyFloyd, 2012-05-07

This also fails on 1.6.1. It is preventing us from pickling masked numpy arrays.

**Comment by thouis** [comment]
Attachment in Trac by trac user AnthonyFloyd, 2012-05-07: [core.py.patch](http://projects.scipy.org/numpy/attachment/ticket/1897/core.py.patch)

**Comment by thouis** [comment]
Comment in Trac by trac user AnthonyFloyd, 2012-05-07

Our work-around was to add

```
_fill_value = fill_value = None 
```

to the !MaskedConstant class definition. See attached trivial patch.

**Comment by thouis** [comment]
Comment in Trac by trac user iMichka, 2012-05-22

I just tested your patch, but you will get an error when unpickling :

```
>>> import numpy; import pickle
>>> numpy.version.version
'1.6.1'
>>> ma = numpy.ma.MaskedArray([0, 0, 0], mask=True)
>>> m = ma[0]
>>> m
masked
>>> dump = pickle.dumps(m)
>>> pickle.loads(dump)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1133, in load_reduce
    value = func(*args)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/ma/core.py", line 5494, in _mareconstruct
    return subtype.__new__(subtype, _data, mask=_mask, dtype=basetype,)
TypeError: __new__() takes exactly 1 argument (4 given)
```

I was not able to correct this error. Could you check if you also get this error ?
