### ISSUE TITLE
FAIL: test_two_keys_two_vars (test_recfunctions.TestJoinBy2) (migrated from Trac #1906)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3454]
Original ticket http://projects.scipy.org/numpy/ticket/1906
Reported 2011-07-14 by atmention:stsci-sienkiew, assigned to unknown.

Observed in 32 bit python 2.7 on mac leopard and red hat enterprise 4 linux.  Not observed in any of my 64 bit systems.

```
FAIL: test_two_keys_two_vars (test_recfunctions.TestJoinBy2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/stsci/pyssgdev/2.7/numpy/lib/tests/test_recfunctions.py", line 677, in test_two_keys_two_vars
    assert_equal(test, control)
  File "/usr/stsci/pyssgdev/2.7/numpy/ma/testutils.py", line 120, in assert_equal
    return assert_array_equal(actual, desired, err_msg)
  File "/usr/stsci/pyssgdev/2.7/numpy/ma/testutils.py", line 193, in assert_array_equal
    header='Arrays are not equal')
  File "/usr/stsci/pyssgdev/2.7/numpy/ma/testutils.py", line 186, in assert_array_compare
    verbose=verbose, header=header)
  File "/usr/stsci/pyssgdev/2.7/numpy/testing/utils.py", line 635, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([(10, 0, 50, 65, 10, 0), (11, 0, 51, 66, 11, 1),
       (10, 1, 52, 67, 12, 2), (11, 1, 53, 68, 13, 3),
       (10, 2, 54, 69, 14, 4), (11, 2, 55, 70, 15, 5),...
 y: array([(10L, 0L, 50L, 65L, 10L, 0L), (11L, 0L, 51L, 66L, 11L, 1L),
       (10L, 1L, 52L, 67L, 12L, 2L), (11L, 1L, 53L, 68L, 13L, 3L),
       (10L, 2L, 54L, 69L, 14L, 4L), (11L, 2L, 55L, 70L, 15L, 5L),...
```

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-07-15

Same here, due to commit:97886266
