### ISSUE TITLE
Datetime related failures under python 3 (migrated from Trac #1923)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3471]
Original ticket http://projects.scipy.org/numpy/ticket/1923
Reported 2011-08-02 by atmention:rgommers, assigned to unknown.

These are found with Python 3.2 in a virtualenv on OS X.
    ======================================================================
    ERROR: test_datetime_array_str (test_datetime.TestDateTime)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/tests/test_datetime.py", line 510, in test_datetime_array_str
        assert_equal(str(a), "['2011-03-16' '1920-01-01' '2013-05-19']")
      File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/numeric.py", line 1385, in array_str
        return array2string(a, max_line_width, precision, suppress_small, ' ', "", str)
      File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/arrayprint.py", line 437, in array2string
        separator, prefix, formatter=formatter)
      File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/arrayprint.py", line 313, in _array2string
        _summaryEdgeItems, summary_insert)[:-1]
      File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/arrayprint.py", line 480, in _formatArray
        word = format_function(a[-i]) + separator
      File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/arrayprint.py", line 726, in __call__
        casting=self.casting)
    TypeError: Cannot create a local timezone-based date string from a NumPy datetime without forcing 'unsafe' casting

```
======================================================================
ERROR: test_datetime_divide (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/tests/test_datetime.py", line 926, in test_datetime_divide
    assert_equal(tda / tdb, 6.0 / 9.0)
TypeError: internal error: could not find appropriate datetime inner loop in true_divide ufunc


======================================================================
FAIL: test_datetime_as_string (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/tests/test_datetime.py", line 1166, in test_datetime_as_string
    '1959')
  File "/Users/rgommers/Code/numpy/build/py3k/numpy/testing/utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: b'1959'
 DESIRED: '1959'

======================================================================
FAIL: test_datetime_as_string_timezone (test_datetime.TestDateTime)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rgommers/Code/numpy/build/py3k/numpy/core/tests/test_datetime.py", line 1277, in test_datetime_as_string_timezone
    '2010-03-15T06:30Z')
  File "/Users/rgommers/Code/numpy/build/py3k/numpy/testing/utils.py", line 313, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal:
 ACTUAL: b'2010-03-15T06:30Z'
 DESIRED: '2010-03-15T06:30Z'

----------------------------------------------------------------------
```

**Comment by thouis** [comment]
Comment in Trac by atmention:dhomeier, 2011-08-24

The string-related failures might be fixed as usual by converting to bytes; I had a patch for this in 
[https://github.com/dhomeier/numpy/commit/43ebe96] 
but as Mark commented there he seems the want to come up with a more general solution.
