### ISSUE TITLE
test_umath_complex fails under OS X Lion (migrated from Trac #1926)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3474]
Original ticket http://projects.scipy.org/numpy/ticket/1926
Reported 2011-08-05 by trac user RuiPereira, assigned to unknown.

8 tests related to umath_complex fail when testing numpy 1.6.1 under OS X Lion. The same tests fail with numpy 1.5.1 shipped with the system as well as with the most recent HEAD from github.

```
python -c "import numpy; numpy.test()"
Running unit tests for numpy
NumPy version 1.6.1
NumPy is installed in /Library/Python/2.7/site-packages/numpy
Python version 2.7.1 (r271:86832, Jun 16 2011, 16:59:05) [GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)]
nose version 1.0.0
```

(...)
    ======================================================================
    FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, 1, inf, inf, inf)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/nose/case.py", line 187, in runTest
        self.test(*self.arg)
      File "/Library/Python/2.7/site-packages/numpy/core/tests/test_umath_complex.py", line 578, in check_complex_value
        assert_equal(f(z1), z2)
      File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 256, in assert_equal
        return assert_array_equal(actual, desired, err_msg, verbose)
      File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
        verbose=verbose, header='Arrays are not equal')
      File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 605, in assert_array_compare
        chk_same_position(x_id, y_id, hasval='nan')
      File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
        raise AssertionError(msg)
    AssertionError: 
    Arrays are not equal

```
x and y nan location mismatch:
 x: array([ nan+infj])
 y: array((inf+infj))

======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, -1, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/numpy/core/tests/test_umath_complex.py", line 578, in check_complex_value
    assert_equal(f(z1), z2)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 605, in assert_array_compare
    chk_same_position(x_id, y_id, hasval='nan')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

x and y nan location mismatch:
 x: array([ nan+infj])
 y: array((inf+infj))

======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, 0.0, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/numpy/core/tests/test_umath_complex.py", line 578, in check_complex_value
    assert_equal(f(z1), z2)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 605, in assert_array_compare
    chk_same_position(x_id, y_id, hasval='nan')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

x and y nan location mismatch:
 x: array([ nan+infj])
 y: array((inf+infj))

======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, -0.0, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/numpy/core/tests/test_umath_complex.py", line 578, in check_complex_value
    assert_equal(f(z1), z2)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 605, in assert_array_compare
    chk_same_position(x_id, y_id, hasval='nan')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

x and y nan location mismatch:
 x: array([ nan+infj])
 y: array((inf+infj))

======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, inf, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/numpy/core/tests/test_umath_complex.py", line 578, in check_complex_value
    assert_equal(f(z1), z2)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 605, in assert_array_compare
    chk_same_position(x_id, y_id, hasval='nan')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

x and y nan location mismatch:
 x: array([ nan+infj])
 y: array((inf+infj))

======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, -inf, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/numpy/core/tests/test_umath_complex.py", line 578, in check_complex_value
    assert_equal(f(z1), z2)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 605, in assert_array_compare
    chk_same_position(x_id, y_id, hasval='nan')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

x and y nan location mismatch:
 x: array([ nan+infj])
 y: array((inf+infj))

======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, nan, inf, inf, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/numpy/core/tests/test_umath_complex.py", line 578, in check_complex_value
    assert_equal(f(z1), z2)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 605, in assert_array_compare
    chk_same_position(x_id, y_id, hasval='nan')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

x and y nan location mismatch:
 x: array([ nan+infj])
 y: array((inf+infj))

======================================================================
FAIL: test_umath_complex.TestCsqrt.test_special_values(<ufunc 'sqrt'>, -inf, 1, 0.0, inf)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 187, in runTest
    self.test(*self.arg)
  File "/Library/Python/2.7/site-packages/numpy/core/tests/test_umath_complex.py", line 578, in check_complex_value
    assert_equal(f(z1), z2)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 256, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 707, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 605, in assert_array_compare
    chk_same_position(x_id, y_id, hasval='nan')
  File "/Library/Python/2.7/site-packages/numpy/testing/utils.py", line 588, in chk_same_position
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

x and y nan location mismatch:
 x: array([ nan+infj])
 y: array(infj)

----------------------------------------------------------------------
Ran 3533 tests in 22.955s

FAILED (KNOWNFAIL=3, SKIP=2, failures=8)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-08-07

Nothing to worry about - these tests should just be skipped on OS X.

**Comment by thouis** [comment]
Comment in Trac by trac user samueljohn, 2011-09-06

However, still annoying. I hope someone can mark these as tests to be skipped.

Additionally, I get this message during the tests:
"/usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/tests/test_umath_complex.py:364: RuntimeWarning: invalid value encountered in sqrt
  z = np.sqrt(np.array(np.complex(-np.inf, np.nan)))"

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-09-06

Yes it's annoying. The dust from the move to Lion seems to have settled so these can be marked as skipped. I've asked on the mailing list before if someone with Lion could send a patch/pull request - if you could do that it would be much appreciated.

**Comment by thouis** [comment]
Comment in Trac by trac user samueljohn, 2011-09-07

Then, please give me a pointer where to start reading on how to mark tests as skipped.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-09-07

Have a look in numpy/core/tests/test_umath_complex.py. Right now this is the logic for skipping tests:
    have_platform_functions = (sys.platform.startswith('sunos') or
                               (sys.platform == 'darwin' and 'powerpc' in
                                                 platform.processor()))
    skip_complex_tests = (sys.platform.startswith('win') or
                          (have_platform_functions and functions_seem_flaky))
I think those tests should be skipped on all platforms except Linux.  For Linux the {{{functions_seem_flaky}}} bit can be kept.  Then you can check if all the relevant tests are skipped. If not, add a {{{atmention:platform_skip}}} decorator to the ones that are still failing.

**Comment by thouis** [comment]
Comment in Trac by trac user RuiPereira, 2011-09-08

Hello. The following changes work for me:
https://github.com/RuiPereira/numpy/commit/8426bcb58338887b10193dd747e02e1fb3505e63
If it seems OK I can submit a pull request.

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-09-08

Merged in commit:073bc39. Thanks!

**Comment by thouis** [comment]
Comment in Trac by trac user samueljohn, 2011-09-08

Thank you so much, RuiPereira for the quick fix. And Ralf for the explanation and the final commit.

**Comment by thouis** [comment]
Comment in Trac by trac user samueljohn, 2011-09-09

I see this commit in the master, but not in the maintenance/1.6.x. Is is possible to port this to 1.6.x so that in the next 1.6 release it will be included?

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2011-09-10

backported in commit:396dbb9

**Comment by thouis** [comment]
Comment in Trac by trac user samueljohn, 2011-09-11

Good work!
And hey, it's weekend. Incredibly fast response here on the numpy trac/ML.
Now bumpy 1.6.x passes all tests and there is only one RuntimeWarning.

enjoy,
 Samuel

```
samuelatmention:localhost:~ $ ipython
Python 2.7.2 (default, Sep  5 2011, 10:50:07) 
Type "copyright", "credits" or "license" for more information.

IPython 0.11 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy

In [2]: numpy.test()
Running unit tests for numpy
NumPy version 1.6.2.dev-396dbb9
NumPy is installed in /usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy
Python version 2.7.2 (default, Sep  5 2011, 10:50:07) [GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)]
nose version 1.1.2
......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................../usr/local/Cellar/python/2.7.2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/numeric.py:1920: RuntimeWarning: invalid value encountered in absolute
  return all(less_equal(absolute(x-y), atol + rtol * absolute(y)))
.......................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................K.................................................................................................K...SK.S.......S...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................S.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 3498 tests in 13.133s

OK (KNOWNFAIL=3, SKIP=4)
Out[2]: <nose.result.TextTestResult run=3498 errors=0 failures=0>
```

**Comment by thouis** [comment]
Comment in Trac by trac user samueljohn, 2011-09-11

oh, sorry ... damn auto-correct does not know Numpy ... replaces it by bumpy. srry.
