### ISSUE TITLE
np.left_shift and np.right_shift fail on np.uint64 scalar types (migrated from Trac #1930)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3478]
Original ticket http://projects.scipy.org/numpy/ticket/1930
Reported 2011-08-10 by trac user tlatorre, assigned to unknown.

```
>>> np.uint64(5) << 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'
>>> np.uint64(5) >> 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'right_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'
```

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2012-05-02

Duplicate of #1931
