### ISSUE TITLE
np.left_shift and np.right_shift fail on np.uint64 scalar types (migrated from Trac #1931)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3479]
Original ticket http://projects.scipy.org/numpy/ticket/1931
Reported 2011-08-10 by trac user tlatorre, assigned to unknown.

```
>>> np.uint64(5) << 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'
>>> np.uint64(5) >> 3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'right_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule 'safe'
```

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-08-13

This is because the shift number is converted as a signed type and there is no signed integer type big enough to hold a uint64. The shift operators need to be special cased, they can also fail on Intel because the hardware masks out the unneeded bits, i.e., for int32 only the lower 5 bits are looked at.
