### ISSUE TITLE
Buffer test error on python 3. (migrated from Trac #1967)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3515]
Original ticket http://projects.scipy.org/numpy/ticket/1967
Reported 2011-10-23 by atmention:charris, assigned to atmention:pv.

```
ERROR: test_multiarray.TestFromBuffer.test_empty('', array([], dtype=float64), {})
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.2/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/charris/.local/lib/python3.2/site-packages/numpy/core/tests/test_multiarray.py", line 1446, in tst_basic
    assert_array_equal(np.frombuffer(buffer,**kwargs),expected)
AttributeError: 'str' object has no attribute '__buffer__'
```

**Comment by thouis** [comment]
Comment in Trac by atmention:charris, 2011-10-23

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2011-10-23

Missing `asbytes` in the test, I think.
