### ISSUE TITLE
loadtxt should give line numbers of problems (migrated from Trac #1998)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3546]
Original ticket http://projects.scipy.org/numpy/ticket/1998
Reported 2011-12-15 by atmention:samtygier, assigned to unknown.

currently input like
    1 2 3
    4 5 6
    78
will cause loadtxt to give the following error
    Traceback (most recent call last):
      File "./np_lt.py", line 5, in <module>
        numpy.loadtxt(sys.argv[1])
      File "/usr/lib/python2.7/site-packages/numpy/lib/npyio.py", line 804, in loadtxt
        X = np.array(X, dtype)
    ValueError: setting an array element with a sequence.

This would be far more useful, if it contained some information about where the problem was.

This is similar to the bug #1212 , but for the loadtxt function.

I attach a patch that gives the following message:
    ValueError: Wrong number of columns at line 3
it also provides a test that the input raises the correct error. Inconveniently it is the same error type as before, so the test is not very useful. However I thing ValueError is probably the most appropriate in this case. Maybe there is a way to check the exception message.

**Comment by thouis** [comment]
Attachment in Trac by atmention:samtygier, 2011-12-15: [numpy_loadtxt.diff](http://projects.scipy.org/numpy/attachment/ticket/1998/numpy_loadtxt.diff)
