### ISSUE TITLE
m68k “long double” format isn’t recognised (migrated from Trac #2014)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3562]
Original ticket http://projects.scipy.org/numpy/ticket/2014
Reported 2012-01-11 by atmention:sandrotosi, assigned to unknown.

Hello,
a fellow Debian Developer has rebuilt numpy on m68k architecture and reported (http;//bugs.debian.org/655388) a failure in detecting the long double format:

```
[…]
compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/include -I/usr/include/python2.6_d -c'
gcc: _configtest.c
_configtest.c:4:5: warning: function declaration isn't a prototype [-Wstrict-prototypes]
success!
removing: _configtest.c _configtest.o
C compiler: gcc -pthread -fno-strict-aliasing -g -Wall -Wstrict-prototypes -fPIC

compile options: '-Inumpy/core/src/private -Inumpy/core/src -Inumpy/core -Inumpy/core/src/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/include -I/usr/include/python2.6_d -c'
gcc: _configtest.c
removing: _configtest.c _configtest.o
Traceback (most recent call last):
 File "setup.py", line 211, in <module>
   setup_package()
 File "setup.py", line 204, in setup_package
   configuration=configuration )
 File "/tmp/buildd/python-numpy-1.5.1/numpy/distutils/core.py", line 186, in setup
   return old_setup(**new_attr)
 File "/usr/lib/python2.6/distutils/core.py", line 152, in setup
   dist.run_commands()
 File "/usr/lib/python2.6/distutils/dist.py", line 975, in run_commands
   self.run_command(cmd)
 File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
   cmd_obj.run()
 File "/tmp/buildd/python-numpy-1.5.1/numpy/distutils/command/build.py", line 37, in run
   old_build.run(self)
 File "/usr/lib/python2.6/distutils/command/build.py", line 135, in run
   self.run_command(cmd_name)
 File "/usr/lib/python2.6/distutils/cmd.py", line 333, in run_command
   self.distribution.run_command(command)
 File "/usr/lib/python2.6/distutils/dist.py", line 995, in run_command
   cmd_obj.run()
 File "/tmp/buildd/python-numpy-1.5.1/numpy/distutils/command/build_src.py", line 152, in run
   self.build_sources()
 File "/tmp/buildd/python-numpy-1.5.1/numpy/distutils/command/build_src.py", line 169, in build_sources
   self.build_extension_sources(ext)
 File "/tmp/buildd/python-numpy-1.5.1/numpy/distutils/command/build_src.py", line 328, in build_extension_sources
   sources = self.generate_sources(sources, ext)
 File "/tmp/buildd/python-numpy-1.5.1/numpy/distutils/command/build_src.py", line 385, in generate_sources
   source = func(extension, build_dir)
 File "numpy/core/setup.py", line 434, in generate_config_h
   rep = check_long_double_representation(config_cmd)
 File "numpy/core/setup_common.py", line 136, in check_long_double_representation
   type = long_double_representation(pyod(object))
 File "numpy/core/setup_common.py", line 268, in long_double_representation
   raise ValueError("Unrecognized format (%s)" % saw)
ValueError: Unrecognized format (['000', '000', '000', '000', '001', '043', '105', '147', '211', '253', '315', '357', '300', '031', '000', '000', '353', '171', '242', '240', '000', '000', '000', '000', '376', '334', '272', '230', '166', '124', '062', '020'])
[58723 refs]
dh_auto_build: python2.6-dbg setup.py build --force returned exit code 1
```

the reported traceback is for 1.5.1 but it applies also for 1.6.1.

Regards,
Sandro

**Comment by thouis** [comment]
Attachment in Trac by trac user schwab, 2012-01-11: [xx](http://projects.scipy.org/numpy/attachment/ticket/2014/xx)

**Comment by thouis** [comment]
Comment in Trac by trac user schwab, 2012-01-11

**Comment by thouis** [comment]
Comment in Trac by atmention:sandrotosi, 2012-04-10

Hi all, FYI I'm about to include this patch in the Debian package for numpy.
