### ISSUE TITLE
cross doesn't broadcast correctly (migrated from Trac #2032)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3579]
Original ticket http://projects.scipy.org/numpy/ticket/2032
Reported 2012-01-27 by atmention:girving, assigned to unknown.

cross doesn't broadcast correctly in all cases.  Here's an example:

```
>>> cross(random.randn(2,1,3),random.randn(5,3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/numpy/core/numeric.py", line 1377, in cross
    x = a[1]*b[2] - a[2]*b[1]
ValueError: operands could not be broadcast together with shapes (1,2) (5)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:girving, 2012-01-27

I haven't analyzed numpy.cross, because it's somewhat complicated, but here's a simpler routine which works at least in my case:

```
def cross(u,v):
  # The numpy version doesn't always broadcast correctly, so we roll our own cross product routine.
  # Unfortunately, it's impossible to make 1D/2D cross products work correctly together with
  # broadcasting, so stick to 3D for now.
  assert u.shape[-1]==v.shape[-1]==3
  uv = empty(broadcast(u,v).shape)
  u0,u1,u2 = u[...,0],u[...,1],u[...,2]
  v0,v1,v2 = v[...,0],v[...,1],v[...,2]
  uv[...,0] = u1*v2-u2*v1
  uv[...,1] = u2*v0-u0*v2
  uv[...,2] = u0*v1-u1*v0
  return uv
```

**Comment by thouis** [comment]
Comment in Trac by atmention:girving, 2012-01-27

Trying again with better formatting:

```
def cross(u,v):
  # The numpy version doesn't always broadcast correctly, so we roll our own cross product routine.
  # Unfortunately, it's impossible to make 1D/2D cross products work correctly together with
  # broadcasting, so stick to 3D for now.
  assert u.shape[-1]==v.shape[-1]==3
  uv = empty(broadcast(u,v).shape)
  u0,u1,u2 = u[...,0],u[...,1],u[...,2]
  v0,v1,v2 = v[...,0],v[...,1],v[...,2]
  uv[...,0] = u1*v2-u2*v1
  uv[...,1] = u2*v0-u0*v2
  uv[...,2] = u0*v1-u1*v0
  return uv
```
