### ISSUE TITLE
Broadcasting with masked array doesn't work with divide (after tile instruction) (migrated from Trac #2035)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3582]
Original ticket http://projects.scipy.org/numpy/ticket/2035
Reported 2012-02-02 by trac user elephantterrible, assigned to unknown.

Broadcasting in a division does not work after a tile instruction.

See attached script to reproduce.

If the tile instruction is commented out, the division works.
Division also works if numpy.divide() is used, or if there's no masked value.

Python gives the following error:
    Traceback (most recent call last):
      File "ma_tiling_issue.py", line 18, in <module>
        a/100. #raises ValueError: invalid return array shape
      File "/usr/local/lib/python2.7/dist-packages/numpy/ma/core.py", line 3654, in **div**
        return divide(self, other)
      File "/usr/local/lib/python2.7/dist-packages/numpy/ma/core.py", line 1078, in **call**
        m |= ma
    ValueError: non-broadcastable output operand with shape (3,3,3) doesn't match the broadcast shape (1,3,3,3)

The error occurs in all numpy versions (1.5.1, 1.6.1, 2.0.0.dev) with python 2.7.1

The original bug discussion is on numpy-discuss:
http://www.mail-archive.com/numpy-discussionatmention:scipy.org/msg35146.html

**Comment by thouis** [comment]
Attachment in Trac by trac user elephantterrible, 2012-02-02: [ma_tiling_issue.py](http://projects.scipy.org/numpy/attachment/ticket/2035/ma_tiling_issue.py)

**Comment by thouis** [comment]
Comment in Trac by atmention:bsouthey, 2012-02-02

The error appears to be in call to 'numpy.core.numeric.array' at line 827 numpy/lib/shape_base.py:
    c = _nx.array(A,copy=False,subok=True,ndmin=d)
Also, setting 'copy=True' in the call does not change anything.
    >>> import numpy as np
    >>> np.__version__
    '2.0.0.dev-55472ca'
    >>> import numpy.core.numeric as _nx
    >>> b=np.ma.array([[1,2,3],[4,5,6]], mask=[[1,0,0],[1,0,0]])
    >>> d=4
    >>> c = _nx.array(b,copy=True,subok=True,ndmin=d)
    >>> b/4
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python2.7/site-packages/numpy/ma/core.py", line 3654, in __div__
        return divide(self, other)
      File "/usr/lib64/python2.7/site-packages/numpy/ma/core.py", line 1078, in **call**
        m |= ma
    ValueError: non-broadcastable output operand with shape (2,3) doesn't match the broadcast shape (1,1,2,3)
    >>> c = _nx.array(b,copy=False,subok=True,ndmin=d)
    >>> b/4
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib64/python2.7/site-packages/numpy/ma/core.py", line 3654, in __div__
        return divide(self, other)
      File "/usr/lib64/python2.7/site-packages/numpy/ma/core.py", line 1078, in **call**
        m |= ma
    ValueError: non-broadcastable output operand with shape (2,3) doesn't match the broadcast shape (1,1,2,3)
    >>>

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2012-02-20

<reformat description>

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2012-02-20
