### ISSUE TITLE
Blasdot tests with "out" argument failing (migrated from Trac #2060)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3607]
Original ticket http://projects.scipy.org/numpy/ticket/2060
Reported 2012-02-20 by atmention:rgommers, assigned to unknown.

On Python 2.5 seeing these failures, works on 3.1:

```
======================================================================
ERROR: test_blasdot.test_dot_3args
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python25\lib\site-packages\nose-0.11.3-py2.5.egg\nose\case.py", line 186, in runTest
    self.test(*self.arg)
  File "C:\Python25\Lib\site-packages\numpy\core\tests\test_blasdot.py", line 51, in test_dot_3args
    np.dot(f,v,r)
TypeError: function takes exactly 2 arguments (3 given)

======================================================================
ERROR: test_blasdot.test_dot_3args_errors
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python25\lib\site-packages\nose-0.11.3-py2.5.egg\nose\case.py", line 186, in runTest
    self.test(*self.arg)
  File "C:\Python25\Lib\site-packages\numpy\core\tests\test_blasdot.py", line 69, in test_dot_3args_errors
    assert_raises(ValueError, np.dot, f, v, r)
  File "C:\Python25\Lib\site-packages\numpy\testing\utils.py", line 1053, in assert_raises
    return nose.tools.assert_raises(*args,**kwargs)
  File "C:\Python25\lib\unittest.py", line 320, in failUnlessRaises
    callableObj(*args, **kwargs)
TypeError: function takes exactly 2 arguments (3 given)
```

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2012-02-20

Have to add, this is Windows (= MinGW on OS X).

**Comment by thouis** [comment]
Comment in Trac by atmention:pv, 2012-02-20

Is it importing the correct version of Numpy? What does `print numpy.dot.__module__` say? I have a hard time understanding what goes wrong here...

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2012-02-20

```
>>> import numpy 
>>> numpy.__version__   # current master
'2.0.0.dev-Unknown'
>>> print numpy.dot.__module__
numpy.core._dotblas
>>> numpy.__file__
'Z:\\Users\\rgommers\\.wine\\drive_c\\Python25\\lib\\site-packages\\numpy\\__init__.pyc'
```

I forgot to post the relevant (I think) build warnings, see below. This is on OS X, if necessary I can do another Windows build.

```
gcc-4.0 -o build/scons/numpy/core/_dotblas.os -c -O2 -fno-strict-aliasing -DNDEBUG -fomit-frame-pointer -g -Wall -Wstrict-prototypes -fPIC -Ibuild/scons/numpy/core/src/private -Ibuild/scons/numpy/core/include -Ibuild/scons/numpy/core -Ibuild/scons/numpy/core/include/numpy -I/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 -I/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 build/scons/numpy/core/blasdot/_dotblas.c
In file included from build/scons/numpy/core/include/numpy/ndarraytypes.h:1972,
                 from build/scons/numpy/core/include/numpy/ndarrayobject.h:17,
                 from build/scons/numpy/core/include/numpy/arrayobject.h:15,
                 from build/scons/numpy/core/blasdot/_dotblas.c:6:
build/scons/numpy/core/include/numpy/npy_deprecated_api.h:11:2: warning: #warning "Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API"
build/scons/numpy/core/blasdot/_dotblas.c: In function 'dotblas_matrixproduct':
build/scons/numpy/core/blasdot/_dotblas.c:239: warning: comparison of distinct pointer types lacks a cast
build/scons/numpy/core/blasdot/_dotblas.c:257: warning: passing argument 3 of '*(PyArray_API + 1120u)' from incompatible pointer type
build/scons/numpy/core/blasdot/_dotblas.c:292: warning: passing argument 3 of '*(PyArray_API + 1120u)' from incompatible pointer type
```

**Comment by thouis** [comment]
Comment in Trac by atmention:rgommers, 2012-03-25

The compile warnings have disappeared in current master (3503c5f4) and the tests pass now. I can't reproduce the issue either with commit 08338bd from two months ago. Unfortunately I didn't report the commit ID for which I had the issue. I'll close this as invalid, because it will take too much time to track down where the problem appeared/disappeared.
