### ISSUE TITLE
ndarray.dot rejects "out" argument (migrated from Trac #2096)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3642]
Original ticket http://projects.scipy.org/numpy/ticket/2096
Reported 2012-04-02 by trac user JLull, assigned to unknown.

Testing with python 2.7.2, Pywin32 build 217, and numpy-1.6.1-win32-superpack-python2.7.exe, any call to ndarray.dot() with an "out" argument fails:

> > > import numpy
> > > numpy.version.version
> > > '1.6.1'
> > > a=numpy.array(((1,2),(3,4)))
> > > b=numpy.array((5,6))
> > > c=numpy.array((7,8))
> > > a.dot(b)
> > > array([17, 39])
> > > a.dot(b,c)
> > > Traceback (most recent call last):
> > >   File "<interactive input>", line 1, in <module>
> > > TypeError: function takes exactly 1 argument (2 given)
> > > a.dot(b,out=c)
> > > Traceback (most recent call last):
> > >   File "<interactive input>", line 1, in <module>
> > > TypeError: dot() takes no keyword arguments

Similar calls to numpy.dot() succeed:

> > > numpy.dot(a,b,c)
> > > array([17, 39])
> > > numpy.dot(a,b,out=c)
> > > array([17, 39])

Similar calls to matrix.dot() with an "out" argument also fail (not shown)

**Comment by thouis** [comment]
Comment in Trac by trac user JLull, 2012-04-03

I apologize for the really horrible formatting of my original description. This should be clearer.

Testing with:
    python 2.7.2\
    Pywin32 build 217
    numpy-1.6.1-win32-superpack-python2.7.exe
Any call to ndarray.dot() with an "out" argument fails:
    >>> import numpy
    >>> numpy.version.version
    '1.6.1'
    >>> a=numpy.array(((1,2),(3,4)))
    >>> b=numpy.array((5,6))
    >>> c=numpy.array((7,8))
    >>> a.dot(b)
    array([17, 39])
    >>> a.dot(b,c)
    Traceback (most recent call last):
      File "<interactive input>", line 1, in <module>
    TypeError: function takes exactly 1 argument (2 given)
    >>> a.dot(b,out=c)
    Traceback (most recent call last):
      File "<interactive input>", line 1, in <module>
    TypeError: dot() takes no keyword arguments
Equivalent calls to numpy.dot() succeed:
    >>> numpy.dot(a,b,c)
    array([17, 39])
    >>> numpy.dot(a,b,out=c)
    array([17, 39])
Similar calls to matrix.dot() with an "out" argument also fail (not shown)
