### ISSUE TITLE
Production code is importing numpy testcases (migrated from Trac #2153)

### ISSUE THREAD

**Issue by thouis** [thouis/numpy-trac-migration#3695]
Original ticket http://projects.scipy.org/numpy/ticket/2153
Reported 2012-06-06 by trac user ms4py, assigned to unknown.

Numpy is importing its testcases on a default import, this is a very bad style. See as reference:

```
>>> class A:
...   pass
... 
>>> sys.modules['unittest'] = A
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/site-packages/numpy/__init__.py", line 137, in <module>
    import add_newdocs
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/site-packages/numpy/add_newdocs.py", line 9, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/site-packages/numpy/lib/__init__.py", line 4, in <module>
    from type_check import *
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/site-packages/numpy/lib/type_check.py", line 8, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from numpy.testing import Tester
  File "/usr/local/Cellar/python/2.7.3/lib/python2.7/site-packages/numpy/testing/__init__.py", line 8, in <module>
    from unittest import TestCase
ImportError: cannot import name TestCase
```

(I know how to solve this Exception, that is not the point)

**Comment by thouis** [comment]
Comment in Trac by atmention:rkern, 2012-06-06

It imports some testing _utilities_ in `numpy.testing` because they are part of the public API for use by other libraries, but not the test cases themselves (which are in directories named `tests`, not `testing`).
